"use client";

import Link from "next/link";
import { EnumValues, type ApiFieldItem } from "../../_components/doc-components";
import { SingleEndpointReferencePage } from "../../_components/single-endpoint-page";

const AUTH_FIELDS: ApiFieldItem[] = [
  { name: "Authorization", type: "Bearer <token>", meta: "In header", description: "Workspace API key." },
];

const BODY_FIELDS: ApiFieldItem[] = [
  { name: "profile_id?", type: "string", description: "Profile that should own the connected account. Required when the workspace has multiple profiles." },
  { name: "platform", type: "string", description: <>OAuth platform key. Facebook Page OAuth is beta/admin-gated; Bluesky uses <Link href="/docs/api/accounts/connect">direct credentials</Link> instead.<EnumValues values={["twitter", "linkedin", "instagram", "threads", "youtube", "tiktok", "pinterest", "facebook"]} /></> },
  { name: "redirect_url?", type: "string", description: "Optional app URL where the browser should land after OAuth completes. This is not the OAuth callback URL or platform redirect_uri." },
];

const RESPONSE_200_FIELDS: ApiFieldItem[] = [
  { name: "auth_url", type: "string", description: "Browser URL to open for the OAuth authorization flow." },
];

const ERROR_FIELDS: ApiFieldItem[] = [
  { name: "error.code", type: "string", description: 'Common values include "UNAUTHORIZED", "VALIDATION_ERROR", and "FACEBOOK_DISABLED".' },
  { name: "error.normalized_code", type: "string", description: 'Lowercase alias such as "unauthorized" or "validation_error".' },
  { name: "error.message", type: "string", description: "Human-readable error message." },
  { name: "request_id", type: "string", description: "Request identifier for debugging and support." },
];

const SNIPPETS = [
  {
    lang: "curl",
    label: "cURL",
    code: `curl -X POST "https://api.unipost.dev/v1/oauth/connect" \\
  -H "Authorization: Bearer $UNIPOST_API_KEY" \\
  -H "Content-Type: application/json" \\
  -d '{
    "profile_id": "pr_brand_us",
    "platform": "linkedin",
    "redirect_url": "https://app.acme.com/integrations/done"
  }'`,
  },
  {
    lang: "js",
    label: "Node.js",
    code: `const { auth_url } = await client.connect.getConnectUrl({
  profileId: "pr_brand_us",
  platform: "linkedin",
});

console.log(auth_url);`,
  },
  {
    lang: "python",
    label: "Python",
    code: `connect = client.connect.get_connect_url(
  profile_id="pr_brand_us",
  platform="linkedin",
)

print(connect.auth_url)`,
  },
  {
    lang: "go",
    label: "Go",
    code: `connect, err := client.Connect.GetConnectURL(ctx, &unipost.GetConnectURLParams{
  ProfileID: "pr_brand_us",
  Platform:  "linkedin",
})
if err != nil {
  log.Fatal(err)
}

fmt.Println(connect.AuthURL)`,
  },
  {
    lang: "java",
    label: "Java",
    code: `var connect = client.connect().getConnectUrl(Map.of(
    "profile_id", "pr_brand_us",
    "platform", "linkedin"
));

System.out.println(connect.get("auth_url").asText());`,
  },
];

const RESPONSE_SNIPPETS = [
  {
    lang: "json",
    label: "200",
    code: `{
  "data": {
    "auth_url": "https://www.linkedin.com/oauth/v2/authorization?response_type=code&client_id=..."
  }
}`,
  },
];

export default function OAuthConnectPage() {
  return (
    <SingleEndpointReferencePage
      section="accounts"
      title="Connect account (OAuth)"
      description={
        <>
          Starts an OAuth account connection flow by returning an auth_url you
          open in the browser. Use this for workspace-owned accounts, then list
          accounts afterward to find the new UniPost account ID. For
          customer-owned accounts, use{" "}
          <Link href="/docs/connect-sessions">Connect Sessions</Link>.
        </>
      }
      method="POST"
      path="/v1/oauth/connect"
      requestSections={[
        { title: "Authorization", items: AUTH_FIELDS },
        { title: "Request Body", items: BODY_FIELDS },
      ]}
      responses={[
        { code: "200", fields: RESPONSE_200_FIELDS },
        { code: "401", fields: ERROR_FIELDS },
        { code: "403", fields: ERROR_FIELDS },
        { code: "422", fields: ERROR_FIELDS },
        { code: "500", fields: ERROR_FIELDS },
      ]}
      snippets={SNIPPETS}
      responseSnippets={RESPONSE_SNIPPETS}
    >
      <section className="api-field-section">
        <h2 className="api-field-section-title">Callback URLs</h2>
        <p>
          <code>redirect_url</code> is your post-OAuth landing page. The platform
          OAuth callback URL is generated by UniPost and must match the callback
          registered for the OAuth app being used.
        </p>
      </section>
    </SingleEndpointReferencePage>
  );
}
