// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_search_history.sql

package db

import (
	"context"
)

const cleanupExpiredAdminSearchHistory = `-- name: CleanupExpiredAdminSearchHistory :execrows
DELETE FROM admin_search_history
WHERE last_used_at < NOW() - INTERVAL '180 days'
`

func (q *Queries) CleanupExpiredAdminSearchHistory(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupExpiredAdminSearchHistory)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAdminSearchHistory = `-- name: DeleteAdminSearchHistory :execrows
DELETE FROM admin_search_history
WHERE id = $1
  AND admin_user_id = $2
`

type DeleteAdminSearchHistoryParams struct {
	ID          string `json:"id"`
	AdminUserID string `json:"admin_user_id"`
}

func (q *Queries) DeleteAdminSearchHistory(ctx context.Context, arg DeleteAdminSearchHistoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAdminSearchHistory, arg.ID, arg.AdminUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAdminSearchHistory = `-- name: ListAdminSearchHistory :many
SELECT id, admin_user_id, field_key, value, value_normalized, usage_count, first_used_at, last_used_at, created_at, updated_at FROM admin_search_history
WHERE admin_user_id = $1
  AND field_key = $2
ORDER BY last_used_at DESC, usage_count DESC
LIMIT $3
`

type ListAdminSearchHistoryParams struct {
	AdminUserID string `json:"admin_user_id"`
	FieldKey    string `json:"field_key"`
	LimitRows   int32  `json:"limit_rows"`
}

func (q *Queries) ListAdminSearchHistory(ctx context.Context, arg ListAdminSearchHistoryParams) ([]AdminSearchHistory, error) {
	rows, err := q.db.Query(ctx, listAdminSearchHistory, arg.AdminUserID, arg.FieldKey, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminSearchHistory{}
	for rows.Next() {
		var i AdminSearchHistory
		if err := rows.Scan(
			&i.ID,
			&i.AdminUserID,
			&i.FieldKey,
			&i.Value,
			&i.ValueNormalized,
			&i.UsageCount,
			&i.FirstUsedAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneAdminSearchHistory = `-- name: PruneAdminSearchHistory :execrows
DELETE FROM admin_search_history AS ash
WHERE id IN (
    SELECT inner_ash.id
    FROM admin_search_history AS inner_ash
    WHERE inner_ash.admin_user_id = $1
      AND inner_ash.field_key = $2
    ORDER BY inner_ash.last_used_at DESC, inner_ash.usage_count DESC, inner_ash.created_at DESC
    OFFSET $3
)
`

type PruneAdminSearchHistoryParams struct {
	AdminUserID string `json:"admin_user_id"`
	FieldKey    string `json:"field_key"`
	KeepRows    int32  `json:"keep_rows"`
}

func (q *Queries) PruneAdminSearchHistory(ctx context.Context, arg PruneAdminSearchHistoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneAdminSearchHistory, arg.AdminUserID, arg.FieldKey, arg.KeepRows)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertAdminSearchHistory = `-- name: UpsertAdminSearchHistory :one
INSERT INTO admin_search_history (
    admin_user_id,
    field_key,
    value,
    value_normalized
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (admin_user_id, field_key, value_normalized) DO UPDATE
SET value = EXCLUDED.value,
    usage_count = admin_search_history.usage_count + 1,
    last_used_at = NOW(),
    updated_at = NOW()
RETURNING id, admin_user_id, field_key, value, value_normalized, usage_count, first_used_at, last_used_at, created_at, updated_at
`

type UpsertAdminSearchHistoryParams struct {
	AdminUserID     string `json:"admin_user_id"`
	FieldKey        string `json:"field_key"`
	Value           string `json:"value"`
	ValueNormalized string `json:"value_normalized"`
}

func (q *Queries) UpsertAdminSearchHistory(ctx context.Context, arg UpsertAdminSearchHistoryParams) (AdminSearchHistory, error) {
	row := q.db.QueryRow(ctx, upsertAdminSearchHistory,
		arg.AdminUserID,
		arg.FieldKey,
		arg.Value,
		arg.ValueNormalized,
	)
	var i AdminSearchHistory
	err := row.Scan(
		&i.ID,
		&i.AdminUserID,
		&i.FieldKey,
		&i.Value,
		&i.ValueNormalized,
		&i.UsageCount,
		&i.FirstUsedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
