// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (id, project_id, name, prefix, key_hash, environment, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, name, prefix, created_at, last_used_at, expires_at, revoked_at, key_hash, environment
`

type CreateAPIKeyParams struct {
	ID          string             `json:"id"`
	ProjectID   string             `json:"project_id"`
	Name        string             `json:"name"`
	Prefix      string             `json:"prefix"`
	KeyHash     string             `json:"key_hash"`
	Environment string             `json:"environment"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Prefix,
		arg.KeyHash,
		arg.Environment,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Prefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.KeyHash,
		&i.Environment,
	)
	return i, err
}

const getAPIKey = `-- name: GetAPIKey :one
SELECT id, project_id, name, prefix, created_at, last_used_at, expires_at, revoked_at, key_hash, environment FROM api_keys WHERE id = $1
`

func (q *Queries) GetAPIKey(ctx context.Context, id string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKey, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Prefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.KeyHash,
		&i.Environment,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, project_id, name, prefix, created_at, last_used_at, expires_at, revoked_at, key_hash, environment FROM api_keys WHERE key_hash = $1
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Prefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.KeyHash,
		&i.Environment,
	)
	return i, err
}

const listAPIKeysByProject = `-- name: ListAPIKeysByProject :many
SELECT id, project_id, name, prefix, created_at, last_used_at, expires_at, revoked_at, key_hash, environment FROM api_keys
WHERE project_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByProject(ctx context.Context, projectID string) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Prefix,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.KeyHash,
			&i.Environment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :one
UPDATE api_keys SET revoked_at = NOW()
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, name, prefix, created_at, last_used_at, expires_at, revoked_at, key_hash, environment
`

type RevokeAPIKeyParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, revokeAPIKey, arg.ID, arg.ProjectID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Prefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.KeyHash,
		&i.Environment,
	)
	return i, err
}

const updateAPIKeyLastUsedAt = `-- name: UpdateAPIKeyLastUsedAt :exec
UPDATE api_keys SET last_used_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateAPIKeyLastUsedAt(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateAPIKeyLastUsedAt, id)
	return err
}
