// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_metrics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAPIMetricsOverall = `-- name: GetAPIMetricsOverall :one
SELECT
  COUNT(*)::INTEGER AS total_calls,
  COUNT(*) FILTER (WHERE status_code < 400)::INTEGER AS success_count,
  COUNT(*) FILTER (WHERE status_code >= 400 AND status_code < 500)::INTEGER AS client_error_count,
  COUNT(*) FILTER (WHERE status_code >= 500)::INTEGER AS server_error_count,
  COALESCE(percentile_cont(0.50) WITHIN GROUP (ORDER BY duration_ms), 0)::INTEGER AS p50_ms,
  COALESCE(percentile_cont(0.95) WITHIN GROUP (ORDER BY duration_ms), 0)::INTEGER AS p95_ms,
  COALESCE(percentile_cont(0.99) WITHIN GROUP (ORDER BY duration_ms), 0)::INTEGER AS p99_ms
FROM api_metrics
WHERE workspace_id = $1
  AND created_at >= $2
  AND created_at <= $3
`

type GetAPIMetricsOverallParams struct {
	WorkspaceID string             `json:"workspace_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type GetAPIMetricsOverallRow struct {
	TotalCalls       int32 `json:"total_calls"`
	SuccessCount     int32 `json:"success_count"`
	ClientErrorCount int32 `json:"client_error_count"`
	ServerErrorCount int32 `json:"server_error_count"`
	P50Ms            int32 `json:"p50_ms"`
	P95Ms            int32 `json:"p95_ms"`
	P99Ms            int32 `json:"p99_ms"`
}

// Overall stats for a workspace within a time range.
func (q *Queries) GetAPIMetricsOverall(ctx context.Context, arg GetAPIMetricsOverallParams) (GetAPIMetricsOverallRow, error) {
	row := q.db.QueryRow(ctx, getAPIMetricsOverall, arg.WorkspaceID, arg.CreatedAt, arg.CreatedAt_2)
	var i GetAPIMetricsOverallRow
	err := row.Scan(
		&i.TotalCalls,
		&i.SuccessCount,
		&i.ClientErrorCount,
		&i.ServerErrorCount,
		&i.P50Ms,
		&i.P95Ms,
		&i.P99Ms,
	)
	return i, err
}

const getAPIMetricsSummary = `-- name: GetAPIMetricsSummary :many
SELECT
  path,
  method,
  COUNT(*)::INTEGER AS total_calls,
  COUNT(*) FILTER (WHERE status_code < 400)::INTEGER AS success_count,
  COUNT(*) FILTER (WHERE status_code >= 400 AND status_code < 500)::INTEGER AS client_error_count,
  COUNT(*) FILTER (WHERE status_code >= 500)::INTEGER AS server_error_count,
  COALESCE(percentile_cont(0.50) WITHIN GROUP (ORDER BY duration_ms), 0)::INTEGER AS p50_ms,
  COALESCE(percentile_cont(0.95) WITHIN GROUP (ORDER BY duration_ms), 0)::INTEGER AS p95_ms,
  COALESCE(percentile_cont(0.99) WITHIN GROUP (ORDER BY duration_ms), 0)::INTEGER AS p99_ms,
  COALESCE(AVG(duration_ms), 0)::INTEGER AS avg_ms
FROM api_metrics
WHERE workspace_id = $1
  AND created_at >= $2
  AND created_at <= $3
GROUP BY path, method
ORDER BY total_calls DESC
`

type GetAPIMetricsSummaryParams struct {
	WorkspaceID string             `json:"workspace_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type GetAPIMetricsSummaryRow struct {
	Path             string `json:"path"`
	Method           string `json:"method"`
	TotalCalls       int32  `json:"total_calls"`
	SuccessCount     int32  `json:"success_count"`
	ClientErrorCount int32  `json:"client_error_count"`
	ServerErrorCount int32  `json:"server_error_count"`
	P50Ms            int32  `json:"p50_ms"`
	P95Ms            int32  `json:"p95_ms"`
	P99Ms            int32  `json:"p99_ms"`
	AvgMs            int32  `json:"avg_ms"`
}

// Per-endpoint summary for a workspace within a time range.
// Returns total calls, success (2xx/3xx), client errors (4xx),
// server errors (5xx), and latency percentiles.
func (q *Queries) GetAPIMetricsSummary(ctx context.Context, arg GetAPIMetricsSummaryParams) ([]GetAPIMetricsSummaryRow, error) {
	rows, err := q.db.Query(ctx, getAPIMetricsSummary, arg.WorkspaceID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAPIMetricsSummaryRow{}
	for rows.Next() {
		var i GetAPIMetricsSummaryRow
		if err := rows.Scan(
			&i.Path,
			&i.Method,
			&i.TotalCalls,
			&i.SuccessCount,
			&i.ClientErrorCount,
			&i.ServerErrorCount,
			&i.P50Ms,
			&i.P95Ms,
			&i.P99Ms,
			&i.AvgMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAPIMetricsTrend = `-- name: GetAPIMetricsTrend :many
SELECT
  date_trunc('hour', created_at)::timestamptz AS bucket,
  COUNT(*)::INTEGER AS total_calls,
  COUNT(*) FILTER (WHERE status_code < 400)::INTEGER AS success_count,
  COUNT(*) FILTER (WHERE status_code >= 400)::INTEGER AS error_count
FROM api_metrics
WHERE workspace_id = $1
  AND created_at >= $2
  AND created_at <= $3
GROUP BY bucket
ORDER BY bucket
`

type GetAPIMetricsTrendParams struct {
	WorkspaceID string             `json:"workspace_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type GetAPIMetricsTrendRow struct {
	Bucket       pgtype.Timestamptz `json:"bucket"`
	TotalCalls   int32              `json:"total_calls"`
	SuccessCount int32              `json:"success_count"`
	ErrorCount   int32              `json:"error_count"`
}

// Hourly call counts for a workspace within a time range.
// Used for the usage-over-time chart.
func (q *Queries) GetAPIMetricsTrend(ctx context.Context, arg GetAPIMetricsTrendParams) ([]GetAPIMetricsTrendRow, error) {
	rows, err := q.db.Query(ctx, getAPIMetricsTrend, arg.WorkspaceID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAPIMetricsTrendRow{}
	for rows.Next() {
		var i GetAPIMetricsTrendRow
		if err := rows.Scan(
			&i.Bucket,
			&i.TotalCalls,
			&i.SuccessCount,
			&i.ErrorCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAPIMetric = `-- name: InsertAPIMetric :exec
INSERT INTO api_metrics (workspace_id, method, path, status_code, duration_ms)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAPIMetricParams struct {
	WorkspaceID string `json:"workspace_id"`
	Method      string `json:"method"`
	Path        string `json:"path"`
	StatusCode  int32  `json:"status_code"`
	DurationMs  int32  `json:"duration_ms"`
}

func (q *Queries) InsertAPIMetric(ctx context.Context, arg InsertAPIMetricParams) error {
	_, err := q.db.Exec(ctx, insertAPIMetric,
		arg.WorkspaceID,
		arg.Method,
		arg.Path,
		arg.StatusCode,
		arg.DurationMs,
	)
	return err
}
