// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_send_attempts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailSendAttemptAudit = `-- name: CreateEmailSendAttemptAudit :one
INSERT INTO email_send_attempts (
  event_key,
  recipient_user_id,
  recipient_email,
  workspace_id,
  provider,
  provider_template_id,
  idempotency_key,
  delivery_class,
  status,
  subject_snapshot,
  data_variables_snapshot,
  trigger_source,
  trigger_reference_id,
  attempt_count,
  last_error,
  attempted_at,
  sent_at
)
VALUES (
  $1,
  NULLIF($2, ''),
  $3,
  NULLIF($4, ''),
  $5,
  NULLIF($6, ''),
  $7,
  $8,
  'pending',
  NULLIF($9, ''),
  COALESCE($10::JSONB, '{}'::JSONB),
  NULLIF($11, ''),
  NULLIF($12, ''),
  1,
  NULL,
  NOW(),
  NULL
)
ON CONFLICT (provider, idempotency_key) WHERE idempotency_key <> ''
DO UPDATE SET
  event_key = CASE WHEN email_send_attempts.status = 'sent' THEN email_send_attempts.event_key ELSE EXCLUDED.event_key END,
  recipient_user_id = CASE WHEN email_send_attempts.status = 'sent' THEN email_send_attempts.recipient_user_id ELSE EXCLUDED.recipient_user_id END,
  recipient_email = CASE WHEN email_send_attempts.status = 'sent' THEN email_send_attempts.recipient_email ELSE EXCLUDED.recipient_email END,
  workspace_id = CASE WHEN email_send_attempts.status = 'sent' THEN email_send_attempts.workspace_id ELSE EXCLUDED.workspace_id END,
  provider_template_id = CASE WHEN email_send_attempts.status = 'sent' THEN email_send_attempts.provider_template_id ELSE EXCLUDED.provider_template_id END,
  delivery_class = CASE WHEN email_send_attempts.status = 'sent' THEN email_send_attempts.delivery_class ELSE EXCLUDED.delivery_class END,
  status = CASE WHEN email_send_attempts.status = 'sent' THEN email_send_attempts.status ELSE 'pending' END,
  subject_snapshot = CASE WHEN email_send_attempts.status = 'sent' THEN email_send_attempts.subject_snapshot ELSE EXCLUDED.subject_snapshot END,
  data_variables_snapshot = CASE WHEN email_send_attempts.status = 'sent' THEN email_send_attempts.data_variables_snapshot ELSE EXCLUDED.data_variables_snapshot END,
  trigger_source = CASE WHEN email_send_attempts.status = 'sent' THEN email_send_attempts.trigger_source ELSE EXCLUDED.trigger_source END,
  trigger_reference_id = CASE WHEN email_send_attempts.status = 'sent' THEN email_send_attempts.trigger_reference_id ELSE EXCLUDED.trigger_reference_id END,
  attempt_count = CASE WHEN email_send_attempts.status = 'sent' THEN email_send_attempts.attempt_count ELSE email_send_attempts.attempt_count + 1 END,
  last_error = CASE WHEN email_send_attempts.status = 'sent' THEN email_send_attempts.last_error ELSE NULL END,
  attempted_at = CASE WHEN email_send_attempts.status = 'sent' THEN email_send_attempts.attempted_at ELSE NOW() END,
  sent_at = CASE WHEN email_send_attempts.status = 'sent' THEN email_send_attempts.sent_at ELSE NULL END,
  updated_at = CASE WHEN email_send_attempts.status = 'sent' THEN email_send_attempts.updated_at ELSE NOW() END
RETURNING id, event_key, recipient_user_id, recipient_email, workspace_id, provider, provider_template_id, idempotency_key, delivery_class, status, subject_snapshot, data_variables_snapshot, trigger_source, trigger_reference_id, attempt_count, last_error, attempted_at, sent_at, created_at, updated_at
`

type CreateEmailSendAttemptAuditParams struct {
	EventKey              string      `json:"event_key"`
	RecipientUserID       interface{} `json:"recipient_user_id"`
	RecipientEmail        string      `json:"recipient_email"`
	WorkspaceID           interface{} `json:"workspace_id"`
	Provider              string      `json:"provider"`
	ProviderTemplateID    interface{} `json:"provider_template_id"`
	IdempotencyKey        string      `json:"idempotency_key"`
	DeliveryClass         string      `json:"delivery_class"`
	SubjectSnapshot       interface{} `json:"subject_snapshot"`
	DataVariablesSnapshot []byte      `json:"data_variables_snapshot"`
	TriggerSource         interface{} `json:"trigger_source"`
	TriggerReferenceID    interface{} `json:"trigger_reference_id"`
}

func (q *Queries) CreateEmailSendAttemptAudit(ctx context.Context, arg CreateEmailSendAttemptAuditParams) (EmailSendAttempt, error) {
	row := q.db.QueryRow(ctx, createEmailSendAttemptAudit,
		arg.EventKey,
		arg.RecipientUserID,
		arg.RecipientEmail,
		arg.WorkspaceID,
		arg.Provider,
		arg.ProviderTemplateID,
		arg.IdempotencyKey,
		arg.DeliveryClass,
		arg.SubjectSnapshot,
		arg.DataVariablesSnapshot,
		arg.TriggerSource,
		arg.TriggerReferenceID,
	)
	var i EmailSendAttempt
	err := row.Scan(
		&i.ID,
		&i.EventKey,
		&i.RecipientUserID,
		&i.RecipientEmail,
		&i.WorkspaceID,
		&i.Provider,
		&i.ProviderTemplateID,
		&i.IdempotencyKey,
		&i.DeliveryClass,
		&i.Status,
		&i.SubjectSnapshot,
		&i.DataVariablesSnapshot,
		&i.TriggerSource,
		&i.TriggerReferenceID,
		&i.AttemptCount,
		&i.LastError,
		&i.AttemptedAt,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSkippedEmailSendAttemptAudit = `-- name: CreateSkippedEmailSendAttemptAudit :one
INSERT INTO email_send_attempts (
  event_key,
  recipient_user_id,
  recipient_email,
  workspace_id,
  provider,
  provider_template_id,
  idempotency_key,
  delivery_class,
  status,
  subject_snapshot,
  data_variables_snapshot,
  trigger_source,
  trigger_reference_id,
  attempt_count,
  last_error,
  attempted_at,
  sent_at
)
VALUES (
  $1,
  NULLIF($2, ''),
  $3,
  NULLIF($4, ''),
  $5,
  NULLIF($6, ''),
  $7,
  $8,
  'skipped',
  NULLIF($9, ''),
  COALESCE($10::JSONB, '{}'::JSONB),
  NULLIF($11, ''),
  NULLIF($12, ''),
  1,
  $13,
  NOW(),
  NULL
)
ON CONFLICT (provider, idempotency_key) WHERE idempotency_key <> ''
DO UPDATE SET
  event_key = CASE WHEN email_send_attempts.status = 'sent' THEN email_send_attempts.event_key ELSE EXCLUDED.event_key END,
  recipient_user_id = CASE WHEN email_send_attempts.status = 'sent' THEN email_send_attempts.recipient_user_id ELSE EXCLUDED.recipient_user_id END,
  recipient_email = CASE WHEN email_send_attempts.status = 'sent' THEN email_send_attempts.recipient_email ELSE EXCLUDED.recipient_email END,
  workspace_id = CASE WHEN email_send_attempts.status = 'sent' THEN email_send_attempts.workspace_id ELSE EXCLUDED.workspace_id END,
  provider_template_id = CASE WHEN email_send_attempts.status = 'sent' THEN email_send_attempts.provider_template_id ELSE EXCLUDED.provider_template_id END,
  delivery_class = CASE WHEN email_send_attempts.status = 'sent' THEN email_send_attempts.delivery_class ELSE EXCLUDED.delivery_class END,
  status = CASE WHEN email_send_attempts.status = 'sent' THEN email_send_attempts.status ELSE 'skipped' END,
  subject_snapshot = CASE WHEN email_send_attempts.status = 'sent' THEN email_send_attempts.subject_snapshot ELSE EXCLUDED.subject_snapshot END,
  data_variables_snapshot = CASE WHEN email_send_attempts.status = 'sent' THEN email_send_attempts.data_variables_snapshot ELSE EXCLUDED.data_variables_snapshot END,
  trigger_source = CASE WHEN email_send_attempts.status = 'sent' THEN email_send_attempts.trigger_source ELSE EXCLUDED.trigger_source END,
  trigger_reference_id = CASE WHEN email_send_attempts.status = 'sent' THEN email_send_attempts.trigger_reference_id ELSE EXCLUDED.trigger_reference_id END,
  attempt_count = CASE WHEN email_send_attempts.status = 'sent' THEN email_send_attempts.attempt_count ELSE email_send_attempts.attempt_count + 1 END,
  last_error = CASE WHEN email_send_attempts.status = 'sent' THEN email_send_attempts.last_error ELSE EXCLUDED.last_error END,
  attempted_at = CASE WHEN email_send_attempts.status = 'sent' THEN email_send_attempts.attempted_at ELSE NOW() END,
  sent_at = CASE WHEN email_send_attempts.status = 'sent' THEN email_send_attempts.sent_at ELSE NULL END,
  updated_at = CASE WHEN email_send_attempts.status = 'sent' THEN email_send_attempts.updated_at ELSE NOW() END
RETURNING id, event_key, recipient_user_id, recipient_email, workspace_id, provider, provider_template_id, idempotency_key, delivery_class, status, subject_snapshot, data_variables_snapshot, trigger_source, trigger_reference_id, attempt_count, last_error, attempted_at, sent_at, created_at, updated_at
`

type CreateSkippedEmailSendAttemptAuditParams struct {
	EventKey              string      `json:"event_key"`
	RecipientUserID       interface{} `json:"recipient_user_id"`
	RecipientEmail        string      `json:"recipient_email"`
	WorkspaceID           interface{} `json:"workspace_id"`
	Provider              string      `json:"provider"`
	ProviderTemplateID    interface{} `json:"provider_template_id"`
	IdempotencyKey        string      `json:"idempotency_key"`
	DeliveryClass         string      `json:"delivery_class"`
	SubjectSnapshot       interface{} `json:"subject_snapshot"`
	DataVariablesSnapshot []byte      `json:"data_variables_snapshot"`
	TriggerSource         interface{} `json:"trigger_source"`
	TriggerReferenceID    interface{} `json:"trigger_reference_id"`
	LastError             pgtype.Text `json:"last_error"`
}

func (q *Queries) CreateSkippedEmailSendAttemptAudit(ctx context.Context, arg CreateSkippedEmailSendAttemptAuditParams) (EmailSendAttempt, error) {
	row := q.db.QueryRow(ctx, createSkippedEmailSendAttemptAudit,
		arg.EventKey,
		arg.RecipientUserID,
		arg.RecipientEmail,
		arg.WorkspaceID,
		arg.Provider,
		arg.ProviderTemplateID,
		arg.IdempotencyKey,
		arg.DeliveryClass,
		arg.SubjectSnapshot,
		arg.DataVariablesSnapshot,
		arg.TriggerSource,
		arg.TriggerReferenceID,
		arg.LastError,
	)
	var i EmailSendAttempt
	err := row.Scan(
		&i.ID,
		&i.EventKey,
		&i.RecipientUserID,
		&i.RecipientEmail,
		&i.WorkspaceID,
		&i.Provider,
		&i.ProviderTemplateID,
		&i.IdempotencyKey,
		&i.DeliveryClass,
		&i.Status,
		&i.SubjectSnapshot,
		&i.DataVariablesSnapshot,
		&i.TriggerSource,
		&i.TriggerReferenceID,
		&i.AttemptCount,
		&i.LastError,
		&i.AttemptedAt,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markEmailSendAttemptAuditFailed = `-- name: MarkEmailSendAttemptAuditFailed :exec
UPDATE email_send_attempts
SET status = 'failed',
    last_error = $2,
    updated_at = NOW()
WHERE id = $1 AND status = 'pending'
`

type MarkEmailSendAttemptAuditFailedParams struct {
	ID        string      `json:"id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) MarkEmailSendAttemptAuditFailed(ctx context.Context, arg MarkEmailSendAttemptAuditFailedParams) error {
	_, err := q.db.Exec(ctx, markEmailSendAttemptAuditFailed, arg.ID, arg.LastError)
	return err
}

const markEmailSendAttemptAuditSent = `-- name: MarkEmailSendAttemptAuditSent :exec
UPDATE email_send_attempts
SET status = 'sent',
    last_error = NULL,
    sent_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) MarkEmailSendAttemptAuditSent(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markEmailSendAttemptAuditSent, id)
	return err
}
