// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_preferences.sql

package db

import (
	"context"
)

const getEmailPreferenceForSend = `-- name: GetEmailPreferenceForSend :one
SELECT id, user_id, email, category_key, enabled, source, created_at, updated_at
FROM email_preferences
WHERE user_id = $1
  AND category_key = $2
LIMIT 1
`

type GetEmailPreferenceForSendParams struct {
	UserID      string `json:"user_id"`
	CategoryKey string `json:"category_key"`
}

func (q *Queries) GetEmailPreferenceForSend(ctx context.Context, arg GetEmailPreferenceForSendParams) (EmailPreference, error) {
	row := q.db.QueryRow(ctx, getEmailPreferenceForSend, arg.UserID, arg.CategoryKey)
	var i EmailPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.CategoryKey,
		&i.Enabled,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEmailPreferencesByUser = `-- name: ListEmailPreferencesByUser :many
SELECT id, user_id, email, category_key, enabled, source, created_at, updated_at
FROM email_preferences
WHERE user_id = $1
ORDER BY category_key ASC
`

func (q *Queries) ListEmailPreferencesByUser(ctx context.Context, userID string) ([]EmailPreference, error) {
	rows, err := q.db.Query(ctx, listEmailPreferencesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailPreference{}
	for rows.Next() {
		var i EmailPreference
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.CategoryKey,
			&i.Enabled,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEmailPreference = `-- name: UpsertEmailPreference :one
INSERT INTO email_preferences (
  user_id,
  email,
  category_key,
  enabled,
  source
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
ON CONFLICT (user_id, category_key)
DO UPDATE SET
  email = EXCLUDED.email,
  enabled = EXCLUDED.enabled,
  source = EXCLUDED.source,
  updated_at = NOW()
RETURNING id, user_id, email, category_key, enabled, source, created_at, updated_at
`

type UpsertEmailPreferenceParams struct {
	UserID      string `json:"user_id"`
	Email       string `json:"email"`
	CategoryKey string `json:"category_key"`
	Enabled     bool   `json:"enabled"`
	Source      string `json:"source"`
}

func (q *Queries) UpsertEmailPreference(ctx context.Context, arg UpsertEmailPreferenceParams) (EmailPreference, error) {
	row := q.db.QueryRow(ctx, upsertEmailPreference,
		arg.UserID,
		arg.Email,
		arg.CategoryKey,
		arg.Enabled,
		arg.Source,
	)
	var i EmailPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.CategoryKey,
		&i.Enabled,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
