// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: free_plan_quota_email_reminders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPendingFreePlanQuotaReminder = `-- name: CreatePendingFreePlanQuotaReminder :one
INSERT INTO free_plan_quota_email_reminders (
  workspace_id,
  user_id,
  email,
  period,
  threshold_percent,
  status,
  transactional_id,
  idempotency_key,
  effective_usage,
  completed_usage,
  reserved_usage,
  post_limit,
  failure_reason,
  attempted_at,
  sent_at
)
VALUES ($1, $2, $3, $4, $5, 'pending', $6, $7, $8, $9, $10, $11, NULL, NOW(), NULL)
ON CONFLICT (workspace_id, period, threshold_percent)
DO UPDATE SET
  user_id = EXCLUDED.user_id,
  email = EXCLUDED.email,
  status = 'pending',
  transactional_id = EXCLUDED.transactional_id,
  idempotency_key = EXCLUDED.idempotency_key,
  effective_usage = EXCLUDED.effective_usage,
  completed_usage = EXCLUDED.completed_usage,
  reserved_usage = EXCLUDED.reserved_usage,
  post_limit = EXCLUDED.post_limit,
  failure_reason = NULL,
  attempted_at = NOW(),
  sent_at = NULL,
  updated_at = NOW()
WHERE free_plan_quota_email_reminders.status = 'failed'
RETURNING id, workspace_id, user_id, email, period, threshold_percent, status, transactional_id, idempotency_key, effective_usage, completed_usage, reserved_usage, post_limit, failure_reason, attempted_at, sent_at, created_at, updated_at
`

type CreatePendingFreePlanQuotaReminderParams struct {
	WorkspaceID      string `json:"workspace_id"`
	UserID           string `json:"user_id"`
	Email            string `json:"email"`
	Period           string `json:"period"`
	ThresholdPercent int32  `json:"threshold_percent"`
	TransactionalID  string `json:"transactional_id"`
	IdempotencyKey   string `json:"idempotency_key"`
	EffectiveUsage   int32  `json:"effective_usage"`
	CompletedUsage   int32  `json:"completed_usage"`
	ReservedUsage    int32  `json:"reserved_usage"`
	PostLimit        int32  `json:"post_limit"`
}

func (q *Queries) CreatePendingFreePlanQuotaReminder(ctx context.Context, arg CreatePendingFreePlanQuotaReminderParams) (FreePlanQuotaEmailReminder, error) {
	row := q.db.QueryRow(ctx, createPendingFreePlanQuotaReminder,
		arg.WorkspaceID,
		arg.UserID,
		arg.Email,
		arg.Period,
		arg.ThresholdPercent,
		arg.TransactionalID,
		arg.IdempotencyKey,
		arg.EffectiveUsage,
		arg.CompletedUsage,
		arg.ReservedUsage,
		arg.PostLimit,
	)
	var i FreePlanQuotaEmailReminder
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Email,
		&i.Period,
		&i.ThresholdPercent,
		&i.Status,
		&i.TransactionalID,
		&i.IdempotencyKey,
		&i.EffectiveUsage,
		&i.CompletedUsage,
		&i.ReservedUsage,
		&i.PostLimit,
		&i.FailureReason,
		&i.AttemptedAt,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFreePlanQuotaReminderAttemptedThresholds = `-- name: ListFreePlanQuotaReminderAttemptedThresholds :many
SELECT threshold_percent
FROM free_plan_quota_email_reminders
WHERE workspace_id = $1
  AND period = $2
  AND status IN ('pending', 'sent')
ORDER BY threshold_percent ASC
`

type ListFreePlanQuotaReminderAttemptedThresholdsParams struct {
	WorkspaceID string `json:"workspace_id"`
	Period      string `json:"period"`
}

func (q *Queries) ListFreePlanQuotaReminderAttemptedThresholds(ctx context.Context, arg ListFreePlanQuotaReminderAttemptedThresholdsParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, listFreePlanQuotaReminderAttemptedThresholds, arg.WorkspaceID, arg.Period)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var threshold_percent int32
		if err := rows.Scan(&threshold_percent); err != nil {
			return nil, err
		}
		items = append(items, threshold_percent)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFreePlanQuotaReminderFailed = `-- name: MarkFreePlanQuotaReminderFailed :exec
UPDATE free_plan_quota_email_reminders
SET status = 'failed',
    failure_reason = $2,
    updated_at = NOW()
WHERE id = $1
`

type MarkFreePlanQuotaReminderFailedParams struct {
	ID            string      `json:"id"`
	FailureReason pgtype.Text `json:"failure_reason"`
}

func (q *Queries) MarkFreePlanQuotaReminderFailed(ctx context.Context, arg MarkFreePlanQuotaReminderFailedParams) error {
	_, err := q.db.Exec(ctx, markFreePlanQuotaReminderFailed, arg.ID, arg.FailureReason)
	return err
}

const markFreePlanQuotaReminderSent = `-- name: MarkFreePlanQuotaReminderSent :exec
UPDATE free_plan_quota_email_reminders
SET status = 'sent',
    sent_at = NOW(),
    failure_reason = NULL,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkFreePlanQuotaReminderSent(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markFreePlanQuotaReminderSent, id)
	return err
}
