// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inbox.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupStaleInboxItems = `-- name: CleanupStaleInboxItems :execrows
DELETE FROM inbox_items
WHERE social_account_id IN (
  SELECT id FROM social_accounts
  WHERE disconnected_at IS NOT NULL
    AND disconnected_at < NOW() - INTERVAL '7 days'
)
`

// Cron cleanup: delete inbox items for accounts that have been
// disconnected for more than 7 days.
func (q *Queries) CleanupStaleInboxItems(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupStaleInboxItems)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countUnreadByWorkspace = `-- name: CountUnreadByWorkspace :one
SELECT COUNT(*)::INTEGER AS count
FROM inbox_items i
JOIN social_accounts sa ON sa.id = i.social_account_id
WHERE i.workspace_id = $1
  AND i.is_read = false
  AND sa.status = 'active'
  AND sa.disconnected_at IS NULL
`

func (q *Queries) CountUnreadByWorkspace(ctx context.Context, workspaceID string) (int32, error) {
	row := q.db.QueryRow(ctx, countUnreadByWorkspace, workspaceID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const findAllActiveAccountsByPlatform = `-- name: FindAllActiveAccountsByPlatform :many
SELECT sa.id, sa.external_account_id, p.workspace_id
FROM social_accounts sa
JOIN profiles p ON p.id = sa.profile_id
WHERE sa.platform = $1
  AND sa.disconnected_at IS NULL
  AND sa.status = 'active'
ORDER BY sa.connected_at DESC
`

type FindAllActiveAccountsByPlatformRow struct {
	ID                string `json:"id"`
	ExternalAccountID string `json:"external_account_id"`
	WorkspaceID       string `json:"workspace_id"`
}

// Returns ALL active accounts for a platform across all workspaces.
// Used by webhooks to fan out comments/replies to every workspace.
func (q *Queries) FindAllActiveAccountsByPlatform(ctx context.Context, platform string) ([]FindAllActiveAccountsByPlatformRow, error) {
	rows, err := q.db.Query(ctx, findAllActiveAccountsByPlatform, platform)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindAllActiveAccountsByPlatformRow{}
	for rows.Next() {
		var i FindAllActiveAccountsByPlatformRow
		if err := rows.Scan(&i.ID, &i.ExternalAccountID, &i.WorkspaceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllSocialAccountsByPlatformAndExternalID = `-- name: FindAllSocialAccountsByPlatformAndExternalID :many
SELECT sa.id, sa.external_account_id, p.workspace_id
FROM social_accounts sa
JOIN profiles p ON p.id = sa.profile_id
WHERE sa.platform = $1
  AND sa.external_account_id = $2
  AND sa.disconnected_at IS NULL
  AND sa.status = 'active'
ORDER BY sa.connected_at DESC
`

type FindAllSocialAccountsByPlatformAndExternalIDParams struct {
	Platform          string `json:"platform"`
	ExternalAccountID string `json:"external_account_id"`
}

type FindAllSocialAccountsByPlatformAndExternalIDRow struct {
	ID                string `json:"id"`
	ExternalAccountID string `json:"external_account_id"`
	WorkspaceID       string `json:"workspace_id"`
}

// Webhook routing: find every active social account for platform +
// external_account_id, joining to profiles for workspace_id.
func (q *Queries) FindAllSocialAccountsByPlatformAndExternalID(ctx context.Context, arg FindAllSocialAccountsByPlatformAndExternalIDParams) ([]FindAllSocialAccountsByPlatformAndExternalIDRow, error) {
	rows, err := q.db.Query(ctx, findAllSocialAccountsByPlatformAndExternalID, arg.Platform, arg.ExternalAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindAllSocialAccountsByPlatformAndExternalIDRow{}
	for rows.Next() {
		var i FindAllSocialAccountsByPlatformAndExternalIDRow
		if err := rows.Scan(&i.ID, &i.ExternalAccountID, &i.WorkspaceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAnyActiveAccountByPlatform = `-- name: FindAnyActiveAccountByPlatform :one
SELECT sa.id, sa.external_account_id, p.workspace_id
FROM social_accounts sa
JOIN profiles p ON p.id = sa.profile_id
WHERE sa.platform = $1
  AND sa.disconnected_at IS NULL
  AND sa.status = 'active'
ORDER BY sa.connected_at DESC
LIMIT 1
`

type FindAnyActiveAccountByPlatformRow struct {
	ID                string `json:"id"`
	ExternalAccountID string `json:"external_account_id"`
	WorkspaceID       string `json:"workspace_id"`
}

// Webhook fallback: find any active account for a platform.
// Used when Meta sends a different ID format than what we store.
func (q *Queries) FindAnyActiveAccountByPlatform(ctx context.Context, platform string) (FindAnyActiveAccountByPlatformRow, error) {
	row := q.db.QueryRow(ctx, findAnyActiveAccountByPlatform, platform)
	var i FindAnyActiveAccountByPlatformRow
	err := row.Scan(&i.ID, &i.ExternalAccountID, &i.WorkspaceID)
	return i, err
}

const findDMThreadKeyBySender = `-- name: FindDMThreadKeyBySender :one
SELECT thread_key, parent_external_id, author_name
FROM inbox_items
WHERE social_account_id = $1
  AND source = 'ig_dm'
  AND author_id = $2
  AND thread_key != ''
ORDER BY received_at DESC
LIMIT 1
`

type FindDMThreadKeyBySenderParams struct {
	SocialAccountID string      `json:"social_account_id"`
	AuthorID        pgtype.Text `json:"author_id"`
}

type FindDMThreadKeyBySenderRow struct {
	ThreadKey        string      `json:"thread_key"`
	ParentExternalID pgtype.Text `json:"parent_external_id"`
	AuthorName       pgtype.Text `json:"author_name"`
}

// Find the thread_key and parent_external_id for an existing DM
// conversation with a given sender, so webhook-delivered messages
// can join the same thread as sync-fetched ones.
func (q *Queries) FindDMThreadKeyBySender(ctx context.Context, arg FindDMThreadKeyBySenderParams) (FindDMThreadKeyBySenderRow, error) {
	row := q.db.QueryRow(ctx, findDMThreadKeyBySender, arg.SocialAccountID, arg.AuthorID)
	var i FindDMThreadKeyBySenderRow
	err := row.Scan(&i.ThreadKey, &i.ParentExternalID, &i.AuthorName)
	return i, err
}

const findInboxAccountsByWorkspace = `-- name: FindInboxAccountsByWorkspace :many
SELECT DISTINCT sa.id, sa.profile_id, sa.platform, sa.access_token, sa.refresh_token, sa.token_expires_at, sa.external_account_id, sa.account_name, sa.account_avatar_url, sa.connected_at, sa.disconnected_at, sa.metadata, sa.scope, sa.status, sa.connection_type, sa.connect_session_id, sa.external_user_id, sa.external_user_email, sa.last_refreshed_at
FROM social_accounts sa
JOIN profiles p ON p.id = sa.profile_id
WHERE p.workspace_id = $1
  AND sa.disconnected_at IS NULL
  AND sa.platform IN ('instagram', 'threads', 'facebook')
`

// Distinct social accounts that have inbox items, for the sync handler.
func (q *Queries) FindInboxAccountsByWorkspace(ctx context.Context, workspaceID string) ([]SocialAccount, error) {
	rows, err := q.db.Query(ctx, findInboxAccountsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SocialAccount{}
	for rows.Next() {
		var i SocialAccount
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.Platform,
			&i.AccessToken,
			&i.RefreshToken,
			&i.TokenExpiresAt,
			&i.ExternalAccountID,
			&i.AccountName,
			&i.AccountAvatarUrl,
			&i.ConnectedAt,
			&i.DisconnectedAt,
			&i.Metadata,
			&i.Scope,
			&i.Status,
			&i.ConnectionType,
			&i.ConnectSessionID,
			&i.ExternalUserID,
			&i.ExternalUserEmail,
			&i.LastRefreshedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findLinkedPostIDForInboxParent = `-- name: FindLinkedPostIDForInboxParent :one
SELECT spr.post_id
FROM social_post_results spr
WHERE spr.social_account_id = $1
  AND spr.external_id = $2
LIMIT 1
`

type FindLinkedPostIDForInboxParentParams struct {
	SocialAccountID string      `json:"social_account_id"`
	ExternalID      pgtype.Text `json:"external_id"`
}

func (q *Queries) FindLinkedPostIDForInboxParent(ctx context.Context, arg FindLinkedPostIDForInboxParentParams) (string, error) {
	row := q.db.QueryRow(ctx, findLinkedPostIDForInboxParent, arg.SocialAccountID, arg.ExternalID)
	var post_id string
	err := row.Scan(&post_id)
	return post_id, err
}

const findSocialAccountByPlatformAndExternalID = `-- name: FindSocialAccountByPlatformAndExternalID :one
SELECT sa.id, sa.external_account_id, p.workspace_id
FROM social_accounts sa
JOIN profiles p ON p.id = sa.profile_id
WHERE sa.platform = $1
  AND sa.external_account_id = $2
  AND sa.disconnected_at IS NULL
  AND sa.status = 'active'
LIMIT 1
`

type FindSocialAccountByPlatformAndExternalIDParams struct {
	Platform          string `json:"platform"`
	ExternalAccountID string `json:"external_account_id"`
}

type FindSocialAccountByPlatformAndExternalIDRow struct {
	ID                string `json:"id"`
	ExternalAccountID string `json:"external_account_id"`
	WorkspaceID       string `json:"workspace_id"`
}

// Webhook routing: find an active social account by platform + external_account_id,
// joining to profiles for workspace_id. Returns the first match.
func (q *Queries) FindSocialAccountByPlatformAndExternalID(ctx context.Context, arg FindSocialAccountByPlatformAndExternalIDParams) (FindSocialAccountByPlatformAndExternalIDRow, error) {
	row := q.db.QueryRow(ctx, findSocialAccountByPlatformAndExternalID, arg.Platform, arg.ExternalAccountID)
	var i FindSocialAccountByPlatformAndExternalIDRow
	err := row.Scan(&i.ID, &i.ExternalAccountID, &i.WorkspaceID)
	return i, err
}

const getInboxItem = `-- name: GetInboxItem :one
SELECT id, social_account_id, workspace_id, source, external_id, parent_external_id, author_name, author_id, author_avatar_url, body, is_read, is_own, received_at, created_at, metadata, thread_key, thread_status, assigned_to, linked_post_id FROM inbox_items
WHERE id = $1 AND workspace_id = $2
`

type GetInboxItemParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetInboxItem(ctx context.Context, arg GetInboxItemParams) (InboxItem, error) {
	row := q.db.QueryRow(ctx, getInboxItem, arg.ID, arg.WorkspaceID)
	var i InboxItem
	err := row.Scan(
		&i.ID,
		&i.SocialAccountID,
		&i.WorkspaceID,
		&i.Source,
		&i.ExternalID,
		&i.ParentExternalID,
		&i.AuthorName,
		&i.AuthorID,
		&i.AuthorAvatarUrl,
		&i.Body,
		&i.IsRead,
		&i.IsOwn,
		&i.ReceivedAt,
		&i.CreatedAt,
		&i.Metadata,
		&i.ThreadKey,
		&i.ThreadStatus,
		&i.AssignedTo,
		&i.LinkedPostID,
	)
	return i, err
}

const getInboxItemByExternalID = `-- name: GetInboxItemByExternalID :one
SELECT id, social_account_id, workspace_id, source, external_id, parent_external_id, author_name, author_id, author_avatar_url, body, is_read, is_own, received_at, created_at, metadata, thread_key, thread_status, assigned_to, linked_post_id FROM inbox_items
WHERE social_account_id = $1
  AND external_id = $2
LIMIT 1
`

type GetInboxItemByExternalIDParams struct {
	SocialAccountID string `json:"social_account_id"`
	ExternalID      string `json:"external_id"`
}

func (q *Queries) GetInboxItemByExternalID(ctx context.Context, arg GetInboxItemByExternalIDParams) (InboxItem, error) {
	row := q.db.QueryRow(ctx, getInboxItemByExternalID, arg.SocialAccountID, arg.ExternalID)
	var i InboxItem
	err := row.Scan(
		&i.ID,
		&i.SocialAccountID,
		&i.WorkspaceID,
		&i.Source,
		&i.ExternalID,
		&i.ParentExternalID,
		&i.AuthorName,
		&i.AuthorID,
		&i.AuthorAvatarUrl,
		&i.Body,
		&i.IsRead,
		&i.IsOwn,
		&i.ReceivedAt,
		&i.CreatedAt,
		&i.Metadata,
		&i.ThreadKey,
		&i.ThreadStatus,
		&i.AssignedTo,
		&i.LinkedPostID,
	)
	return i, err
}

const getInboxMediaCache = `-- name: GetInboxMediaCache :one
SELECT media_url, caption, timestamp, media_type, permalink, fetched_at
FROM inbox_media_cache
WHERE social_account_id = $1
  AND external_id = $2
`

type GetInboxMediaCacheParams struct {
	SocialAccountID string `json:"social_account_id"`
	ExternalID      string `json:"external_id"`
}

type GetInboxMediaCacheRow struct {
	MediaUrl  string             `json:"media_url"`
	Caption   string             `json:"caption"`
	Timestamp string             `json:"timestamp"`
	MediaType string             `json:"media_type"`
	Permalink string             `json:"permalink"`
	FetchedAt pgtype.Timestamptz `json:"fetched_at"`
}

func (q *Queries) GetInboxMediaCache(ctx context.Context, arg GetInboxMediaCacheParams) (GetInboxMediaCacheRow, error) {
	row := q.db.QueryRow(ctx, getInboxMediaCache, arg.SocialAccountID, arg.ExternalID)
	var i GetInboxMediaCacheRow
	err := row.Scan(
		&i.MediaUrl,
		&i.Caption,
		&i.Timestamp,
		&i.MediaType,
		&i.Permalink,
		&i.FetchedAt,
	)
	return i, err
}

const listAllInboxAccounts = `-- name: ListAllInboxAccounts :many
SELECT sa.id, sa.platform, sa.access_token, sa.external_account_id,
       sa.account_name, p.workspace_id
FROM social_accounts sa
JOIN profiles p ON p.id = sa.profile_id
WHERE sa.disconnected_at IS NULL
  AND sa.status = 'active'
  AND sa.platform IN ('instagram', 'threads', 'facebook')
ORDER BY sa.connected_at DESC
`

type ListAllInboxAccountsRow struct {
	ID                string      `json:"id"`
	Platform          string      `json:"platform"`
	AccessToken       string      `json:"access_token"`
	ExternalAccountID string      `json:"external_account_id"`
	AccountName       pgtype.Text `json:"account_name"`
	WorkspaceID       string      `json:"workspace_id"`
}

// All active IG / Threads / Facebook accounts across all workspaces,
// for the background inbox sync worker. Returns account fields plus
// workspace_id.
func (q *Queries) ListAllInboxAccounts(ctx context.Context) ([]ListAllInboxAccountsRow, error) {
	rows, err := q.db.Query(ctx, listAllInboxAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllInboxAccountsRow{}
	for rows.Next() {
		var i ListAllInboxAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.AccessToken,
			&i.ExternalAccountID,
			&i.AccountName,
			&i.WorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInboxItemsByParent = `-- name: ListInboxItemsByParent :many
SELECT id, social_account_id, workspace_id, source, external_id, parent_external_id, author_name, author_id, author_avatar_url, body, is_read, is_own, received_at, created_at, metadata, thread_key, thread_status, assigned_to, linked_post_id FROM inbox_items
WHERE social_account_id = $1
  AND parent_external_id = $2
ORDER BY received_at ASC
`

type ListInboxItemsByParentParams struct {
	SocialAccountID  string      `json:"social_account_id"`
	ParentExternalID pgtype.Text `json:"parent_external_id"`
}

func (q *Queries) ListInboxItemsByParent(ctx context.Context, arg ListInboxItemsByParentParams) ([]InboxItem, error) {
	rows, err := q.db.Query(ctx, listInboxItemsByParent, arg.SocialAccountID, arg.ParentExternalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboxItem{}
	for rows.Next() {
		var i InboxItem
		if err := rows.Scan(
			&i.ID,
			&i.SocialAccountID,
			&i.WorkspaceID,
			&i.Source,
			&i.ExternalID,
			&i.ParentExternalID,
			&i.AuthorName,
			&i.AuthorID,
			&i.AuthorAvatarUrl,
			&i.Body,
			&i.IsRead,
			&i.IsOwn,
			&i.ReceivedAt,
			&i.CreatedAt,
			&i.Metadata,
			&i.ThreadKey,
			&i.ThreadStatus,
			&i.AssignedTo,
			&i.LinkedPostID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInboxItemsByWorkspace = `-- name: ListInboxItemsByWorkspace :many
SELECT i.id, i.social_account_id, i.workspace_id, i.source, i.external_id, i.parent_external_id, i.author_name, i.author_id, i.author_avatar_url, i.body, i.is_read, i.is_own, i.received_at, i.created_at, i.metadata, i.thread_key, i.thread_status, i.assigned_to, i.linked_post_id FROM inbox_items i
JOIN social_accounts sa ON sa.id = i.social_account_id
WHERE i.workspace_id = $1
  AND sa.status = 'active'
  AND sa.disconnected_at IS NULL
  AND ($3::TEXT IS NULL OR i.source = $3::TEXT)
  AND ($4::BOOLEAN IS NULL OR i.is_read = $4::BOOLEAN)
ORDER BY i.received_at DESC
LIMIT $2
`

type ListInboxItemsByWorkspaceParams struct {
	WorkspaceID string      `json:"workspace_id"`
	Limit       int32       `json:"limit"`
	Source      pgtype.Text `json:"source"`
	IsRead      pgtype.Bool `json:"is_read"`
}

func (q *Queries) ListInboxItemsByWorkspace(ctx context.Context, arg ListInboxItemsByWorkspaceParams) ([]InboxItem, error) {
	rows, err := q.db.Query(ctx, listInboxItemsByWorkspace,
		arg.WorkspaceID,
		arg.Limit,
		arg.Source,
		arg.IsRead,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboxItem{}
	for rows.Next() {
		var i InboxItem
		if err := rows.Scan(
			&i.ID,
			&i.SocialAccountID,
			&i.WorkspaceID,
			&i.Source,
			&i.ExternalID,
			&i.ParentExternalID,
			&i.AuthorName,
			&i.AuthorID,
			&i.AuthorAvatarUrl,
			&i.Body,
			&i.IsRead,
			&i.IsOwn,
			&i.ReceivedAt,
			&i.CreatedAt,
			&i.Metadata,
			&i.ThreadKey,
			&i.ThreadStatus,
			&i.AssignedTo,
			&i.LinkedPostID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllInboxItemsRead = `-- name: MarkAllInboxItemsRead :execrows
UPDATE inbox_items
SET is_read = true
WHERE workspace_id = $1 AND is_read = false
`

func (q *Queries) MarkAllInboxItemsRead(ctx context.Context, workspaceID string) (int64, error) {
	result, err := q.db.Exec(ctx, markAllInboxItemsRead, workspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markInboxItemRead = `-- name: MarkInboxItemRead :exec
UPDATE inbox_items
SET is_read = true
WHERE id = $1 AND workspace_id = $2
`

type MarkInboxItemReadParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) MarkInboxItemRead(ctx context.Context, arg MarkInboxItemReadParams) error {
	_, err := q.db.Exec(ctx, markInboxItemRead, arg.ID, arg.WorkspaceID)
	return err
}

const reconcileDMThreadKeys = `-- name: ReconcileDMThreadKeys :execrows
UPDATE inbox_items
SET thread_key = $3,
    parent_external_id = $4
WHERE social_account_id = $1
  AND source = 'ig_dm'
  AND thread_key = $2
  AND thread_key != $3
`

type ReconcileDMThreadKeysParams struct {
	SocialAccountID  string      `json:"social_account_id"`
	ThreadKey        string      `json:"thread_key"`
	ThreadKey_2      string      `json:"thread_key_2"`
	ParentExternalID pgtype.Text `json:"parent_external_id"`
}

// When sync discovers the canonical conversation ID for a DM thread,
// update any existing items (e.g. from webhooks) that used a fallback
// thread_key (sender ID) so all messages share the same thread_key.
func (q *Queries) ReconcileDMThreadKeys(ctx context.Context, arg ReconcileDMThreadKeysParams) (int64, error) {
	result, err := q.db.Exec(ctx, reconcileDMThreadKeys,
		arg.SocialAccountID,
		arg.ThreadKey,
		arg.ThreadKey_2,
		arg.ParentExternalID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateInboxItemAuthorMetadata = `-- name: UpdateInboxItemAuthorMetadata :execrows
UPDATE inbox_items
SET author_name = NULLIF($1::TEXT, ''),
    author_id = NULLIF($2::TEXT, ''),
    author_avatar_url = NULLIF($3::TEXT, '')
WHERE id = $4
  AND workspace_id = $5
`

type UpdateInboxItemAuthorMetadataParams struct {
	AuthorName      string `json:"author_name"`
	AuthorID        string `json:"author_id"`
	AuthorAvatarUrl string `json:"author_avatar_url"`
	ID              string `json:"id"`
	WorkspaceID     string `json:"workspace_id"`
}

func (q *Queries) UpdateInboxItemAuthorMetadata(ctx context.Context, arg UpdateInboxItemAuthorMetadataParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateInboxItemAuthorMetadata,
		arg.AuthorName,
		arg.AuthorID,
		arg.AuthorAvatarUrl,
		arg.ID,
		arg.WorkspaceID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateInboxThreadState = `-- name: UpdateInboxThreadState :execrows
UPDATE inbox_items
SET thread_status = $5,
    assigned_to = NULLIF($6, '')
WHERE workspace_id = $1
  AND social_account_id = $2
  AND source = $3
  AND thread_key = $4
`

type UpdateInboxThreadStateParams struct {
	WorkspaceID     string      `json:"workspace_id"`
	SocialAccountID string      `json:"social_account_id"`
	Source          string      `json:"source"`
	ThreadKey       string      `json:"thread_key"`
	ThreadStatus    string      `json:"thread_status"`
	Column6         interface{} `json:"column_6"`
}

func (q *Queries) UpdateInboxThreadState(ctx context.Context, arg UpdateInboxThreadStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateInboxThreadState,
		arg.WorkspaceID,
		arg.SocialAccountID,
		arg.Source,
		arg.ThreadKey,
		arg.ThreadStatus,
		arg.Column6,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertInboxItem = `-- name: UpsertInboxItem :one
INSERT INTO inbox_items (
  social_account_id, workspace_id, source, external_id,
  parent_external_id, author_name, author_id, author_avatar_url,
  body, is_own, received_at, metadata, thread_key, thread_status,
  assigned_to, linked_post_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
ON CONFLICT (social_account_id, external_id) DO NOTHING
RETURNING id, social_account_id, workspace_id, source, external_id, parent_external_id, author_name, author_id, author_avatar_url, body, is_read, is_own, received_at, created_at, metadata, thread_key, thread_status, assigned_to, linked_post_id
`

type UpsertInboxItemParams struct {
	SocialAccountID  string             `json:"social_account_id"`
	WorkspaceID      string             `json:"workspace_id"`
	Source           string             `json:"source"`
	ExternalID       string             `json:"external_id"`
	ParentExternalID pgtype.Text        `json:"parent_external_id"`
	AuthorName       pgtype.Text        `json:"author_name"`
	AuthorID         pgtype.Text        `json:"author_id"`
	AuthorAvatarUrl  pgtype.Text        `json:"author_avatar_url"`
	Body             pgtype.Text        `json:"body"`
	IsOwn            bool               `json:"is_own"`
	ReceivedAt       pgtype.Timestamptz `json:"received_at"`
	Metadata         []byte             `json:"metadata"`
	ThreadKey        string             `json:"thread_key"`
	ThreadStatus     string             `json:"thread_status"`
	AssignedTo       pgtype.Text        `json:"assigned_to"`
	LinkedPostID     pgtype.Text        `json:"linked_post_id"`
}

func (q *Queries) UpsertInboxItem(ctx context.Context, arg UpsertInboxItemParams) (InboxItem, error) {
	row := q.db.QueryRow(ctx, upsertInboxItem,
		arg.SocialAccountID,
		arg.WorkspaceID,
		arg.Source,
		arg.ExternalID,
		arg.ParentExternalID,
		arg.AuthorName,
		arg.AuthorID,
		arg.AuthorAvatarUrl,
		arg.Body,
		arg.IsOwn,
		arg.ReceivedAt,
		arg.Metadata,
		arg.ThreadKey,
		arg.ThreadStatus,
		arg.AssignedTo,
		arg.LinkedPostID,
	)
	var i InboxItem
	err := row.Scan(
		&i.ID,
		&i.SocialAccountID,
		&i.WorkspaceID,
		&i.Source,
		&i.ExternalID,
		&i.ParentExternalID,
		&i.AuthorName,
		&i.AuthorID,
		&i.AuthorAvatarUrl,
		&i.Body,
		&i.IsRead,
		&i.IsOwn,
		&i.ReceivedAt,
		&i.CreatedAt,
		&i.Metadata,
		&i.ThreadKey,
		&i.ThreadStatus,
		&i.AssignedTo,
		&i.LinkedPostID,
	)
	return i, err
}

const upsertInboxMediaCache = `-- name: UpsertInboxMediaCache :exec
INSERT INTO inbox_media_cache (
  social_account_id, external_id, media_url, caption, timestamp, media_type, permalink, fetched_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())
ON CONFLICT (social_account_id, external_id) DO UPDATE SET
  media_url = EXCLUDED.media_url,
  caption = EXCLUDED.caption,
  timestamp = EXCLUDED.timestamp,
  media_type = EXCLUDED.media_type,
  permalink = EXCLUDED.permalink,
  fetched_at = NOW()
`

type UpsertInboxMediaCacheParams struct {
	SocialAccountID string `json:"social_account_id"`
	ExternalID      string `json:"external_id"`
	MediaUrl        string `json:"media_url"`
	Caption         string `json:"caption"`
	Timestamp       string `json:"timestamp"`
	MediaType       string `json:"media_type"`
	Permalink       string `json:"permalink"`
}

func (q *Queries) UpsertInboxMediaCache(ctx context.Context, arg UpsertInboxMediaCacheParams) error {
	_, err := q.db.Exec(ctx, upsertInboxMediaCache,
		arg.SocialAccountID,
		arg.ExternalID,
		arg.MediaUrl,
		arg.Caption,
		arg.Timestamp,
		arg.MediaType,
		arg.Permalink,
	)
	return err
}
