// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inbox.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadByWorkspace = `-- name: CountUnreadByWorkspace :one
SELECT COUNT(*)::INTEGER AS count
FROM inbox_items
WHERE workspace_id = $1 AND is_read = false
`

func (q *Queries) CountUnreadByWorkspace(ctx context.Context, workspaceID string) (int32, error) {
	row := q.db.QueryRow(ctx, countUnreadByWorkspace, workspaceID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const findInboxAccountsByWorkspace = `-- name: FindInboxAccountsByWorkspace :many
SELECT DISTINCT sa.id, sa.profile_id, sa.platform, sa.access_token, sa.refresh_token, sa.token_expires_at, sa.external_account_id, sa.account_name, sa.account_avatar_url, sa.connected_at, sa.disconnected_at, sa.metadata, sa.scope, sa.status, sa.connection_type, sa.connect_session_id, sa.external_user_id, sa.external_user_email, sa.last_refreshed_at
FROM social_accounts sa
JOIN profiles p ON p.id = sa.profile_id
WHERE p.workspace_id = $1
  AND sa.disconnected_at IS NULL
  AND sa.platform IN ('instagram', 'threads')
`

// Distinct social accounts that have inbox items, for the sync handler.
func (q *Queries) FindInboxAccountsByWorkspace(ctx context.Context, workspaceID string) ([]SocialAccount, error) {
	rows, err := q.db.Query(ctx, findInboxAccountsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SocialAccount{}
	for rows.Next() {
		var i SocialAccount
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.Platform,
			&i.AccessToken,
			&i.RefreshToken,
			&i.TokenExpiresAt,
			&i.ExternalAccountID,
			&i.AccountName,
			&i.AccountAvatarUrl,
			&i.ConnectedAt,
			&i.DisconnectedAt,
			&i.Metadata,
			&i.Scope,
			&i.Status,
			&i.ConnectionType,
			&i.ConnectSessionID,
			&i.ExternalUserID,
			&i.ExternalUserEmail,
			&i.LastRefreshedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSocialAccountByPlatformAndExternalID = `-- name: FindSocialAccountByPlatformAndExternalID :one
SELECT sa.id, sa.external_account_id, p.workspace_id
FROM social_accounts sa
JOIN profiles p ON p.id = sa.profile_id
WHERE sa.platform = $1
  AND sa.external_account_id = $2
  AND sa.disconnected_at IS NULL
  AND sa.status = 'active'
LIMIT 1
`

type FindSocialAccountByPlatformAndExternalIDParams struct {
	Platform          string `json:"platform"`
	ExternalAccountID string `json:"external_account_id"`
}

type FindSocialAccountByPlatformAndExternalIDRow struct {
	ID                string `json:"id"`
	ExternalAccountID string `json:"external_account_id"`
	WorkspaceID       string `json:"workspace_id"`
}

// Webhook routing: find an active social account by platform + external_account_id,
// joining to profiles for workspace_id. Returns the first match.
func (q *Queries) FindSocialAccountByPlatformAndExternalID(ctx context.Context, arg FindSocialAccountByPlatformAndExternalIDParams) (FindSocialAccountByPlatformAndExternalIDRow, error) {
	row := q.db.QueryRow(ctx, findSocialAccountByPlatformAndExternalID, arg.Platform, arg.ExternalAccountID)
	var i FindSocialAccountByPlatformAndExternalIDRow
	err := row.Scan(&i.ID, &i.ExternalAccountID, &i.WorkspaceID)
	return i, err
}

const getInboxItem = `-- name: GetInboxItem :one
SELECT id, social_account_id, workspace_id, source, external_id, parent_external_id, author_name, author_id, author_avatar_url, body, is_read, is_own, received_at, created_at, metadata FROM inbox_items
WHERE id = $1 AND workspace_id = $2
`

type GetInboxItemParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetInboxItem(ctx context.Context, arg GetInboxItemParams) (InboxItem, error) {
	row := q.db.QueryRow(ctx, getInboxItem, arg.ID, arg.WorkspaceID)
	var i InboxItem
	err := row.Scan(
		&i.ID,
		&i.SocialAccountID,
		&i.WorkspaceID,
		&i.Source,
		&i.ExternalID,
		&i.ParentExternalID,
		&i.AuthorName,
		&i.AuthorID,
		&i.AuthorAvatarUrl,
		&i.Body,
		&i.IsRead,
		&i.IsOwn,
		&i.ReceivedAt,
		&i.CreatedAt,
		&i.Metadata,
	)
	return i, err
}

const listAllInboxAccounts = `-- name: ListAllInboxAccounts :many
SELECT sa.id, sa.platform, sa.access_token, sa.external_account_id,
       sa.account_name, p.workspace_id
FROM social_accounts sa
JOIN profiles p ON p.id = sa.profile_id
WHERE sa.disconnected_at IS NULL
  AND sa.status = 'active'
  AND sa.platform IN ('instagram', 'threads')
ORDER BY sa.connected_at DESC
`

type ListAllInboxAccountsRow struct {
	ID                string      `json:"id"`
	Platform          string      `json:"platform"`
	AccessToken       string      `json:"access_token"`
	ExternalAccountID string      `json:"external_account_id"`
	AccountName       pgtype.Text `json:"account_name"`
	WorkspaceID       string      `json:"workspace_id"`
}

// All active IG/Threads accounts across all workspaces, for the
// background inbox sync worker. Returns account fields plus workspace_id.
func (q *Queries) ListAllInboxAccounts(ctx context.Context) ([]ListAllInboxAccountsRow, error) {
	rows, err := q.db.Query(ctx, listAllInboxAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllInboxAccountsRow{}
	for rows.Next() {
		var i ListAllInboxAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.AccessToken,
			&i.ExternalAccountID,
			&i.AccountName,
			&i.WorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInboxItemsByParent = `-- name: ListInboxItemsByParent :many
SELECT id, social_account_id, workspace_id, source, external_id, parent_external_id, author_name, author_id, author_avatar_url, body, is_read, is_own, received_at, created_at, metadata FROM inbox_items
WHERE social_account_id = $1
  AND parent_external_id = $2
ORDER BY received_at ASC
`

type ListInboxItemsByParentParams struct {
	SocialAccountID  string      `json:"social_account_id"`
	ParentExternalID pgtype.Text `json:"parent_external_id"`
}

func (q *Queries) ListInboxItemsByParent(ctx context.Context, arg ListInboxItemsByParentParams) ([]InboxItem, error) {
	rows, err := q.db.Query(ctx, listInboxItemsByParent, arg.SocialAccountID, arg.ParentExternalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboxItem{}
	for rows.Next() {
		var i InboxItem
		if err := rows.Scan(
			&i.ID,
			&i.SocialAccountID,
			&i.WorkspaceID,
			&i.Source,
			&i.ExternalID,
			&i.ParentExternalID,
			&i.AuthorName,
			&i.AuthorID,
			&i.AuthorAvatarUrl,
			&i.Body,
			&i.IsRead,
			&i.IsOwn,
			&i.ReceivedAt,
			&i.CreatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInboxItemsByWorkspace = `-- name: ListInboxItemsByWorkspace :many
SELECT id, social_account_id, workspace_id, source, external_id, parent_external_id, author_name, author_id, author_avatar_url, body, is_read, is_own, received_at, created_at, metadata FROM inbox_items
WHERE workspace_id = $1
  AND ($3::TEXT IS NULL OR source = $3::TEXT)
  AND ($4::BOOLEAN IS NULL OR is_read = $4::BOOLEAN)
ORDER BY received_at DESC
LIMIT $2
`

type ListInboxItemsByWorkspaceParams struct {
	WorkspaceID string      `json:"workspace_id"`
	Limit       int32       `json:"limit"`
	Source      pgtype.Text `json:"source"`
	IsRead      pgtype.Bool `json:"is_read"`
}

func (q *Queries) ListInboxItemsByWorkspace(ctx context.Context, arg ListInboxItemsByWorkspaceParams) ([]InboxItem, error) {
	rows, err := q.db.Query(ctx, listInboxItemsByWorkspace,
		arg.WorkspaceID,
		arg.Limit,
		arg.Source,
		arg.IsRead,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboxItem{}
	for rows.Next() {
		var i InboxItem
		if err := rows.Scan(
			&i.ID,
			&i.SocialAccountID,
			&i.WorkspaceID,
			&i.Source,
			&i.ExternalID,
			&i.ParentExternalID,
			&i.AuthorName,
			&i.AuthorID,
			&i.AuthorAvatarUrl,
			&i.Body,
			&i.IsRead,
			&i.IsOwn,
			&i.ReceivedAt,
			&i.CreatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllInboxItemsRead = `-- name: MarkAllInboxItemsRead :execrows
UPDATE inbox_items
SET is_read = true
WHERE workspace_id = $1 AND is_read = false
`

func (q *Queries) MarkAllInboxItemsRead(ctx context.Context, workspaceID string) (int64, error) {
	result, err := q.db.Exec(ctx, markAllInboxItemsRead, workspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markInboxItemRead = `-- name: MarkInboxItemRead :exec
UPDATE inbox_items
SET is_read = true
WHERE id = $1 AND workspace_id = $2
`

type MarkInboxItemReadParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) MarkInboxItemRead(ctx context.Context, arg MarkInboxItemReadParams) error {
	_, err := q.db.Exec(ctx, markInboxItemRead, arg.ID, arg.WorkspaceID)
	return err
}

const upsertInboxItem = `-- name: UpsertInboxItem :one
INSERT INTO inbox_items (
  social_account_id, workspace_id, source, external_id,
  parent_external_id, author_name, author_id, author_avatar_url,
  body, is_own, received_at, metadata
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (social_account_id, external_id) DO NOTHING
RETURNING id, social_account_id, workspace_id, source, external_id, parent_external_id, author_name, author_id, author_avatar_url, body, is_read, is_own, received_at, created_at, metadata
`

type UpsertInboxItemParams struct {
	SocialAccountID  string             `json:"social_account_id"`
	WorkspaceID      string             `json:"workspace_id"`
	Source           string             `json:"source"`
	ExternalID       string             `json:"external_id"`
	ParentExternalID pgtype.Text        `json:"parent_external_id"`
	AuthorName       pgtype.Text        `json:"author_name"`
	AuthorID         pgtype.Text        `json:"author_id"`
	AuthorAvatarUrl  pgtype.Text        `json:"author_avatar_url"`
	Body             pgtype.Text        `json:"body"`
	IsOwn            bool               `json:"is_own"`
	ReceivedAt       pgtype.Timestamptz `json:"received_at"`
	Metadata         []byte             `json:"metadata"`
}

func (q *Queries) UpsertInboxItem(ctx context.Context, arg UpsertInboxItemParams) (InboxItem, error) {
	row := q.db.QueryRow(ctx, upsertInboxItem,
		arg.SocialAccountID,
		arg.WorkspaceID,
		arg.Source,
		arg.ExternalID,
		arg.ParentExternalID,
		arg.AuthorName,
		arg.AuthorID,
		arg.AuthorAvatarUrl,
		arg.Body,
		arg.IsOwn,
		arg.ReceivedAt,
		arg.Metadata,
	)
	var i InboxItem
	err := row.Scan(
		&i.ID,
		&i.SocialAccountID,
		&i.WorkspaceID,
		&i.Source,
		&i.ExternalID,
		&i.ParentExternalID,
		&i.AuthorName,
		&i.AuthorID,
		&i.AuthorAvatarUrl,
		&i.Body,
		&i.IsRead,
		&i.IsOwn,
		&i.ReceivedAt,
		&i.CreatedAt,
		&i.Metadata,
	)
	return i, err
}
