// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: integration_logs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredIntegrationLogsForWorkspace = `-- name: DeleteExpiredIntegrationLogsForWorkspace :exec
DELETE FROM integration_logs
WHERE workspace_id = $1
  AND ts < $2
`

type DeleteExpiredIntegrationLogsForWorkspaceParams struct {
	WorkspaceID string             `json:"workspace_id"`
	Ts          pgtype.Timestamptz `json:"ts"`
}

func (q *Queries) DeleteExpiredIntegrationLogsForWorkspace(ctx context.Context, arg DeleteExpiredIntegrationLogsForWorkspaceParams) error {
	_, err := q.db.Exec(ctx, deleteExpiredIntegrationLogsForWorkspace, arg.WorkspaceID, arg.Ts)
	return err
}

const getIntegrationLog = `-- name: GetIntegrationLog :one
SELECT id, workspace_id, ts, level, status, category, action, source, message,
       request_id, trace_id,
       actor_user_id, actor_api_key_id,
       profile_id, social_account_id, post_id, platform_post_id, platform,
       endpoint, method, http_status_code, remote_status_code, duration_ms,
       error_code, metadata, request_payload, response_payload, created_at
FROM integration_logs
WHERE id = $1 AND workspace_id = $2
`

type GetIntegrationLogParams struct {
	ID          int64  `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetIntegrationLog(ctx context.Context, arg GetIntegrationLogParams) (IntegrationLog, error) {
	row := q.db.QueryRow(ctx, getIntegrationLog, arg.ID, arg.WorkspaceID)
	var i IntegrationLog
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Ts,
		&i.Level,
		&i.Status,
		&i.Category,
		&i.Action,
		&i.Source,
		&i.Message,
		&i.RequestID,
		&i.TraceID,
		&i.ActorUserID,
		&i.ActorApiKeyID,
		&i.ProfileID,
		&i.SocialAccountID,
		&i.PostID,
		&i.PlatformPostID,
		&i.Platform,
		&i.Endpoint,
		&i.Method,
		&i.HttpStatusCode,
		&i.RemoteStatusCode,
		&i.DurationMs,
		&i.ErrorCode,
		&i.Metadata,
		&i.RequestPayload,
		&i.ResponsePayload,
		&i.CreatedAt,
	)
	return i, err
}

const insertIntegrationLog = `-- name: InsertIntegrationLog :one
INSERT INTO integration_logs (
    workspace_id, ts, level, status, category, action, source, message,
    request_id, trace_id,
    actor_user_id, actor_api_key_id,
    profile_id, social_account_id, post_id, platform_post_id, platform,
    endpoint, method, http_status_code, remote_status_code, duration_ms,
    error_code, metadata, request_payload, response_payload
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10,
    $11, $12,
    $13, $14, $15, $16, $17,
    $18, $19, $20, $21, $22,
    $23, $24, $25, $26
) RETURNING id, workspace_id, ts, level, status, category, action, source, message,
            request_id, trace_id,
            actor_user_id, actor_api_key_id,
            profile_id, social_account_id, post_id, platform_post_id, platform,
            endpoint, method, http_status_code, remote_status_code, duration_ms,
            error_code, metadata, request_payload, response_payload, created_at
`

type InsertIntegrationLogParams struct {
	WorkspaceID      string             `json:"workspace_id"`
	Ts               pgtype.Timestamptz `json:"ts"`
	Level            string             `json:"level"`
	Status           string             `json:"status"`
	Category         string             `json:"category"`
	Action           string             `json:"action"`
	Source           string             `json:"source"`
	Message          string             `json:"message"`
	RequestID        pgtype.Text        `json:"request_id"`
	TraceID          pgtype.Text        `json:"trace_id"`
	ActorUserID      pgtype.Text        `json:"actor_user_id"`
	ActorApiKeyID    pgtype.Text        `json:"actor_api_key_id"`
	ProfileID        pgtype.Text        `json:"profile_id"`
	SocialAccountID  pgtype.Text        `json:"social_account_id"`
	PostID           pgtype.Text        `json:"post_id"`
	PlatformPostID   pgtype.Text        `json:"platform_post_id"`
	Platform         pgtype.Text        `json:"platform"`
	Endpoint         pgtype.Text        `json:"endpoint"`
	Method           pgtype.Text        `json:"method"`
	HttpStatusCode   pgtype.Int4        `json:"http_status_code"`
	RemoteStatusCode pgtype.Int4        `json:"remote_status_code"`
	DurationMs       pgtype.Int4        `json:"duration_ms"`
	ErrorCode        pgtype.Text        `json:"error_code"`
	Metadata         []byte             `json:"metadata"`
	RequestPayload   []byte             `json:"request_payload"`
	ResponsePayload  []byte             `json:"response_payload"`
}

func (q *Queries) InsertIntegrationLog(ctx context.Context, arg InsertIntegrationLogParams) (IntegrationLog, error) {
	row := q.db.QueryRow(ctx, insertIntegrationLog,
		arg.WorkspaceID,
		arg.Ts,
		arg.Level,
		arg.Status,
		arg.Category,
		arg.Action,
		arg.Source,
		arg.Message,
		arg.RequestID,
		arg.TraceID,
		arg.ActorUserID,
		arg.ActorApiKeyID,
		arg.ProfileID,
		arg.SocialAccountID,
		arg.PostID,
		arg.PlatformPostID,
		arg.Platform,
		arg.Endpoint,
		arg.Method,
		arg.HttpStatusCode,
		arg.RemoteStatusCode,
		arg.DurationMs,
		arg.ErrorCode,
		arg.Metadata,
		arg.RequestPayload,
		arg.ResponsePayload,
	)
	var i IntegrationLog
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Ts,
		&i.Level,
		&i.Status,
		&i.Category,
		&i.Action,
		&i.Source,
		&i.Message,
		&i.RequestID,
		&i.TraceID,
		&i.ActorUserID,
		&i.ActorApiKeyID,
		&i.ProfileID,
		&i.SocialAccountID,
		&i.PostID,
		&i.PlatformPostID,
		&i.Platform,
		&i.Endpoint,
		&i.Method,
		&i.HttpStatusCode,
		&i.RemoteStatusCode,
		&i.DurationMs,
		&i.ErrorCode,
		&i.Metadata,
		&i.RequestPayload,
		&i.ResponsePayload,
		&i.CreatedAt,
	)
	return i, err
}

const listIntegrationLogs = `-- name: ListIntegrationLogs :many
SELECT id, workspace_id, ts, level, status, category, action, source, message,
       request_id, trace_id,
       actor_user_id, actor_api_key_id,
       profile_id, social_account_id, post_id, platform_post_id, platform,
       endpoint, method, http_status_code, remote_status_code, duration_ms,
       error_code, metadata, request_payload, response_payload, created_at
FROM integration_logs
WHERE workspace_id = $1
  AND ($2::TEXT = '' OR category = $2)
  AND ($3::TEXT = '' OR action = $3)
  AND ($4::TEXT = '' OR source = $4)
  AND ($5::TEXT = '' OR level = $5)
  AND ($6::TEXT = '' OR status = $6)
  AND ($7::TEXT = '' OR platform = $7)
  AND ($8::TEXT = '' OR profile_id = $8)
  AND ($9::TEXT = '' OR social_account_id = $9)
  AND ($10::TEXT = '' OR post_id = $10)
  AND ($11::TEXT = '' OR request_id = $11)
  AND ($12::TEXT = '' OR error_code = $12)
  AND (
    $13::TEXT = ''
    OR message ILIKE '%' || $13 || '%'
    OR action ILIKE '%' || $13 || '%'
    OR request_id ILIKE '%' || $13 || '%'
    OR post_id ILIKE '%' || $13 || '%'
    OR error_code ILIKE '%' || $13 || '%'
  )
  AND ts >= $14
  AND ts <= $15
ORDER BY ts DESC, id DESC
LIMIT $16
`

type ListIntegrationLogsParams struct {
	WorkspaceID string             `json:"workspace_id"`
	Column2     string             `json:"column_2"`
	Column3     string             `json:"column_3"`
	Column4     string             `json:"column_4"`
	Column5     string             `json:"column_5"`
	Column6     string             `json:"column_6"`
	Column7     string             `json:"column_7"`
	Column8     string             `json:"column_8"`
	Column9     string             `json:"column_9"`
	Column10    string             `json:"column_10"`
	Column11    string             `json:"column_11"`
	Column12    string             `json:"column_12"`
	Column13    string             `json:"column_13"`
	Ts          pgtype.Timestamptz `json:"ts"`
	Ts_2        pgtype.Timestamptz `json:"ts_2"`
	Limit       int32              `json:"limit"`
}

func (q *Queries) ListIntegrationLogs(ctx context.Context, arg ListIntegrationLogsParams) ([]IntegrationLog, error) {
	rows, err := q.db.Query(ctx, listIntegrationLogs,
		arg.WorkspaceID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
		arg.Column10,
		arg.Column11,
		arg.Column12,
		arg.Column13,
		arg.Ts,
		arg.Ts_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IntegrationLog{}
	for rows.Next() {
		var i IntegrationLog
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Ts,
			&i.Level,
			&i.Status,
			&i.Category,
			&i.Action,
			&i.Source,
			&i.Message,
			&i.RequestID,
			&i.TraceID,
			&i.ActorUserID,
			&i.ActorApiKeyID,
			&i.ProfileID,
			&i.SocialAccountID,
			&i.PostID,
			&i.PlatformPostID,
			&i.Platform,
			&i.Endpoint,
			&i.Method,
			&i.HttpStatusCode,
			&i.RemoteStatusCode,
			&i.DurationMs,
			&i.ErrorCode,
			&i.Metadata,
			&i.RequestPayload,
			&i.ResponsePayload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
