// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimAbandonedMedia = `-- name: ClaimAbandonedMedia :many
WITH eligible AS (
  SELECT candidate.id
  FROM media candidate
  WHERE candidate.status = 'pending'
    AND candidate.created_at < NOW() - INTERVAL '7 days'
  ORDER BY candidate.created_at ASC, candidate.id ASC
  LIMIT 100
  FOR UPDATE OF candidate SKIP LOCKED
)
UPDATE media AS m
SET status = 'deleted',
    cleanup_after_at = NOW()
FROM eligible
WHERE m.id = eligible.id
RETURNING m.id, m.storage_key, m.content_type, m.size_bytes, m.status, m.created_at, m.uploaded_at, m.workspace_id, m.content_hash, m.cleanup_after_at, m.width, m.height, m.duration_ms, m.usage_version
`

func (q *Queries) ClaimAbandonedMedia(ctx context.Context) ([]Media, error) {
	rows, err := q.db.Query(ctx, claimAbandonedMedia)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Media{}
	for rows.Next() {
		var i Media
		if err := rows.Scan(
			&i.ID,
			&i.StorageKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.Status,
			&i.CreatedAt,
			&i.UploadedAt,
			&i.WorkspaceID,
			&i.ContentHash,
			&i.CleanupAfterAt,
			&i.Width,
			&i.Height,
			&i.DurationMs,
			&i.UsageVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (workspace_id, storage_key, content_type, size_bytes, status, content_hash)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, storage_key, content_type, size_bytes, status, created_at, uploaded_at, workspace_id, content_hash, cleanup_after_at, width, height, duration_ms, usage_version
`

type CreateMediaParams struct {
	WorkspaceID string      `json:"workspace_id"`
	StorageKey  string      `json:"storage_key"`
	ContentType string      `json:"content_type"`
	SizeBytes   int64       `json:"size_bytes"`
	Status      string      `json:"status"`
	ContentHash pgtype.Text `json:"content_hash"`
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Media, error) {
	row := q.db.QueryRow(ctx, createMedia,
		arg.WorkspaceID,
		arg.StorageKey,
		arg.ContentType,
		arg.SizeBytes,
		arg.Status,
		arg.ContentHash,
	)
	var i Media
	err := row.Scan(
		&i.ID,
		&i.StorageKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.CreatedAt,
		&i.UploadedAt,
		&i.WorkspaceID,
		&i.ContentHash,
		&i.CleanupAfterAt,
		&i.Width,
		&i.Height,
		&i.DurationMs,
		&i.UsageVersion,
	)
	return i, err
}

const getActiveMediaByHash = `-- name: GetActiveMediaByHash :one
SELECT id, storage_key, content_type, size_bytes, status, created_at, uploaded_at, workspace_id, content_hash, cleanup_after_at, width, height, duration_ms, usage_version FROM media
WHERE workspace_id = $1 AND content_hash = $2 AND status != 'deleted'
ORDER BY
  CASE status
    WHEN 'uploaded' THEN 0
    WHEN 'attached' THEN 1
    WHEN 'pending' THEN 2
    ELSE 3
  END,
  created_at DESC
LIMIT 1
`

type GetActiveMediaByHashParams struct {
	WorkspaceID string      `json:"workspace_id"`
	ContentHash pgtype.Text `json:"content_hash"`
}

func (q *Queries) GetActiveMediaByHash(ctx context.Context, arg GetActiveMediaByHashParams) (Media, error) {
	row := q.db.QueryRow(ctx, getActiveMediaByHash, arg.WorkspaceID, arg.ContentHash)
	var i Media
	err := row.Scan(
		&i.ID,
		&i.StorageKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.CreatedAt,
		&i.UploadedAt,
		&i.WorkspaceID,
		&i.ContentHash,
		&i.CleanupAfterAt,
		&i.Width,
		&i.Height,
		&i.DurationMs,
		&i.UsageVersion,
	)
	return i, err
}

const getMedia = `-- name: GetMedia :one
SELECT id, storage_key, content_type, size_bytes, status, created_at, uploaded_at, workspace_id, content_hash, cleanup_after_at, width, height, duration_ms, usage_version FROM media WHERE id = $1
`

func (q *Queries) GetMedia(ctx context.Context, id string) (Media, error) {
	row := q.db.QueryRow(ctx, getMedia, id)
	var i Media
	err := row.Scan(
		&i.ID,
		&i.StorageKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.CreatedAt,
		&i.UploadedAt,
		&i.WorkspaceID,
		&i.ContentHash,
		&i.CleanupAfterAt,
		&i.Width,
		&i.Height,
		&i.DurationMs,
		&i.UsageVersion,
	)
	return i, err
}

const getMediaByHash = `-- name: GetMediaByHash :one
SELECT id, storage_key, content_type, size_bytes, status, created_at, uploaded_at, workspace_id, content_hash, cleanup_after_at, width, height, duration_ms, usage_version FROM media
WHERE workspace_id = $1 AND content_hash = $2 AND status = 'uploaded'
LIMIT 1
`

type GetMediaByHashParams struct {
	WorkspaceID string      `json:"workspace_id"`
	ContentHash pgtype.Text `json:"content_hash"`
}

func (q *Queries) GetMediaByHash(ctx context.Context, arg GetMediaByHashParams) (Media, error) {
	row := q.db.QueryRow(ctx, getMediaByHash, arg.WorkspaceID, arg.ContentHash)
	var i Media
	err := row.Scan(
		&i.ID,
		&i.StorageKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.CreatedAt,
		&i.UploadedAt,
		&i.WorkspaceID,
		&i.ContentHash,
		&i.CleanupAfterAt,
		&i.Width,
		&i.Height,
		&i.DurationMs,
		&i.UsageVersion,
	)
	return i, err
}

const getMediaByIDAndWorkspace = `-- name: GetMediaByIDAndWorkspace :one
SELECT id, storage_key, content_type, size_bytes, status, created_at, uploaded_at, workspace_id, content_hash, cleanup_after_at, width, height, duration_ms, usage_version FROM media WHERE id = $1 AND workspace_id = $2
`

type GetMediaByIDAndWorkspaceParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetMediaByIDAndWorkspace(ctx context.Context, arg GetMediaByIDAndWorkspaceParams) (Media, error) {
	row := q.db.QueryRow(ctx, getMediaByIDAndWorkspace, arg.ID, arg.WorkspaceID)
	var i Media
	err := row.Scan(
		&i.ID,
		&i.StorageKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.CreatedAt,
		&i.UploadedAt,
		&i.WorkspaceID,
		&i.ContentHash,
		&i.CleanupAfterAt,
		&i.Width,
		&i.Height,
		&i.DurationMs,
		&i.UsageVersion,
	)
	return i, err
}

const hardDeleteMedia = `-- name: HardDeleteMedia :exec
DELETE FROM media
WHERE id = $1
`

func (q *Queries) HardDeleteMedia(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, hardDeleteMedia, id)
	return err
}

const hasBlockingMediaUsage = `-- name: HasBlockingMediaUsage :one
SELECT (
  EXISTS (
    SELECT 1
    FROM media_post_usages post_usage
    WHERE post_usage.media_id = $1
      AND (
        post_usage.cleanup_after_at IS NULL
        OR post_usage.cleanup_after_at > NOW()
      )
  )
  OR EXISTS (
    SELECT 1
    FROM media_processing_usages processing_usage
    WHERE processing_usage.media_id = $1
      AND (
        processing_usage.cleanup_after_at IS NULL
        OR processing_usage.cleanup_after_at > NOW()
      )
  )
)::boolean
`

func (q *Queries) HasBlockingMediaUsage(ctx context.Context, mediaID string) (bool, error) {
	row := q.db.QueryRow(ctx, hasBlockingMediaUsage, mediaID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listMediaByWorkspace = `-- name: ListMediaByWorkspace :many
SELECT id, storage_key, content_type, size_bytes, status, created_at, uploaded_at, workspace_id, content_hash, cleanup_after_at, width, height, duration_ms, usage_version FROM media
WHERE workspace_id = $1 AND status != 'deleted'
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListMediaByWorkspaceParams struct {
	WorkspaceID string `json:"workspace_id"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

func (q *Queries) ListMediaByWorkspace(ctx context.Context, arg ListMediaByWorkspaceParams) ([]Media, error) {
	rows, err := q.db.Query(ctx, listMediaByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Media{}
	for rows.Next() {
		var i Media
		if err := rows.Scan(
			&i.ID,
			&i.StorageKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.Status,
			&i.CreatedAt,
			&i.UploadedAt,
			&i.WorkspaceID,
			&i.ContentHash,
			&i.CleanupAfterAt,
			&i.Width,
			&i.Height,
			&i.DurationMs,
			&i.UsageVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMediaUploaded = `-- name: MarkMediaUploaded :one
UPDATE media m
SET status = 'uploaded',
    size_bytes = $2,
    content_type = $3,
    width = $4,
    height = $5,
    duration_ms = $6,
    uploaded_at = NOW(),
    cleanup_after_at = GREATEST(
      COALESCE(m.cleanup_after_at, '-infinity'::timestamptz),
      NOW() + CASE COALESCE((
        SELECT subscriptions.plan_id
        FROM subscriptions
        WHERE subscriptions.workspace_id = m.workspace_id
      ), 'free')
        WHEN 'api' THEN INTERVAL '2 days'
        WHEN 'basic' THEN INTERVAL '4 days'
        WHEN 'growth' THEN INTERVAL '15 days'
        WHEN 'team' THEN INTERVAL '30 days'
        WHEN 'enterprise' THEN INTERVAL '30 days'
        ELSE INTERVAL '1 day'
      END
    )
WHERE m.id = $1
  AND m.status = 'pending'
RETURNING m.id, m.storage_key, m.content_type, m.size_bytes, m.status, m.created_at, m.uploaded_at, m.workspace_id, m.content_hash, m.cleanup_after_at, m.width, m.height, m.duration_ms, m.usage_version
`

type MarkMediaUploadedParams struct {
	ID          string      `json:"id"`
	SizeBytes   int64       `json:"size_bytes"`
	ContentType string      `json:"content_type"`
	Width       pgtype.Int4 `json:"width"`
	Height      pgtype.Int4 `json:"height"`
	DurationMs  pgtype.Int4 `json:"duration_ms"`
}

// Hydrates a pending row after the client's PUT lands. width / height /
// duration_ms come from storage.ProbeVideo for video uploads (see
// migration 056); pass NULL for images or for any case where probing
// couldn't extract them. NULLs leave the columns at NULL — the validator
// treats unknown dimensions as "warn, don't block" rather than 0×0.
func (q *Queries) MarkMediaUploaded(ctx context.Context, arg MarkMediaUploadedParams) (Media, error) {
	row := q.db.QueryRow(ctx, markMediaUploaded,
		arg.ID,
		arg.SizeBytes,
		arg.ContentType,
		arg.Width,
		arg.Height,
		arg.DurationMs,
	)
	var i Media
	err := row.Scan(
		&i.ID,
		&i.StorageKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.CreatedAt,
		&i.UploadedAt,
		&i.WorkspaceID,
		&i.ContentHash,
		&i.CleanupAfterAt,
		&i.Width,
		&i.Height,
		&i.DurationMs,
		&i.UsageVersion,
	)
	return i, err
}

const releaseAbandonedMediaClaim = `-- name: ReleaseAbandonedMediaClaim :exec
UPDATE media
SET status = 'pending',
    cleanup_after_at = NULL
WHERE id = $1
  AND status = 'deleted'
  AND created_at < NOW() - INTERVAL '7 days'
`

func (q *Queries) ReleaseAbandonedMediaClaim(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, releaseAbandonedMediaClaim, id)
	return err
}

const softDeleteMedia = `-- name: SoftDeleteMedia :exec
UPDATE media
SET status = 'deleted',
    cleanup_after_at = NOW()
WHERE id = $1
  AND workspace_id = $2
  AND status != 'deleted'
`

type SoftDeleteMediaParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) SoftDeleteMedia(ctx context.Context, arg SoftDeleteMediaParams) error {
	_, err := q.db.Exec(ctx, softDeleteMedia, arg.ID, arg.WorkspaceID)
	return err
}

const softDeleteUnusedMedia = `-- name: SoftDeleteUnusedMedia :execrows
WITH snapshot_candidate AS MATERIALIZED (
  SELECT candidate.id, candidate.usage_version
  FROM media candidate
  WHERE candidate.id = $1
    AND candidate.workspace_id = $2
    AND candidate.status != 'deleted'
), locked_candidate AS (
  SELECT candidate.id
  FROM media candidate
  JOIN snapshot_candidate snapshot
    ON snapshot.id = candidate.id
   AND snapshot.usage_version = candidate.usage_version
  FOR UPDATE OF candidate SKIP LOCKED
)
UPDATE media candidate
SET status = 'deleted',
    cleanup_after_at = NOW()
FROM locked_candidate
WHERE candidate.id = locked_candidate.id
  AND NOT EXISTS (
    SELECT 1
    FROM media_post_usages post_blocker
    WHERE post_blocker.media_id = candidate.id
      AND (
        post_blocker.cleanup_after_at IS NULL
        OR post_blocker.cleanup_after_at > NOW()
      )
  )
  AND NOT EXISTS (
    SELECT 1
    FROM media_processing_usages processing_blocker
    WHERE processing_blocker.media_id = candidate.id
      AND (
        processing_blocker.cleanup_after_at IS NULL
        OR processing_blocker.cleanup_after_at > NOW()
      )
  )
`

type SoftDeleteUnusedMediaParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) SoftDeleteUnusedMedia(ctx context.Context, arg SoftDeleteUnusedMediaParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteUnusedMedia, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMediaStorageKey = `-- name: UpdateMediaStorageKey :one
UPDATE media SET storage_key = $2
WHERE id = $1
RETURNING id, storage_key, content_type, size_bytes, status, created_at, uploaded_at, workspace_id, content_hash, cleanup_after_at, width, height, duration_ms, usage_version
`

type UpdateMediaStorageKeyParams struct {
	ID         string `json:"id"`
	StorageKey string `json:"storage_key"`
}

func (q *Queries) UpdateMediaStorageKey(ctx context.Context, arg UpdateMediaStorageKeyParams) (Media, error) {
	row := q.db.QueryRow(ctx, updateMediaStorageKey, arg.ID, arg.StorageKey)
	var i Media
	err := row.Scan(
		&i.ID,
		&i.StorageKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.CreatedAt,
		&i.UploadedAt,
		&i.WorkspaceID,
		&i.ContentHash,
		&i.CleanupAfterAt,
		&i.Width,
		&i.Height,
		&i.DurationMs,
		&i.UsageVersion,
	)
	return i, err
}
