// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media_processing_jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimMediaProcessingJobsByKind = `-- name: ClaimMediaProcessingJobsByKind :many
WITH eligible AS (
  SELECT candidate.id
  FROM media_processing_jobs candidate
  WHERE candidate.kind = $1
    AND candidate.status = 'queued'
  ORDER BY candidate.created_at ASC, candidate.id ASC
  LIMIT $2::int
  FOR UPDATE SKIP LOCKED
)
UPDATE media_processing_jobs j
SET status = 'processing',
    attempts = j.attempts + 1,
    started_at = COALESCE(j.started_at, NOW()),
    updated_at = NOW()
FROM eligible
WHERE j.id = eligible.id
RETURNING j.id, j.workspace_id, j.kind, j.status, j.input_video_media_id, j.input_audio_media_id, j.output_media_id, j.mode, j.fit, j.video_volume, j.audio_volume, j.audio_start_ms, j.request, j.idempotency_key, j.request_hash, j.error_code, j.error_message, j.retryable, j.attempts, j.created_at, j.updated_at, j.started_at, j.completed_at, j.input_media_id
`

type ClaimMediaProcessingJobsByKindParams struct {
	JobKind    string `json:"job_kind"`
	BatchLimit int32  `json:"batch_limit"`
}

func (q *Queries) ClaimMediaProcessingJobsByKind(ctx context.Context, arg ClaimMediaProcessingJobsByKindParams) ([]MediaProcessingJob, error) {
	rows, err := q.db.Query(ctx, claimMediaProcessingJobsByKind, arg.JobKind, arg.BatchLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaProcessingJob{}
	for rows.Next() {
		var i MediaProcessingJob
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Kind,
			&i.Status,
			&i.InputVideoMediaID,
			&i.InputAudioMediaID,
			&i.OutputMediaID,
			&i.Mode,
			&i.Fit,
			&i.VideoVolume,
			&i.AudioVolume,
			&i.AudioStartMs,
			&i.Request,
			&i.IdempotencyKey,
			&i.RequestHash,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.Retryable,
			&i.Attempts,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.InputMediaID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createMediaProcessingJob = `-- name: CreateMediaProcessingJob :one
INSERT INTO media_processing_jobs (
  workspace_id,
  kind,
  status,
  input_video_media_id,
  input_audio_media_id,
  output_media_id,
  mode,
  fit,
  video_volume,
  audio_volume,
  audio_start_ms,
  request,
  idempotency_key,
  request_hash
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $14::jsonb,
  $12,
  $13
)
RETURNING id, workspace_id, kind, status, input_video_media_id, input_audio_media_id, output_media_id, mode, fit, video_volume, audio_volume, audio_start_ms, request, idempotency_key, request_hash, error_code, error_message, retryable, attempts, created_at, updated_at, started_at, completed_at, input_media_id
`

type CreateMediaProcessingJobParams struct {
	WorkspaceID       string      `json:"workspace_id"`
	Kind              string      `json:"kind"`
	Status            string      `json:"status"`
	InputVideoMediaID pgtype.Text `json:"input_video_media_id"`
	InputAudioMediaID pgtype.Text `json:"input_audio_media_id"`
	OutputMediaID     pgtype.Text `json:"output_media_id"`
	Mode              string      `json:"mode"`
	Fit               string      `json:"fit"`
	VideoVolume       int32       `json:"video_volume"`
	AudioVolume       int32       `json:"audio_volume"`
	AudioStartMs      int32       `json:"audio_start_ms"`
	IdempotencyKey    pgtype.Text `json:"idempotency_key"`
	RequestHash       pgtype.Text `json:"request_hash"`
	RequestJson       []byte      `json:"request_json"`
}

func (q *Queries) CreateMediaProcessingJob(ctx context.Context, arg CreateMediaProcessingJobParams) (MediaProcessingJob, error) {
	row := q.db.QueryRow(ctx, createMediaProcessingJob,
		arg.WorkspaceID,
		arg.Kind,
		arg.Status,
		arg.InputVideoMediaID,
		arg.InputAudioMediaID,
		arg.OutputMediaID,
		arg.Mode,
		arg.Fit,
		arg.VideoVolume,
		arg.AudioVolume,
		arg.AudioStartMs,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.RequestJson,
	)
	var i MediaProcessingJob
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Status,
		&i.InputVideoMediaID,
		&i.InputAudioMediaID,
		&i.OutputMediaID,
		&i.Mode,
		&i.Fit,
		&i.VideoVolume,
		&i.AudioVolume,
		&i.AudioStartMs,
		&i.Request,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Retryable,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.InputMediaID,
	)
	return i, err
}

const getMediaProcessingJobByIDAndWorkspace = `-- name: GetMediaProcessingJobByIDAndWorkspace :one
SELECT id, workspace_id, kind, status, input_video_media_id, input_audio_media_id, output_media_id, mode, fit, video_volume, audio_volume, audio_start_ms, request, idempotency_key, request_hash, error_code, error_message, retryable, attempts, created_at, updated_at, started_at, completed_at, input_media_id FROM media_processing_jobs
WHERE id = $1 AND workspace_id = $2
`

type GetMediaProcessingJobByIDAndWorkspaceParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetMediaProcessingJobByIDAndWorkspace(ctx context.Context, arg GetMediaProcessingJobByIDAndWorkspaceParams) (MediaProcessingJob, error) {
	row := q.db.QueryRow(ctx, getMediaProcessingJobByIDAndWorkspace, arg.ID, arg.WorkspaceID)
	var i MediaProcessingJob
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Status,
		&i.InputVideoMediaID,
		&i.InputAudioMediaID,
		&i.OutputMediaID,
		&i.Mode,
		&i.Fit,
		&i.VideoVolume,
		&i.AudioVolume,
		&i.AudioStartMs,
		&i.Request,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Retryable,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.InputMediaID,
	)
	return i, err
}

const getMediaProcessingJobByIdempotencyKey = `-- name: GetMediaProcessingJobByIdempotencyKey :one
SELECT id, workspace_id, kind, status, input_video_media_id, input_audio_media_id, output_media_id, mode, fit, video_volume, audio_volume, audio_start_ms, request, idempotency_key, request_hash, error_code, error_message, retryable, attempts, created_at, updated_at, started_at, completed_at, input_media_id FROM media_processing_jobs
WHERE workspace_id = $1 AND idempotency_key = $2
`

type GetMediaProcessingJobByIdempotencyKeyParams struct {
	WorkspaceID    string      `json:"workspace_id"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
}

func (q *Queries) GetMediaProcessingJobByIdempotencyKey(ctx context.Context, arg GetMediaProcessingJobByIdempotencyKeyParams) (MediaProcessingJob, error) {
	row := q.db.QueryRow(ctx, getMediaProcessingJobByIdempotencyKey, arg.WorkspaceID, arg.IdempotencyKey)
	var i MediaProcessingJob
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Status,
		&i.InputVideoMediaID,
		&i.InputAudioMediaID,
		&i.OutputMediaID,
		&i.Mode,
		&i.Fit,
		&i.VideoVolume,
		&i.AudioVolume,
		&i.AudioStartMs,
		&i.Request,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Retryable,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.InputMediaID,
	)
	return i, err
}

const markMediaProcessingJobFailed = `-- name: MarkMediaProcessingJobFailed :one
UPDATE media_processing_jobs
SET status = 'failed',
    error_code = $2,
    error_message = $3,
    retryable = $4,
    updated_at = NOW(),
    completed_at = NOW()
WHERE id = $1
RETURNING id, workspace_id, kind, status, input_video_media_id, input_audio_media_id, output_media_id, mode, fit, video_volume, audio_volume, audio_start_ms, request, idempotency_key, request_hash, error_code, error_message, retryable, attempts, created_at, updated_at, started_at, completed_at, input_media_id
`

type MarkMediaProcessingJobFailedParams struct {
	ID           string      `json:"id"`
	ErrorCode    pgtype.Text `json:"error_code"`
	ErrorMessage pgtype.Text `json:"error_message"`
	Retryable    bool        `json:"retryable"`
}

func (q *Queries) MarkMediaProcessingJobFailed(ctx context.Context, arg MarkMediaProcessingJobFailedParams) (MediaProcessingJob, error) {
	row := q.db.QueryRow(ctx, markMediaProcessingJobFailed,
		arg.ID,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.Retryable,
	)
	var i MediaProcessingJob
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Status,
		&i.InputVideoMediaID,
		&i.InputAudioMediaID,
		&i.OutputMediaID,
		&i.Mode,
		&i.Fit,
		&i.VideoVolume,
		&i.AudioVolume,
		&i.AudioStartMs,
		&i.Request,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Retryable,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.InputMediaID,
	)
	return i, err
}

const markMediaProcessingJobSucceeded = `-- name: MarkMediaProcessingJobSucceeded :one
UPDATE media_processing_jobs
SET status = 'succeeded',
    output_media_id = $2,
    error_code = NULL,
    error_message = NULL,
    retryable = false,
    updated_at = NOW(),
    completed_at = NOW()
WHERE id = $1
RETURNING id, workspace_id, kind, status, input_video_media_id, input_audio_media_id, output_media_id, mode, fit, video_volume, audio_volume, audio_start_ms, request, idempotency_key, request_hash, error_code, error_message, retryable, attempts, created_at, updated_at, started_at, completed_at, input_media_id
`

type MarkMediaProcessingJobSucceededParams struct {
	ID            string      `json:"id"`
	OutputMediaID pgtype.Text `json:"output_media_id"`
}

func (q *Queries) MarkMediaProcessingJobSucceeded(ctx context.Context, arg MarkMediaProcessingJobSucceededParams) (MediaProcessingJob, error) {
	row := q.db.QueryRow(ctx, markMediaProcessingJobSucceeded, arg.ID, arg.OutputMediaID)
	var i MediaProcessingJob
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Status,
		&i.InputVideoMediaID,
		&i.InputAudioMediaID,
		&i.OutputMediaID,
		&i.Mode,
		&i.Fit,
		&i.VideoVolume,
		&i.AudioVolume,
		&i.AudioStartMs,
		&i.Request,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Retryable,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.InputMediaID,
	)
	return i, err
}

const requeueMediaProcessingJob = `-- name: RequeueMediaProcessingJob :one
UPDATE media_processing_jobs
SET status = 'queued',
    error_code = NULL,
    error_message = NULL,
    retryable = false,
    updated_at = NOW(),
    completed_at = NULL
WHERE id = $1
RETURNING id, workspace_id, kind, status, input_video_media_id, input_audio_media_id, output_media_id, mode, fit, video_volume, audio_volume, audio_start_ms, request, idempotency_key, request_hash, error_code, error_message, retryable, attempts, created_at, updated_at, started_at, completed_at, input_media_id
`

func (q *Queries) RequeueMediaProcessingJob(ctx context.Context, id string) (MediaProcessingJob, error) {
	row := q.db.QueryRow(ctx, requeueMediaProcessingJob, id)
	var i MediaProcessingJob
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Status,
		&i.InputVideoMediaID,
		&i.InputAudioMediaID,
		&i.OutputMediaID,
		&i.Mode,
		&i.Fit,
		&i.VideoVolume,
		&i.AudioVolume,
		&i.AudioStartMs,
		&i.Request,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Retryable,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.InputMediaID,
	)
	return i, err
}
