// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media_processing_usages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMediaProcessingUsage = `-- name: CreateMediaProcessingUsage :one
INSERT INTO media_processing_usages (
  workspace_id,
  job_id,
  media_id,
  role,
  status,
  cleanup_after_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
RETURNING id, workspace_id, job_id, media_id, role, status, cleanup_after_at, created_at, updated_at
`

type CreateMediaProcessingUsageParams struct {
	WorkspaceID    string             `json:"workspace_id"`
	JobID          string             `json:"job_id"`
	MediaID        string             `json:"media_id"`
	Role           string             `json:"role"`
	Status         string             `json:"status"`
	CleanupAfterAt pgtype.Timestamptz `json:"cleanup_after_at"`
}

func (q *Queries) CreateMediaProcessingUsage(ctx context.Context, arg CreateMediaProcessingUsageParams) (MediaProcessingUsage, error) {
	row := q.db.QueryRow(ctx, createMediaProcessingUsage,
		arg.WorkspaceID,
		arg.JobID,
		arg.MediaID,
		arg.Role,
		arg.Status,
		arg.CleanupAfterAt,
	)
	var i MediaProcessingUsage
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.JobID,
		&i.MediaID,
		&i.Role,
		&i.Status,
		&i.CleanupAfterAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMediaProcessingUsagesByJob = `-- name: DeleteMediaProcessingUsagesByJob :exec
DELETE FROM media_processing_usages
WHERE job_id = $1
`

func (q *Queries) DeleteMediaProcessingUsagesByJob(ctx context.Context, jobID string) error {
	_, err := q.db.Exec(ctx, deleteMediaProcessingUsagesByJob, jobID)
	return err
}

const hasActiveMediaProcessingUsage = `-- name: HasActiveMediaProcessingUsage :one
SELECT EXISTS (
  SELECT 1
  FROM media_processing_usages
  WHERE media_id = $1
    AND status = 'active'
)::boolean
`

func (q *Queries) HasActiveMediaProcessingUsage(ctx context.Context, mediaID string) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveMediaProcessingUsage, mediaID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listMediaProcessingUsagesByJob = `-- name: ListMediaProcessingUsagesByJob :many
SELECT id, workspace_id, job_id, media_id, role, status, cleanup_after_at, created_at, updated_at
FROM media_processing_usages
WHERE job_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListMediaProcessingUsagesByJob(ctx context.Context, jobID string) ([]MediaProcessingUsage, error) {
	rows, err := q.db.Query(ctx, listMediaProcessingUsagesByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaProcessingUsage{}
	for rows.Next() {
		var i MediaProcessingUsage
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.JobID,
			&i.MediaID,
			&i.Role,
			&i.Status,
			&i.CleanupAfterAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionMediaProcessingUsages = `-- name: TransitionMediaProcessingUsages :exec
UPDATE media_processing_usages
SET status = $2,
    cleanup_after_at = $3,
    updated_at = NOW()
WHERE job_id = $1
  AND status = 'active'
`

type TransitionMediaProcessingUsagesParams struct {
	JobID          string             `json:"job_id"`
	Status         string             `json:"status"`
	CleanupAfterAt pgtype.Timestamptz `json:"cleanup_after_at"`
}

func (q *Queries) TransitionMediaProcessingUsages(ctx context.Context, arg TransitionMediaProcessingUsagesParams) error {
	_, err := q.db.Exec(ctx, transitionMediaProcessingUsages, arg.JobID, arg.Status, arg.CleanupAfterAt)
	return err
}
