// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Prefix      string             `json:"prefix"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	KeyHash     string             `json:"key_hash"`
	Environment string             `json:"environment"`
	WorkspaceID string             `json:"workspace_id"`
}

type ApiMetric struct {
	ID          int64              `json:"id"`
	WorkspaceID string             `json:"workspace_id"`
	Method      string             `json:"method"`
	Path        string             `json:"path"`
	StatusCode  int32              `json:"status_code"`
	DurationMs  int32              `json:"duration_ms"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ConnectSession struct {
	ID                       string             `json:"id"`
	ProfileID                string             `json:"profile_id"`
	Platform                 string             `json:"platform"`
	ExternalUserID           string             `json:"external_user_id"`
	ExternalUserEmail        pgtype.Text        `json:"external_user_email"`
	ReturnUrl                pgtype.Text        `json:"return_url"`
	Status                   string             `json:"status"`
	CompletedSocialAccountID pgtype.Text        `json:"completed_social_account_id"`
	OauthState               string             `json:"oauth_state"`
	PkceVerifier             pgtype.Text        `json:"pkce_verifier"`
	ExpiresAt                pgtype.Timestamptz `json:"expires_at"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	CompletedAt              pgtype.Timestamptz `json:"completed_at"`
}

type InboxItem struct {
	ID               string             `json:"id"`
	SocialAccountID  string             `json:"social_account_id"`
	WorkspaceID      string             `json:"workspace_id"`
	Source           string             `json:"source"`
	ExternalID       string             `json:"external_id"`
	ParentExternalID pgtype.Text        `json:"parent_external_id"`
	AuthorName       pgtype.Text        `json:"author_name"`
	AuthorID         pgtype.Text        `json:"author_id"`
	AuthorAvatarUrl  pgtype.Text        `json:"author_avatar_url"`
	Body             pgtype.Text        `json:"body"`
	IsRead           bool               `json:"is_read"`
	IsOwn            bool               `json:"is_own"`
	ReceivedAt       pgtype.Timestamptz `json:"received_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	Metadata         []byte             `json:"metadata"`
	ThreadKey        string             `json:"thread_key"`
	ThreadStatus     string             `json:"thread_status"`
	AssignedTo       pgtype.Text        `json:"assigned_to"`
	LinkedPostID     pgtype.Text        `json:"linked_post_id"`
}

type InboxMediaCache struct {
	SocialAccountID string             `json:"social_account_id"`
	ExternalID      string             `json:"external_id"`
	MediaUrl        string             `json:"media_url"`
	Caption         string             `json:"caption"`
	Timestamp       string             `json:"timestamp"`
	MediaType       string             `json:"media_type"`
	Permalink       string             `json:"permalink"`
	FetchedAt       pgtype.Timestamptz `json:"fetched_at"`
}

type LandingVisit struct {
	ID         int64              `json:"id"`
	Path       string             `json:"path"`
	SourceCode string             `json:"source_code"`
	Referer    string             `json:"referer"`
	SessionID  string             `json:"session_id"`
	UserAgent  string             `json:"user_agent"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Media struct {
	ID          string             `json:"id"`
	StorageKey  string             `json:"storage_key"`
	ContentType string             `json:"content_type"`
	SizeBytes   int64              `json:"size_bytes"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UploadedAt  pgtype.Timestamptz `json:"uploaded_at"`
	WorkspaceID string             `json:"workspace_id"`
	ContentHash pgtype.Text        `json:"content_hash"`
}

type NotificationChannel struct {
	ID          string             `json:"id"`
	UserID      string             `json:"user_id"`
	WorkspaceID pgtype.Text        `json:"workspace_id"`
	Kind        string             `json:"kind"`
	Config      []byte             `json:"config"`
	Label       pgtype.Text        `json:"label"`
	VerifiedAt  pgtype.Timestamptz `json:"verified_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type NotificationDelivery struct {
	ID             string             `json:"id"`
	SubscriptionID string             `json:"subscription_id"`
	ChannelID      string             `json:"channel_id"`
	EventType      string             `json:"event_type"`
	EventID        string             `json:"event_id"`
	Payload        []byte             `json:"payload"`
	Status         string             `json:"status"`
	Attempts       int32              `json:"attempts"`
	NextRetryAt    pgtype.Timestamptz `json:"next_retry_at"`
	LastError      pgtype.Text        `json:"last_error"`
	DeliveredAt    pgtype.Timestamptz `json:"delivered_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type NotificationSubscription struct {
	ID          string             `json:"id"`
	UserID      string             `json:"user_id"`
	WorkspaceID pgtype.Text        `json:"workspace_id"`
	EventType   string             `json:"event_type"`
	ChannelID   string             `json:"channel_id"`
	Enabled     bool               `json:"enabled"`
	Filter      []byte             `json:"filter"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type OauthState struct {
	State       string             `json:"state"`
	ProfileID   string             `json:"profile_id"`
	Platform    string             `json:"platform"`
	RedirectUrl pgtype.Text        `json:"redirect_url"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Plan struct {
	ID            string             `json:"id"`
	Name          string             `json:"name"`
	PriceCents    int32              `json:"price_cents"`
	PostLimit     int32              `json:"post_limit"`
	StripePriceID pgtype.Text        `json:"stripe_price_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	WhiteLabel    bool               `json:"white_label"`
}

type PlatformCredential struct {
	ID           string             `json:"id"`
	Platform     string             `json:"platform"`
	ClientID     string             `json:"client_id"`
	ClientSecret string             `json:"client_secret"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	WorkspaceID  string             `json:"workspace_id"`
}

type PostAnalytic struct {
	ID                  string             `json:"id"`
	SocialPostResultID  string             `json:"social_post_result_id"`
	Views               pgtype.Int8        `json:"views"`
	Likes               pgtype.Int8        `json:"likes"`
	Comments            pgtype.Int8        `json:"comments"`
	Shares              pgtype.Int8        `json:"shares"`
	Reach               pgtype.Int8        `json:"reach"`
	Impressions         pgtype.Int8        `json:"impressions"`
	EngagementRate      pgtype.Numeric     `json:"engagement_rate"`
	RawData             []byte             `json:"raw_data"`
	FetchedAt           pgtype.Timestamptz `json:"fetched_at"`
	Saves               pgtype.Int8        `json:"saves"`
	Clicks              pgtype.Int8        `json:"clicks"`
	VideoViews          pgtype.Int8        `json:"video_views"`
	PlatformSpecific    []byte             `json:"platform_specific"`
	ConsecutiveFailures int32              `json:"consecutive_failures"`
	LastFailureReason   pgtype.Text        `json:"last_failure_reason"`
}

type Profile struct {
	ID                   string             `json:"id"`
	Name                 string             `json:"name"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	BrandingLogoUrl      pgtype.Text        `json:"branding_logo_url"`
	BrandingDisplayName  pgtype.Text        `json:"branding_display_name"`
	BrandingPrimaryColor pgtype.Text        `json:"branding_primary_color"`
	WorkspaceID          string             `json:"workspace_id"`
}

type SocialAccount struct {
	ID                string             `json:"id"`
	ProfileID         string             `json:"profile_id"`
	Platform          string             `json:"platform"`
	AccessToken       string             `json:"access_token"`
	RefreshToken      pgtype.Text        `json:"refresh_token"`
	TokenExpiresAt    pgtype.Timestamptz `json:"token_expires_at"`
	ExternalAccountID string             `json:"external_account_id"`
	AccountName       pgtype.Text        `json:"account_name"`
	AccountAvatarUrl  pgtype.Text        `json:"account_avatar_url"`
	ConnectedAt       pgtype.Timestamptz `json:"connected_at"`
	DisconnectedAt    pgtype.Timestamptz `json:"disconnected_at"`
	Metadata          []byte             `json:"metadata"`
	Scope             []string           `json:"scope"`
	Status            string             `json:"status"`
	ConnectionType    string             `json:"connection_type"`
	ConnectSessionID  pgtype.Text        `json:"connect_session_id"`
	ExternalUserID    pgtype.Text        `json:"external_user_id"`
	ExternalUserEmail pgtype.Text        `json:"external_user_email"`
	LastRefreshedAt   pgtype.Timestamptz `json:"last_refreshed_at"`
}

type SocialPost struct {
	ID             string             `json:"id"`
	Caption        pgtype.Text        `json:"caption"`
	MediaUrls      []string           `json:"media_urls"`
	Status         string             `json:"status"`
	ScheduledAt    pgtype.Timestamptz `json:"scheduled_at"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Metadata       []byte             `json:"metadata"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	WorkspaceID    string             `json:"workspace_id"`
	ArchivedAt     pgtype.Timestamptz `json:"archived_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type SocialPostResult struct {
	ID              string             `json:"id"`
	PostID          string             `json:"post_id"`
	SocialAccountID string             `json:"social_account_id"`
	Status          string             `json:"status"`
	ExternalID      pgtype.Text        `json:"external_id"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
	Caption         string             `json:"caption"`
	Url             pgtype.Text        `json:"url"`
}

type Subscription struct {
	ID                   string             `json:"id"`
	PlanID               string             `json:"plan_id"`
	StripeCustomerID     pgtype.Text        `json:"stripe_customer_id"`
	StripeSubscriptionID pgtype.Text        `json:"stripe_subscription_id"`
	Status               string             `json:"status"`
	CurrentPeriodStart   pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd     pgtype.Timestamptz `json:"current_period_end"`
	CancelAtPeriodEnd    pgtype.Bool        `json:"cancel_at_period_end"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	TrialUsed            bool               `json:"trial_used"`
	WorkspaceID          string             `json:"workspace_id"`
}

type Usage struct {
	ID          string             `json:"id"`
	Period      string             `json:"period"`
	PostCount   int32              `json:"post_count"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	WorkspaceID string             `json:"workspace_id"`
}

type User struct {
	ID                         string             `json:"id"`
	Email                      string             `json:"email"`
	Name                       pgtype.Text        `json:"name"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	DefaultProfileID           pgtype.Text        `json:"default_profile_id"`
	LastProfileID              pgtype.Text        `json:"last_profile_id"`
	OnboardingCompleted        bool               `json:"onboarding_completed"`
	OnboardingIntent           pgtype.Text        `json:"onboarding_intent"`
	OnboardingShownAt          pgtype.Timestamptz `json:"onboarding_shown_at"`
	OnboardingCompletedAt      pgtype.Timestamptz `json:"onboarding_completed_at"`
	ActivationCompletedAt      pgtype.Timestamptz `json:"activation_completed_at"`
	ActivationGuideDismissedAt pgtype.Timestamptz `json:"activation_guide_dismissed_at"`
}

type UserTutorial struct {
	UserID      string             `json:"user_id"`
	TutorialID  string             `json:"tutorial_id"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	DismissedAt pgtype.Timestamptz `json:"dismissed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Webhook struct {
	ID          string             `json:"id"`
	Url         string             `json:"url"`
	Secret      string             `json:"secret"`
	Events      []string           `json:"events"`
	Active      bool               `json:"active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	WorkspaceID string             `json:"workspace_id"`
}

type WebhookDelivery struct {
	ID          string             `json:"id"`
	WebhookID   string             `json:"webhook_id"`
	Event       string             `json:"event"`
	Payload     []byte             `json:"payload"`
	StatusCode  pgtype.Int4        `json:"status_code"`
	Attempts    int32              `json:"attempts"`
	DeliveredAt pgtype.Timestamptz `json:"delivered_at"`
	NextRetryAt pgtype.Timestamptz `json:"next_retry_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Workspace struct {
	ID                     string             `json:"id"`
	UserID                 string             `json:"user_id"`
	Name                   string             `json:"name"`
	PerAccountMonthlyLimit pgtype.Int4        `json:"per_account_monthly_limit"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	UsageModes             []string           `json:"usage_modes"`
}
