// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotificationChannel = `-- name: CreateNotificationChannel :one


INSERT INTO notification_channels (user_id, workspace_id, kind, config, label, verified_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, workspace_id, kind, config, label, verified_at, created_at, deleted_at
`

type CreateNotificationChannelParams struct {
	UserID      string             `json:"user_id"`
	WorkspaceID pgtype.Text        `json:"workspace_id"`
	Kind        string             `json:"kind"`
	Config      []byte             `json:"config"`
	Label       pgtype.Text        `json:"label"`
	VerifiedAt  pgtype.Timestamptz `json:"verified_at"`
}

// Queries for the user-facing notification system.
// See migration 040_notifications.sql for the schema.
// ─── Channels ────────────────────────────────────────────────────────
func (q *Queries) CreateNotificationChannel(ctx context.Context, arg CreateNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, createNotificationChannel,
		arg.UserID,
		arg.WorkspaceID,
		arg.Kind,
		arg.Config,
		arg.Label,
		arg.VerifiedAt,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Config,
		&i.Label,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createNotificationDelivery = `-- name: CreateNotificationDelivery :exec
INSERT INTO notification_deliveries (subscription_id, channel_id, event_type, event_id, payload)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (event_id, channel_id) DO NOTHING
`

type CreateNotificationDeliveryParams struct {
	SubscriptionID string `json:"subscription_id"`
	ChannelID      string `json:"channel_id"`
	EventType      string `json:"event_type"`
	EventID        string `json:"event_id"`
	Payload        []byte `json:"payload"`
}

// Idempotent insert — if (event_id, channel_id) already exists from a
// retried publish we silently skip. The UNIQUE constraint on the table
// enforces one delivery per logical event per channel.
func (q *Queries) CreateNotificationDelivery(ctx context.Context, arg CreateNotificationDeliveryParams) error {
	_, err := q.db.Exec(ctx, createNotificationDelivery,
		arg.SubscriptionID,
		arg.ChannelID,
		arg.EventType,
		arg.EventID,
		arg.Payload,
	)
	return err
}

const createNotificationSubscription = `-- name: CreateNotificationSubscription :one

INSERT INTO notification_subscriptions (user_id, workspace_id, event_type, channel_id, enabled, filter)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, workspace_id, event_type, channel_id)
DO UPDATE SET enabled = EXCLUDED.enabled, filter = EXCLUDED.filter
RETURNING id, user_id, workspace_id, event_type, channel_id, enabled, filter, created_at
`

type CreateNotificationSubscriptionParams struct {
	UserID      string      `json:"user_id"`
	WorkspaceID pgtype.Text `json:"workspace_id"`
	EventType   string      `json:"event_type"`
	ChannelID   string      `json:"channel_id"`
	Enabled     bool        `json:"enabled"`
	Filter      []byte      `json:"filter"`
}

// ─── Subscriptions ───────────────────────────────────────────────────
func (q *Queries) CreateNotificationSubscription(ctx context.Context, arg CreateNotificationSubscriptionParams) (NotificationSubscription, error) {
	row := q.db.QueryRow(ctx, createNotificationSubscription,
		arg.UserID,
		arg.WorkspaceID,
		arg.EventType,
		arg.ChannelID,
		arg.Enabled,
		arg.Filter,
	)
	var i NotificationSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkspaceID,
		&i.EventType,
		&i.ChannelID,
		&i.Enabled,
		&i.Filter,
		&i.CreatedAt,
	)
	return i, err
}

const deleteNotificationSubscription = `-- name: DeleteNotificationSubscription :exec
DELETE FROM notification_subscriptions
WHERE id = $1 AND user_id = $2
`

type DeleteNotificationSubscriptionParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteNotificationSubscription(ctx context.Context, arg DeleteNotificationSubscriptionParams) error {
	_, err := q.db.Exec(ctx, deleteNotificationSubscription, arg.ID, arg.UserID)
	return err
}

const getNotificationChannel = `-- name: GetNotificationChannel :one
SELECT id, user_id, workspace_id, kind, config, label, verified_at, created_at, deleted_at FROM notification_channels
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetNotificationChannelParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetNotificationChannel(ctx context.Context, arg GetNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, getNotificationChannel, arg.ID, arg.UserID)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Config,
		&i.Label,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPendingNotificationDeliveries = `-- name: GetPendingNotificationDeliveries :many

SELECT d.id, d.subscription_id, d.channel_id, d.event_type, d.event_id, d.payload, d.status, d.attempts, d.next_retry_at, d.last_error, d.delivered_at, d.created_at, c.kind AS channel_kind, c.config AS channel_config, c.label AS channel_label
FROM notification_deliveries d
JOIN notification_channels c ON c.id = d.channel_id
WHERE d.status = 'pending'
  AND d.next_retry_at <= NOW()
  AND c.deleted_at IS NULL
ORDER BY d.created_at ASC
LIMIT 100
`

type GetPendingNotificationDeliveriesRow struct {
	ID             string             `json:"id"`
	SubscriptionID string             `json:"subscription_id"`
	ChannelID      string             `json:"channel_id"`
	EventType      string             `json:"event_type"`
	EventID        string             `json:"event_id"`
	Payload        []byte             `json:"payload"`
	Status         string             `json:"status"`
	Attempts       int32              `json:"attempts"`
	NextRetryAt    pgtype.Timestamptz `json:"next_retry_at"`
	LastError      pgtype.Text        `json:"last_error"`
	DeliveredAt    pgtype.Timestamptz `json:"delivered_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ChannelKind    string             `json:"channel_kind"`
	ChannelConfig  []byte             `json:"channel_config"`
	ChannelLabel   pgtype.Text        `json:"channel_label"`
}

// ─── Delivery worker ─────────────────────────────────────────────────
func (q *Queries) GetPendingNotificationDeliveries(ctx context.Context) ([]GetPendingNotificationDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, getPendingNotificationDeliveries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPendingNotificationDeliveriesRow{}
	for rows.Next() {
		var i GetPendingNotificationDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.ChannelID,
			&i.EventType,
			&i.EventID,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.NextRetryAt,
			&i.LastError,
			&i.DeliveredAt,
			&i.CreatedAt,
			&i.ChannelKind,
			&i.ChannelConfig,
			&i.ChannelLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationChannelsByUser = `-- name: ListNotificationChannelsByUser :many
SELECT id, user_id, workspace_id, kind, config, label, verified_at, created_at, deleted_at FROM notification_channels
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListNotificationChannelsByUser(ctx context.Context, userID string) ([]NotificationChannel, error) {
	rows, err := q.db.Query(ctx, listNotificationChannelsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationChannel{}
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WorkspaceID,
			&i.Kind,
			&i.Config,
			&i.Label,
			&i.VerifiedAt,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationSubscriptionsByUser = `-- name: ListNotificationSubscriptionsByUser :many
SELECT s.id, s.user_id, s.workspace_id, s.event_type, s.channel_id, s.enabled, s.filter, s.created_at, c.kind AS channel_kind, c.config AS channel_config, c.label AS channel_label
FROM notification_subscriptions s
JOIN notification_channels c ON c.id = s.channel_id
WHERE s.user_id = $1 AND c.deleted_at IS NULL
ORDER BY s.event_type, s.created_at
`

type ListNotificationSubscriptionsByUserRow struct {
	ID            string             `json:"id"`
	UserID        string             `json:"user_id"`
	WorkspaceID   pgtype.Text        `json:"workspace_id"`
	EventType     string             `json:"event_type"`
	ChannelID     string             `json:"channel_id"`
	Enabled       bool               `json:"enabled"`
	Filter        []byte             `json:"filter"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ChannelKind   string             `json:"channel_kind"`
	ChannelConfig []byte             `json:"channel_config"`
	ChannelLabel  pgtype.Text        `json:"channel_label"`
}

func (q *Queries) ListNotificationSubscriptionsByUser(ctx context.Context, userID string) ([]ListNotificationSubscriptionsByUserRow, error) {
	rows, err := q.db.Query(ctx, listNotificationSubscriptionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationSubscriptionsByUserRow{}
	for rows.Next() {
		var i ListNotificationSubscriptionsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WorkspaceID,
			&i.EventType,
			&i.ChannelID,
			&i.Enabled,
			&i.Filter,
			&i.CreatedAt,
			&i.ChannelKind,
			&i.ChannelConfig,
			&i.ChannelLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationChannelVerified = `-- name: MarkNotificationChannelVerified :exec
UPDATE notification_channels
SET verified_at = NOW()
WHERE id = $1 AND user_id = $2
`

type MarkNotificationChannelVerifiedParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) MarkNotificationChannelVerified(ctx context.Context, arg MarkNotificationChannelVerifiedParams) error {
	_, err := q.db.Exec(ctx, markNotificationChannelVerified, arg.ID, arg.UserID)
	return err
}

const markNotificationDeliveryDead = `-- name: MarkNotificationDeliveryDead :exec
UPDATE notification_deliveries
SET status = 'dead', attempts = attempts + 1, last_error = $2, delivered_at = NOW()
WHERE id = $1
`

type MarkNotificationDeliveryDeadParams struct {
	ID        string      `json:"id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) MarkNotificationDeliveryDead(ctx context.Context, arg MarkNotificationDeliveryDeadParams) error {
	_, err := q.db.Exec(ctx, markNotificationDeliveryDead, arg.ID, arg.LastError)
	return err
}

const markNotificationDeliverySent = `-- name: MarkNotificationDeliverySent :exec
UPDATE notification_deliveries
SET status = 'sent', attempts = attempts + 1, delivered_at = NOW(), last_error = NULL
WHERE id = $1
`

func (q *Queries) MarkNotificationDeliverySent(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markNotificationDeliverySent, id)
	return err
}

const resolveNotificationTargets = `-- name: ResolveNotificationTargets :many

SELECT s.id AS subscription_id, s.channel_id, s.event_type, c.kind AS channel_kind
FROM notification_subscriptions s
JOIN notification_channels c ON c.id = s.channel_id
WHERE s.event_type = $1
  AND s.enabled = TRUE
  AND c.deleted_at IS NULL
  AND c.verified_at IS NOT NULL
  AND (s.workspace_id = $2 OR s.workspace_id IS NULL)
`

type ResolveNotificationTargetsParams struct {
	EventType   string      `json:"event_type"`
	WorkspaceID pgtype.Text `json:"workspace_id"`
}

type ResolveNotificationTargetsRow struct {
	SubscriptionID string `json:"subscription_id"`
	ChannelID      string `json:"channel_id"`
	EventType      string `json:"event_type"`
	ChannelKind    string `json:"channel_kind"`
}

// ─── Dispatch / fanout ───────────────────────────────────────────────
// Resolve every subscription that should receive an event, returning
// the delivery row we'd need to insert. Used by NotificationDispatcher
// during event.Publish(). workspace_id is matched against the sub's
// workspace_id; NULL on the sub means "all workspaces of this user".
func (q *Queries) ResolveNotificationTargets(ctx context.Context, arg ResolveNotificationTargetsParams) ([]ResolveNotificationTargetsRow, error) {
	rows, err := q.db.Query(ctx, resolveNotificationTargets, arg.EventType, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResolveNotificationTargetsRow{}
	for rows.Next() {
		var i ResolveNotificationTargetsRow
		if err := rows.Scan(
			&i.SubscriptionID,
			&i.ChannelID,
			&i.EventType,
			&i.ChannelKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scheduleNotificationDeliveryRetry = `-- name: ScheduleNotificationDeliveryRetry :exec
UPDATE notification_deliveries
SET attempts = attempts + 1, next_retry_at = $2, last_error = $3
WHERE id = $1
`

type ScheduleNotificationDeliveryRetryParams struct {
	ID          string             `json:"id"`
	NextRetryAt pgtype.Timestamptz `json:"next_retry_at"`
	LastError   pgtype.Text        `json:"last_error"`
}

func (q *Queries) ScheduleNotificationDeliveryRetry(ctx context.Context, arg ScheduleNotificationDeliveryRetryParams) error {
	_, err := q.db.Exec(ctx, scheduleNotificationDeliveryRetry, arg.ID, arg.NextRetryAt, arg.LastError)
	return err
}

const setNotificationSubscriptionEnabled = `-- name: SetNotificationSubscriptionEnabled :exec
UPDATE notification_subscriptions
SET enabled = $3
WHERE id = $1 AND user_id = $2
`

type SetNotificationSubscriptionEnabledParams struct {
	ID      string `json:"id"`
	UserID  string `json:"user_id"`
	Enabled bool   `json:"enabled"`
}

func (q *Queries) SetNotificationSubscriptionEnabled(ctx context.Context, arg SetNotificationSubscriptionEnabledParams) error {
	_, err := q.db.Exec(ctx, setNotificationSubscriptionEnabled, arg.ID, arg.UserID, arg.Enabled)
	return err
}

const softDeleteNotificationChannel = `-- name: SoftDeleteNotificationChannel :exec
UPDATE notification_channels
SET deleted_at = NOW()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type SoftDeleteNotificationChannelParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) SoftDeleteNotificationChannel(ctx context.Context, arg SoftDeleteNotificationChannelParams) error {
	_, err := q.db.Exec(ctx, softDeleteNotificationChannel, arg.ID, arg.UserID)
	return err
}
