// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: platform_credentials.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlatformCredential = `-- name: CreatePlatformCredential :one
INSERT INTO platform_credentials (
  workspace_id, platform, client_id, client_secret,
  app_bearer_token, consumer_secret
)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (workspace_id, platform) DO UPDATE
SET client_id = EXCLUDED.client_id,
    client_secret = EXCLUDED.client_secret,
    app_bearer_token = CASE
      WHEN $7::BOOLEAN THEN EXCLUDED.app_bearer_token
      ELSE platform_credentials.app_bearer_token
    END,
    consumer_secret = CASE
      WHEN $8::BOOLEAN THEN EXCLUDED.consumer_secret
      ELSE platform_credentials.consumer_secret
    END
RETURNING id, platform, client_id, client_secret, created_at, workspace_id, app_bearer_token, consumer_secret
`

type CreatePlatformCredentialParams struct {
	WorkspaceID            string      `json:"workspace_id"`
	Platform               string      `json:"platform"`
	ClientID               string      `json:"client_id"`
	ClientSecret           string      `json:"client_secret"`
	AppBearerToken         pgtype.Text `json:"app_bearer_token"`
	ConsumerSecret         pgtype.Text `json:"consumer_secret"`
	AppBearerTokenSupplied bool        `json:"app_bearer_token_supplied"`
	ConsumerSecretSupplied bool        `json:"consumer_secret_supplied"`
}

func (q *Queries) CreatePlatformCredential(ctx context.Context, arg CreatePlatformCredentialParams) (PlatformCredential, error) {
	row := q.db.QueryRow(ctx, createPlatformCredential,
		arg.WorkspaceID,
		arg.Platform,
		arg.ClientID,
		arg.ClientSecret,
		arg.AppBearerToken,
		arg.ConsumerSecret,
		arg.AppBearerTokenSupplied,
		arg.ConsumerSecretSupplied,
	)
	var i PlatformCredential
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.ClientID,
		&i.ClientSecret,
		&i.CreatedAt,
		&i.WorkspaceID,
		&i.AppBearerToken,
		&i.ConsumerSecret,
	)
	return i, err
}

const deletePlatformCredential = `-- name: DeletePlatformCredential :exec
DELETE FROM platform_credentials
WHERE workspace_id = $1 AND platform = $2
`

type DeletePlatformCredentialParams struct {
	WorkspaceID string `json:"workspace_id"`
	Platform    string `json:"platform"`
}

func (q *Queries) DeletePlatformCredential(ctx context.Context, arg DeletePlatformCredentialParams) error {
	_, err := q.db.Exec(ctx, deletePlatformCredential, arg.WorkspaceID, arg.Platform)
	return err
}

const getPlatformCredential = `-- name: GetPlatformCredential :one
SELECT id, platform, client_id, client_secret, created_at, workspace_id, app_bearer_token, consumer_secret FROM platform_credentials
WHERE workspace_id = $1 AND platform = $2
`

type GetPlatformCredentialParams struct {
	WorkspaceID string `json:"workspace_id"`
	Platform    string `json:"platform"`
}

func (q *Queries) GetPlatformCredential(ctx context.Context, arg GetPlatformCredentialParams) (PlatformCredential, error) {
	row := q.db.QueryRow(ctx, getPlatformCredential, arg.WorkspaceID, arg.Platform)
	var i PlatformCredential
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.ClientID,
		&i.ClientSecret,
		&i.CreatedAt,
		&i.WorkspaceID,
		&i.AppBearerToken,
		&i.ConsumerSecret,
	)
	return i, err
}

const listPlatformCredentialsByWorkspace = `-- name: ListPlatformCredentialsByWorkspace :many
SELECT id, platform, client_id, client_secret, created_at, workspace_id, app_bearer_token, consumer_secret FROM platform_credentials
WHERE workspace_id = $1
ORDER BY platform
`

func (q *Queries) ListPlatformCredentialsByWorkspace(ctx context.Context, workspaceID string) ([]PlatformCredential, error) {
	rows, err := q.db.Query(ctx, listPlatformCredentialsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformCredential{}
	for rows.Next() {
		var i PlatformCredential
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.ClientID,
			&i.ClientSecret,
			&i.CreatedAt,
			&i.WorkspaceID,
			&i.AppBearerToken,
			&i.ConsumerSecret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
