// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: platform_credentials.sql

package db

import (
	"context"
)

const createPlatformCredential = `-- name: CreatePlatformCredential :one
INSERT INTO platform_credentials (workspace_id, platform, client_id, client_secret)
VALUES ($1, $2, $3, $4)
ON CONFLICT (workspace_id, platform) DO UPDATE
SET client_id = EXCLUDED.client_id, client_secret = EXCLUDED.client_secret
RETURNING id, platform, client_id, client_secret, created_at, workspace_id
`

type CreatePlatformCredentialParams struct {
	WorkspaceID  string `json:"workspace_id"`
	Platform     string `json:"platform"`
	ClientID     string `json:"client_id"`
	ClientSecret string `json:"client_secret"`
}

func (q *Queries) CreatePlatformCredential(ctx context.Context, arg CreatePlatformCredentialParams) (PlatformCredential, error) {
	row := q.db.QueryRow(ctx, createPlatformCredential,
		arg.WorkspaceID,
		arg.Platform,
		arg.ClientID,
		arg.ClientSecret,
	)
	var i PlatformCredential
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.ClientID,
		&i.ClientSecret,
		&i.CreatedAt,
		&i.WorkspaceID,
	)
	return i, err
}

const deletePlatformCredential = `-- name: DeletePlatformCredential :exec
DELETE FROM platform_credentials
WHERE workspace_id = $1 AND platform = $2
`

type DeletePlatformCredentialParams struct {
	WorkspaceID string `json:"workspace_id"`
	Platform    string `json:"platform"`
}

func (q *Queries) DeletePlatformCredential(ctx context.Context, arg DeletePlatformCredentialParams) error {
	_, err := q.db.Exec(ctx, deletePlatformCredential, arg.WorkspaceID, arg.Platform)
	return err
}

const getPlatformCredential = `-- name: GetPlatformCredential :one
SELECT id, platform, client_id, client_secret, created_at, workspace_id FROM platform_credentials
WHERE workspace_id = $1 AND platform = $2
`

type GetPlatformCredentialParams struct {
	WorkspaceID string `json:"workspace_id"`
	Platform    string `json:"platform"`
}

func (q *Queries) GetPlatformCredential(ctx context.Context, arg GetPlatformCredentialParams) (PlatformCredential, error) {
	row := q.db.QueryRow(ctx, getPlatformCredential, arg.WorkspaceID, arg.Platform)
	var i PlatformCredential
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.ClientID,
		&i.ClientSecret,
		&i.CreatedAt,
		&i.WorkspaceID,
	)
	return i, err
}

const listPlatformCredentialsByWorkspace = `-- name: ListPlatformCredentialsByWorkspace :many
SELECT id, platform, client_id, client_secret, created_at, workspace_id FROM platform_credentials
WHERE workspace_id = $1
ORDER BY platform
`

func (q *Queries) ListPlatformCredentialsByWorkspace(ctx context.Context, workspaceID string) ([]PlatformCredential, error) {
	rows, err := q.db.Query(ctx, listPlatformCredentialsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformCredential{}
	for rows.Next() {
		var i PlatformCredential
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.ClientID,
			&i.ClientSecret,
			&i.CreatedAt,
			&i.WorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
