// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: post_analytics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPostAnalytics = `-- name: GetPostAnalytics :one
SELECT id, social_post_result_id, views, likes, comments, shares, reach, impressions, engagement_rate, raw_data, fetched_at FROM post_analytics WHERE social_post_result_id = $1
`

func (q *Queries) GetPostAnalytics(ctx context.Context, socialPostResultID string) (PostAnalytic, error) {
	row := q.db.QueryRow(ctx, getPostAnalytics, socialPostResultID)
	var i PostAnalytic
	err := row.Scan(
		&i.ID,
		&i.SocialPostResultID,
		&i.Views,
		&i.Likes,
		&i.Comments,
		&i.Shares,
		&i.Reach,
		&i.Impressions,
		&i.EngagementRate,
		&i.RawData,
		&i.FetchedAt,
	)
	return i, err
}

const upsertPostAnalytics = `-- name: UpsertPostAnalytics :one
INSERT INTO post_analytics (social_post_result_id, views, likes, comments, shares, reach, impressions, engagement_rate, raw_data)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (social_post_result_id) DO UPDATE
SET views = EXCLUDED.views, likes = EXCLUDED.likes, comments = EXCLUDED.comments,
    shares = EXCLUDED.shares, reach = EXCLUDED.reach, impressions = EXCLUDED.impressions,
    engagement_rate = EXCLUDED.engagement_rate, raw_data = EXCLUDED.raw_data, fetched_at = NOW()
RETURNING id, social_post_result_id, views, likes, comments, shares, reach, impressions, engagement_rate, raw_data, fetched_at
`

type UpsertPostAnalyticsParams struct {
	SocialPostResultID string         `json:"social_post_result_id"`
	Views              pgtype.Int8    `json:"views"`
	Likes              pgtype.Int8    `json:"likes"`
	Comments           pgtype.Int8    `json:"comments"`
	Shares             pgtype.Int8    `json:"shares"`
	Reach              pgtype.Int8    `json:"reach"`
	Impressions        pgtype.Int8    `json:"impressions"`
	EngagementRate     pgtype.Numeric `json:"engagement_rate"`
	RawData            []byte         `json:"raw_data"`
}

func (q *Queries) UpsertPostAnalytics(ctx context.Context, arg UpsertPostAnalyticsParams) (PostAnalytic, error) {
	row := q.db.QueryRow(ctx, upsertPostAnalytics,
		arg.SocialPostResultID,
		arg.Views,
		arg.Likes,
		arg.Comments,
		arg.Shares,
		arg.Reach,
		arg.Impressions,
		arg.EngagementRate,
		arg.RawData,
	)
	var i PostAnalytic
	err := row.Scan(
		&i.ID,
		&i.SocialPostResultID,
		&i.Views,
		&i.Likes,
		&i.Comments,
		&i.Shares,
		&i.Reach,
		&i.Impressions,
		&i.EngagementRate,
		&i.RawData,
		&i.FetchedAt,
	)
	return i, err
}
