// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: post_analytics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAnalyticsByPlatformByWorkspace = `-- name: GetAnalyticsByPlatformByWorkspace :many
SELECT
  sa.platform::TEXT                                                          AS platform,
  COUNT(DISTINCT sp.id)::BIGINT                                              AS posts,
  COUNT(DISTINCT sa.id)::BIGINT                                              AS accounts,
  COALESCE(SUM(pa.impressions), 0)::BIGINT                                   AS impressions,
  COALESCE(SUM(pa.reach), 0)::BIGINT                                         AS reach,
  COALESCE(SUM(pa.likes), 0)::BIGINT                                         AS likes,
  COALESCE(SUM(pa.comments), 0)::BIGINT                                      AS comments,
  COALESCE(SUM(pa.shares), 0)::BIGINT                                        AS shares,
  COALESCE(SUM(pa.saves), 0)::BIGINT                                         AS saves,
  COALESCE(SUM(pa.clicks), 0)::BIGINT                                        AS clicks,
  COALESCE(SUM(pa.video_views), 0)::BIGINT                                   AS video_views
FROM social_posts sp
JOIN social_post_results spr ON spr.post_id = sp.id
JOIN social_accounts sa      ON sa.id = spr.social_account_id
LEFT JOIN post_analytics pa  ON pa.social_post_result_id = spr.id
WHERE sp.workspace_id = $1
  AND sp.created_at >= $2
  AND sp.created_at <  $3
  AND ($4::text = '' OR sa.platform = $4)
  AND ($5::text = '' OR sp.status   = $5)
GROUP BY sa.platform
ORDER BY sa.platform ASC
`

type GetAnalyticsByPlatformByWorkspaceParams struct {
	WorkspaceID string             `json:"workspace_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
	Column4     string             `json:"column_4"`
	Column5     string             `json:"column_5"`
}

type GetAnalyticsByPlatformByWorkspaceRow struct {
	Platform    string `json:"platform"`
	Posts       int64  `json:"posts"`
	Accounts    int64  `json:"accounts"`
	Impressions int64  `json:"impressions"`
	Reach       int64  `json:"reach"`
	Likes       int64  `json:"likes"`
	Comments    int64  `json:"comments"`
	Shares      int64  `json:"shares"`
	Saves       int64  `json:"saves"`
	Clicks      int64  `json:"clicks"`
	VideoViews  int64  `json:"video_views"`
}

func (q *Queries) GetAnalyticsByPlatformByWorkspace(ctx context.Context, arg GetAnalyticsByPlatformByWorkspaceParams) ([]GetAnalyticsByPlatformByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, getAnalyticsByPlatformByWorkspace,
		arg.WorkspaceID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Column4,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAnalyticsByPlatformByWorkspaceRow{}
	for rows.Next() {
		var i GetAnalyticsByPlatformByWorkspaceRow
		if err := rows.Scan(
			&i.Platform,
			&i.Posts,
			&i.Accounts,
			&i.Impressions,
			&i.Reach,
			&i.Likes,
			&i.Comments,
			&i.Shares,
			&i.Saves,
			&i.Clicks,
			&i.VideoViews,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnalyticsSummaryByWorkspace = `-- name: GetAnalyticsSummaryByWorkspace :one
SELECT
  COUNT(DISTINCT sp.id)::BIGINT                                              AS total_posts,
  COUNT(DISTINCT sp.id) FILTER (WHERE sp.status = 'published')::BIGINT       AS published_posts,
  COUNT(DISTINCT sp.id) FILTER (WHERE sp.status = 'failed')::BIGINT          AS failed_posts,
  COUNT(DISTINCT sp.id) FILTER (WHERE sp.status = 'scheduled')::BIGINT       AS scheduled_posts,
  COALESCE(SUM(pa.impressions), 0)::BIGINT                                   AS impressions,
  COALESCE(SUM(pa.reach), 0)::BIGINT                                         AS reach,
  COALESCE(SUM(pa.likes), 0)::BIGINT                                         AS likes,
  COALESCE(SUM(pa.comments), 0)::BIGINT                                      AS comments,
  COALESCE(SUM(pa.shares), 0)::BIGINT                                        AS shares,
  COALESCE(SUM(pa.saves), 0)::BIGINT                                         AS saves,
  COALESCE(SUM(pa.clicks), 0)::BIGINT                                        AS clicks,
  COALESCE(SUM(pa.video_views), 0)::BIGINT                                   AS video_views
FROM social_posts sp
LEFT JOIN social_post_results spr ON spr.post_id = sp.id
LEFT JOIN social_accounts sa      ON sa.id = spr.social_account_id
LEFT JOIN post_analytics pa       ON pa.social_post_result_id = spr.id
WHERE sp.workspace_id = $1
  AND sp.created_at >= $2
  AND sp.created_at <  $3
  AND ($4::text = '' OR sa.platform = $4)
  AND ($5::text = '' OR sp.status   = $5)
`

type GetAnalyticsSummaryByWorkspaceParams struct {
	WorkspaceID string             `json:"workspace_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
	Column4     string             `json:"column_4"`
	Column5     string             `json:"column_5"`
}

type GetAnalyticsSummaryByWorkspaceRow struct {
	TotalPosts     int64 `json:"total_posts"`
	PublishedPosts int64 `json:"published_posts"`
	FailedPosts    int64 `json:"failed_posts"`
	ScheduledPosts int64 `json:"scheduled_posts"`
	Impressions    int64 `json:"impressions"`
	Reach          int64 `json:"reach"`
	Likes          int64 `json:"likes"`
	Comments       int64 `json:"comments"`
	Shares         int64 `json:"shares"`
	Saves          int64 `json:"saves"`
	Clicks         int64 `json:"clicks"`
	VideoViews     int64 `json:"video_views"`
}

func (q *Queries) GetAnalyticsSummaryByWorkspace(ctx context.Context, arg GetAnalyticsSummaryByWorkspaceParams) (GetAnalyticsSummaryByWorkspaceRow, error) {
	row := q.db.QueryRow(ctx, getAnalyticsSummaryByWorkspace,
		arg.WorkspaceID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Column4,
		arg.Column5,
	)
	var i GetAnalyticsSummaryByWorkspaceRow
	err := row.Scan(
		&i.TotalPosts,
		&i.PublishedPosts,
		&i.FailedPosts,
		&i.ScheduledPosts,
		&i.Impressions,
		&i.Reach,
		&i.Likes,
		&i.Comments,
		&i.Shares,
		&i.Saves,
		&i.Clicks,
		&i.VideoViews,
	)
	return i, err
}

const getAnalyticsTrendByWorkspace = `-- name: GetAnalyticsTrendByWorkspace :many
SELECT
  date_trunc('day', sp.created_at)::TIMESTAMPTZ                              AS day,
  COUNT(DISTINCT sp.id)::BIGINT                                              AS posts,
  COALESCE(SUM(pa.impressions), 0)::BIGINT                                   AS impressions,
  COALESCE(SUM(pa.likes), 0)::BIGINT                                         AS likes,
  COALESCE(SUM(pa.comments), 0)::BIGINT                                      AS comments,
  COALESCE(SUM(pa.shares), 0)::BIGINT                                        AS shares
FROM social_posts sp
LEFT JOIN social_post_results spr ON spr.post_id = sp.id
LEFT JOIN social_accounts sa      ON sa.id = spr.social_account_id
LEFT JOIN post_analytics pa       ON pa.social_post_result_id = spr.id
WHERE sp.workspace_id = $1
  AND sp.created_at >= $2
  AND sp.created_at <  $3
  AND ($4::text = '' OR sa.platform = $4)
  AND ($5::text = '' OR sp.status   = $5)
GROUP BY day
ORDER BY day ASC
`

type GetAnalyticsTrendByWorkspaceParams struct {
	WorkspaceID string             `json:"workspace_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
	Column4     string             `json:"column_4"`
	Column5     string             `json:"column_5"`
}

type GetAnalyticsTrendByWorkspaceRow struct {
	Day         pgtype.Timestamptz `json:"day"`
	Posts       int64              `json:"posts"`
	Impressions int64              `json:"impressions"`
	Likes       int64              `json:"likes"`
	Comments    int64              `json:"comments"`
	Shares      int64              `json:"shares"`
}

func (q *Queries) GetAnalyticsTrendByWorkspace(ctx context.Context, arg GetAnalyticsTrendByWorkspaceParams) ([]GetAnalyticsTrendByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, getAnalyticsTrendByWorkspace,
		arg.WorkspaceID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Column4,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAnalyticsTrendByWorkspaceRow{}
	for rows.Next() {
		var i GetAnalyticsTrendByWorkspaceRow
		if err := rows.Scan(
			&i.Day,
			&i.Posts,
			&i.Impressions,
			&i.Likes,
			&i.Comments,
			&i.Shares,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDuePostAnalyticsRefresh = `-- name: GetDuePostAnalyticsRefresh :many
SELECT
  spr.id                  AS social_post_result_id,
  spr.social_account_id,
  spr.external_id,
  sa.platform,
  sa.access_token,
  sa.refresh_token,
  sa.token_expires_at
FROM social_post_results spr
JOIN social_accounts sa     ON sa.id = spr.social_account_id
LEFT JOIN post_analytics pa ON pa.social_post_result_id = spr.id
WHERE spr.status = 'published'
  AND spr.external_id IS NOT NULL
  AND spr.published_at IS NOT NULL
  AND spr.published_at > NOW() - INTERVAL '90 days'
  AND sa.disconnected_at IS NULL
  AND (
    pa.fetched_at IS NULL
    OR (spr.published_at >  NOW() - INTERVAL '24 hours' AND pa.fetched_at < NOW() - INTERVAL '1 hour')
    OR (spr.published_at <= NOW() - INTERVAL '24 hours' AND spr.published_at > NOW() - INTERVAL '7 days' AND pa.fetched_at < NOW() - INTERVAL '6 hours')
    OR (spr.published_at <= NOW() - INTERVAL '7 days'  AND pa.fetched_at < NOW() - INTERVAL '24 hours')
  )
ORDER BY pa.fetched_at NULLS FIRST
LIMIT 200
`

type GetDuePostAnalyticsRefreshRow struct {
	SocialPostResultID string             `json:"social_post_result_id"`
	SocialAccountID    string             `json:"social_account_id"`
	ExternalID         pgtype.Text        `json:"external_id"`
	Platform           string             `json:"platform"`
	AccessToken        string             `json:"access_token"`
	RefreshToken       pgtype.Text        `json:"refresh_token"`
	TokenExpiresAt     pgtype.Timestamptz `json:"token_expires_at"`
}

func (q *Queries) GetDuePostAnalyticsRefresh(ctx context.Context) ([]GetDuePostAnalyticsRefreshRow, error) {
	rows, err := q.db.Query(ctx, getDuePostAnalyticsRefresh)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDuePostAnalyticsRefreshRow{}
	for rows.Next() {
		var i GetDuePostAnalyticsRefreshRow
		if err := rows.Scan(
			&i.SocialPostResultID,
			&i.SocialAccountID,
			&i.ExternalID,
			&i.Platform,
			&i.AccessToken,
			&i.RefreshToken,
			&i.TokenExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchPostAnalyticsFetchedAt = `-- name: TouchPostAnalyticsFetchedAt :exec
INSERT INTO post_analytics (social_post_result_id, fetched_at, consecutive_failures, last_failure_reason)
VALUES ($1, NOW(), 1, $2)
ON CONFLICT (social_post_result_id) DO UPDATE
SET fetched_at           = NOW(),
    consecutive_failures = post_analytics.consecutive_failures + 1,
    last_failure_reason  = $2
`

type TouchPostAnalyticsFetchedAtParams struct {
	SocialPostResultID string `json:"social_post_result_id"`
	LastFailureReason  string `json:"last_failure_reason"`
}

func (q *Queries) TouchPostAnalyticsFetchedAt(ctx context.Context, arg TouchPostAnalyticsFetchedAtParams) error {
	_, err := q.db.Exec(ctx, touchPostAnalyticsFetchedAt, arg.SocialPostResultID, arg.LastFailureReason)
	return err
}

const getPostAnalytics = `-- name: GetPostAnalytics :one
SELECT id, social_post_result_id, views, likes, comments, shares, reach, impressions, engagement_rate, raw_data, fetched_at, saves, clicks, video_views, platform_specific, consecutive_failures, last_failure_reason FROM post_analytics WHERE social_post_result_id = $1
`

func (q *Queries) GetPostAnalytics(ctx context.Context, socialPostResultID string) (PostAnalytic, error) {
	row := q.db.QueryRow(ctx, getPostAnalytics, socialPostResultID)
	var i PostAnalytic
	err := row.Scan(
		&i.ID,
		&i.SocialPostResultID,
		&i.Views,
		&i.Likes,
		&i.Comments,
		&i.Shares,
		&i.Reach,
		&i.Impressions,
		&i.EngagementRate,
		&i.RawData,
		&i.FetchedAt,
		&i.Saves,
		&i.Clicks,
		&i.VideoViews,
		&i.PlatformSpecific,
		&i.ConsecutiveFailures,
		&i.LastFailureReason,
	)
	return i, err
}

const upsertPostAnalytics = `-- name: UpsertPostAnalytics :one
INSERT INTO post_analytics (
  social_post_result_id, views, likes, comments, shares, reach, impressions,
  saves, clicks, video_views, platform_specific, engagement_rate, raw_data
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
ON CONFLICT (social_post_result_id) DO UPDATE
SET views                = EXCLUDED.views,
    likes                = EXCLUDED.likes,
    comments             = EXCLUDED.comments,
    shares               = EXCLUDED.shares,
    reach                = EXCLUDED.reach,
    impressions          = EXCLUDED.impressions,
    saves                = EXCLUDED.saves,
    clicks               = EXCLUDED.clicks,
    video_views          = EXCLUDED.video_views,
    platform_specific    = EXCLUDED.platform_specific,
    engagement_rate      = EXCLUDED.engagement_rate,
    raw_data             = EXCLUDED.raw_data,
    fetched_at           = NOW(),
    consecutive_failures = 0,
    last_failure_reason  = NULL
RETURNING id, social_post_result_id, views, likes, comments, shares, reach, impressions, engagement_rate, raw_data, fetched_at, saves, clicks, video_views, platform_specific, consecutive_failures, last_failure_reason
`

type UpsertPostAnalyticsParams struct {
	SocialPostResultID string         `json:"social_post_result_id"`
	Views              pgtype.Int8    `json:"views"`
	Likes              pgtype.Int8    `json:"likes"`
	Comments           pgtype.Int8    `json:"comments"`
	Shares             pgtype.Int8    `json:"shares"`
	Reach              pgtype.Int8    `json:"reach"`
	Impressions        pgtype.Int8    `json:"impressions"`
	Saves              pgtype.Int8    `json:"saves"`
	Clicks             pgtype.Int8    `json:"clicks"`
	VideoViews         pgtype.Int8    `json:"video_views"`
	PlatformSpecific   []byte         `json:"platform_specific"`
	EngagementRate     pgtype.Numeric `json:"engagement_rate"`
	RawData            []byte         `json:"raw_data"`
}

func (q *Queries) UpsertPostAnalytics(ctx context.Context, arg UpsertPostAnalyticsParams) (PostAnalytic, error) {
	row := q.db.QueryRow(ctx, upsertPostAnalytics,
		arg.SocialPostResultID,
		arg.Views,
		arg.Likes,
		arg.Comments,
		arg.Shares,
		arg.Reach,
		arg.Impressions,
		arg.Saves,
		arg.Clicks,
		arg.VideoViews,
		arg.PlatformSpecific,
		arg.EngagementRate,
		arg.RawData,
	)
	var i PostAnalytic
	err := row.Scan(
		&i.ID,
		&i.SocialPostResultID,
		&i.Views,
		&i.Likes,
		&i.Comments,
		&i.Shares,
		&i.Reach,
		&i.Impressions,
		&i.EngagementRate,
		&i.RawData,
		&i.FetchedAt,
		&i.Saves,
		&i.Clicks,
		&i.VideoViews,
		&i.PlatformSpecific,
		&i.ConsecutiveFailures,
		&i.LastFailureReason,
	)
	return i, err
}
