// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profiles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (workspace_id, name)
VALUES ($1, $2)
RETURNING id, name, created_at, updated_at, branding_logo_url, branding_display_name, branding_primary_color, workspace_id
`

type CreateProfileParams struct {
	WorkspaceID string `json:"workspace_id"`
	Name        string `json:"name"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, createProfile, arg.WorkspaceID, arg.Name)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BrandingLogoUrl,
		&i.BrandingDisplayName,
		&i.BrandingPrimaryColor,
		&i.WorkspaceID,
	)
	return i, err
}

const deleteProfile = `-- name: DeleteProfile :exec
DELETE FROM profiles WHERE id = $1
`

func (q *Queries) DeleteProfile(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteProfile, id)
	return err
}

const getProfile = `-- name: GetProfile :one
SELECT id, name, created_at, updated_at, branding_logo_url, branding_display_name, branding_primary_color, workspace_id FROM profiles WHERE id = $1
`

func (q *Queries) GetProfile(ctx context.Context, id string) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfile, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BrandingLogoUrl,
		&i.BrandingDisplayName,
		&i.BrandingPrimaryColor,
		&i.WorkspaceID,
	)
	return i, err
}

const getProfileByIDAndWorkspaceOwner = `-- name: GetProfileByIDAndWorkspaceOwner :one
SELECT p.id, p.name, p.created_at, p.updated_at, p.branding_logo_url, p.branding_display_name, p.branding_primary_color, p.workspace_id FROM profiles p
JOIN workspaces w ON w.id = p.workspace_id
WHERE p.id = $1 AND w.user_id = $2
`

type GetProfileByIDAndWorkspaceOwnerParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

// Single-query ownership check: joins profiles -> workspaces to verify
// the requesting user owns the workspace that contains this profile.
func (q *Queries) GetProfileByIDAndWorkspaceOwner(ctx context.Context, arg GetProfileByIDAndWorkspaceOwnerParams) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByIDAndWorkspaceOwner, arg.ID, arg.UserID)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BrandingLogoUrl,
		&i.BrandingDisplayName,
		&i.BrandingPrimaryColor,
		&i.WorkspaceID,
	)
	return i, err
}

const listProfilesByWorkspace = `-- name: ListProfilesByWorkspace :many
SELECT id, name, created_at, updated_at, branding_logo_url, branding_display_name, branding_primary_color, workspace_id FROM profiles WHERE workspace_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListProfilesByWorkspace(ctx context.Context, workspaceID string) ([]Profile, error) {
	rows, err := q.db.Query(ctx, listProfilesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Profile{}
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BrandingLogoUrl,
			&i.BrandingDisplayName,
			&i.BrandingPrimaryColor,
			&i.WorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE profiles SET name = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, name, created_at, updated_at, branding_logo_url, branding_display_name, branding_primary_color, workspace_id
`

type UpdateProfileParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, updateProfile, arg.ID, arg.Name)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BrandingLogoUrl,
		&i.BrandingDisplayName,
		&i.BrandingPrimaryColor,
		&i.WorkspaceID,
	)
	return i, err
}

const updateProfileBranding = `-- name: UpdateProfileBranding :one
UPDATE profiles
SET branding_logo_url      = COALESCE($2::TEXT,      branding_logo_url),
    branding_display_name  = COALESCE($3::TEXT,  branding_display_name),
    branding_primary_color = COALESCE($4::TEXT, branding_primary_color),
    updated_at             = NOW()
WHERE id = $1
RETURNING id, name, created_at, updated_at, branding_logo_url, branding_display_name, branding_primary_color, workspace_id
`

type UpdateProfileBrandingParams struct {
	ID           string      `json:"id"`
	LogoUrl      pgtype.Text `json:"logo_url"`
	DisplayName  pgtype.Text `json:"display_name"`
	PrimaryColor pgtype.Text `json:"primary_color"`
}

func (q *Queries) UpdateProfileBranding(ctx context.Context, arg UpdateProfileBrandingParams) (Profile, error) {
	row := q.db.QueryRow(ctx, updateProfileBranding,
		arg.ID,
		arg.LogoUrl,
		arg.DisplayName,
		arg.PrimaryColor,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BrandingLogoUrl,
		&i.BrandingDisplayName,
		&i.BrandingPrimaryColor,
		&i.WorkspaceID,
	)
	return i, err
}
