// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: publishing_pull_objects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const abandonPublishingPullObjectUsage = `-- name: AbandonPublishingPullObjectUsage :exec
UPDATE publishing_pull_object_usages
SET post_status = 'failed',
    cleanup_after_at = NOW(),
    retention_reason = 'upload_failed',
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) AbandonPublishingPullObjectUsage(ctx context.Context, usageID string) error {
	_, err := q.db.Exec(ctx, abandonPublishingPullObjectUsage, usageID)
	return err
}

const activatePublishingPullObjectUsage = `-- name: ActivatePublishingPullObjectUsage :one
UPDATE publishing_pull_object_usages
SET post_status = 'publishing',
    cleanup_after_at = NULL,
    retention_reason = 'active_post',
    updated_at = NOW()
WHERE id = $1
  AND post_status = 'upload_pending'
RETURNING id
`

func (q *Queries) ActivatePublishingPullObjectUsage(ctx context.Context, usageID string) (string, error) {
	row := q.db.QueryRow(ctx, activatePublishingPullObjectUsage, usageID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const hardDeletePublishingPullObject = `-- name: HardDeletePublishingPullObject :exec
DELETE FROM publishing_pull_objects
WHERE object_key = $1
  AND cleanup_state = 'deleting'
`

func (q *Queries) HardDeletePublishingPullObject(ctx context.Context, objectKey string) error {
	_, err := q.db.Exec(ctx, hardDeletePublishingPullObject, objectKey)
	return err
}

const lockPublishingPullObjectCandidates = `-- name: LockPublishingPullObjectCandidates :many
SELECT candidate.object_key, candidate.content_type, candidate.size_bytes, candidate.cleanup_state, candidate.created_at, candidate.updated_at
FROM publishing_pull_objects candidate
WHERE candidate.cleanup_state IN ('active', 'deleting')
  AND NOT EXISTS (
    SELECT 1
    FROM publishing_pull_object_usages usage
    WHERE usage.object_key = candidate.object_key
      AND (
        usage.cleanup_after_at IS NULL
        OR usage.cleanup_after_at > NOW()
      )
  )
ORDER BY candidate.created_at ASC, candidate.object_key ASC
LIMIT $1
FOR UPDATE OF candidate SKIP LOCKED
`

func (q *Queries) LockPublishingPullObjectCandidates(ctx context.Context, batchSize int32) ([]PublishingPullObject, error) {
	rows, err := q.db.Query(ctx, lockPublishingPullObjectCandidates, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PublishingPullObject{}
	for rows.Next() {
		var i PublishingPullObject
		if err := rows.Scan(
			&i.ObjectKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.CleanupState,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPublishingPullObjectDeleting = `-- name: MarkPublishingPullObjectDeleting :one
UPDATE publishing_pull_objects
SET cleanup_state = 'deleting',
    updated_at = NOW()
WHERE object_key = $1
  AND cleanup_state IN ('active', 'deleting')
RETURNING object_key, content_type, size_bytes, cleanup_state, created_at, updated_at
`

func (q *Queries) MarkPublishingPullObjectDeleting(ctx context.Context, objectKey string) (PublishingPullObject, error) {
	row := q.db.QueryRow(ctx, markPublishingPullObjectDeleting, objectKey)
	var i PublishingPullObject
	err := row.Scan(
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.CleanupState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const publishingPullObjectHasActiveUsage = `-- name: PublishingPullObjectHasActiveUsage :one
SELECT EXISTS (
  SELECT 1
  FROM publishing_pull_object_usages usage
  WHERE usage.object_key = $1
    AND (
      usage.cleanup_after_at IS NULL
      OR usage.cleanup_after_at > NOW()
    )
)
`

func (q *Queries) PublishingPullObjectHasActiveUsage(ctx context.Context, objectKey string) (bool, error) {
	row := q.db.QueryRow(ctx, publishingPullObjectHasActiveUsage, objectKey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const releasePublishingPullObjectClaim = `-- name: ReleasePublishingPullObjectClaim :exec
UPDATE publishing_pull_objects
SET cleanup_state = 'active',
    updated_at = NOW()
WHERE object_key = $1
  AND cleanup_state = 'deleting'
`

func (q *Queries) ReleasePublishingPullObjectClaim(ctx context.Context, objectKey string) error {
	_, err := q.db.Exec(ctx, releasePublishingPullObjectClaim, objectKey)
	return err
}

const reservePublishingPullObjectUsage = `-- name: ReservePublishingPullObjectUsage :one
WITH reserved_object AS (
  INSERT INTO publishing_pull_objects (
    object_key,
    content_type,
    size_bytes,
    cleanup_state
  ) VALUES (
    $3,
    $4,
    $5,
    'active'
  )
  ON CONFLICT (object_key) DO UPDATE
  SET content_type = EXCLUDED.content_type,
      size_bytes = EXCLUDED.size_bytes,
      updated_at = NOW()
  WHERE publishing_pull_objects.cleanup_state = 'active'
  RETURNING object_key
)
INSERT INTO publishing_pull_object_usages (
  object_key,
  workspace_id,
  post_id,
  post_status,
  cleanup_after_at,
  retention_reason
)
SELECT
  reserved_object.object_key,
  $1,
  $2,
  'upload_pending',
  NOW() + INTERVAL '15 minutes',
  'upload_pending'
FROM reserved_object
RETURNING id
`

type ReservePublishingPullObjectUsageParams struct {
	WorkspaceID string `json:"workspace_id"`
	PostID      string `json:"post_id"`
	ObjectKey   string `json:"object_key"`
	ContentType string `json:"content_type"`
	SizeBytes   int64  `json:"size_bytes"`
}

func (q *Queries) ReservePublishingPullObjectUsage(ctx context.Context, arg ReservePublishingPullObjectUsageParams) (string, error) {
	row := q.db.QueryRow(ctx, reservePublishingPullObjectUsage,
		arg.WorkspaceID,
		arg.PostID,
		arg.ObjectKey,
		arg.ContentType,
		arg.SizeBytes,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const updatePublishingPullObjectUsagesForPost = `-- name: UpdatePublishingPullObjectUsagesForPost :exec
UPDATE publishing_pull_object_usages
SET post_status = $1,
    cleanup_after_at = $2,
    retention_reason = $3,
    updated_at = NOW()
WHERE post_id = $4
`

type UpdatePublishingPullObjectUsagesForPostParams struct {
	PostStatus      string             `json:"post_status"`
	CleanupAfterAt  pgtype.Timestamptz `json:"cleanup_after_at"`
	RetentionReason string             `json:"retention_reason"`
	PostID          string             `json:"post_id"`
}

func (q *Queries) UpdatePublishingPullObjectUsagesForPost(ctx context.Context, arg UpdatePublishingPullObjectUsagesForPostParams) error {
	_, err := q.db.Exec(ctx, updatePublishingPullObjectUsagesForPost,
		arg.PostStatus,
		arg.CleanupAfterAt,
		arg.RetentionReason,
		arg.PostID,
	)
	return err
}
