// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: review.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachReviewSessionToJob = `-- name: AttachReviewSessionToJob :one
UPDATE review_jobs
SET review_session_token_id = $3,
    updated_at = NOW()
WHERE id = $1 AND workspace_id = $2
RETURNING id, review_kit_id, workspace_id, platform, status, started_at, completed_at, failed_at, failure_reason, agent_version, review_session_token_id, video_file_id, artifacts_json, created_at, updated_at
`

type AttachReviewSessionToJobParams struct {
	ID                   string      `json:"id"`
	WorkspaceID          string      `json:"workspace_id"`
	ReviewSessionTokenID pgtype.Text `json:"review_session_token_id"`
}

func (q *Queries) AttachReviewSessionToJob(ctx context.Context, arg AttachReviewSessionToJobParams) (ReviewJob, error) {
	row := q.db.QueryRow(ctx, attachReviewSessionToJob, arg.ID, arg.WorkspaceID, arg.ReviewSessionTokenID)
	var i ReviewJob
	err := row.Scan(
		&i.ID,
		&i.ReviewKitID,
		&i.WorkspaceID,
		&i.Platform,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.FailureReason,
		&i.AgentVersion,
		&i.ReviewSessionTokenID,
		&i.VideoFileID,
		&i.ArtifactsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimReviewSession = `-- name: ClaimReviewSession :one
UPDATE review_sessions
SET claimed_at = COALESCE(claimed_at, NOW())
WHERE id = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
RETURNING id, review_job_id, review_kit_id, workspace_id, platform, review_domain, token_hash, expires_at, claimed_at, revoked_at, created_at
`

func (q *Queries) ClaimReviewSession(ctx context.Context, id string) (ReviewSession, error) {
	row := q.db.QueryRow(ctx, claimReviewSession, id)
	var i ReviewSession
	err := row.Scan(
		&i.ID,
		&i.ReviewJobID,
		&i.ReviewKitID,
		&i.WorkspaceID,
		&i.Platform,
		&i.ReviewDomain,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ClaimedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const completeReviewJob = `-- name: CompleteReviewJob :one
UPDATE review_jobs
SET status = 'completed',
    completed_at = NOW(),
    video_file_id = $3,
    artifacts_json = $4,
    updated_at = NOW()
WHERE id = $1 AND workspace_id = $2
RETURNING id, review_kit_id, workspace_id, platform, status, started_at, completed_at, failed_at, failure_reason, agent_version, review_session_token_id, video_file_id, artifacts_json, created_at, updated_at
`

type CompleteReviewJobParams struct {
	ID            string      `json:"id"`
	WorkspaceID   string      `json:"workspace_id"`
	VideoFileID   pgtype.Text `json:"video_file_id"`
	ArtifactsJson []byte      `json:"artifacts_json"`
}

func (q *Queries) CompleteReviewJob(ctx context.Context, arg CompleteReviewJobParams) (ReviewJob, error) {
	row := q.db.QueryRow(ctx, completeReviewJob,
		arg.ID,
		arg.WorkspaceID,
		arg.VideoFileID,
		arg.ArtifactsJson,
	)
	var i ReviewJob
	err := row.Scan(
		&i.ID,
		&i.ReviewKitID,
		&i.WorkspaceID,
		&i.Platform,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.FailureReason,
		&i.AgentVersion,
		&i.ReviewSessionTokenID,
		&i.VideoFileID,
		&i.ArtifactsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReviewDomain = `-- name: CreateReviewDomain :one
INSERT INTO review_domains (
  workspace_id, domain, provider, status, verification_token, cname_target, tls_status
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, workspace_id, domain, provider, status, verification_token, cname_target, dns_verified_at, tls_status, tls_issued_at, created_at, updated_at
`

type CreateReviewDomainParams struct {
	WorkspaceID       string      `json:"workspace_id"`
	Domain            string      `json:"domain"`
	Provider          pgtype.Text `json:"provider"`
	Status            string      `json:"status"`
	VerificationToken string      `json:"verification_token"`
	CnameTarget       string      `json:"cname_target"`
	TlsStatus         string      `json:"tls_status"`
}

func (q *Queries) CreateReviewDomain(ctx context.Context, arg CreateReviewDomainParams) (ReviewDomain, error) {
	row := q.db.QueryRow(ctx, createReviewDomain,
		arg.WorkspaceID,
		arg.Domain,
		arg.Provider,
		arg.Status,
		arg.VerificationToken,
		arg.CnameTarget,
		arg.TlsStatus,
	)
	var i ReviewDomain
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Domain,
		&i.Provider,
		&i.Status,
		&i.VerificationToken,
		&i.CnameTarget,
		&i.DnsVerifiedAt,
		&i.TlsStatus,
		&i.TlsIssuedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReviewJob = `-- name: CreateReviewJob :one
INSERT INTO review_jobs (
  review_kit_id, workspace_id, platform, status, agent_version, review_session_token_id
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, review_kit_id, workspace_id, platform, status, started_at, completed_at, failed_at, failure_reason, agent_version, review_session_token_id, video_file_id, artifacts_json, created_at, updated_at
`

type CreateReviewJobParams struct {
	ReviewKitID          string      `json:"review_kit_id"`
	WorkspaceID          string      `json:"workspace_id"`
	Platform             string      `json:"platform"`
	Status               string      `json:"status"`
	AgentVersion         pgtype.Text `json:"agent_version"`
	ReviewSessionTokenID pgtype.Text `json:"review_session_token_id"`
}

func (q *Queries) CreateReviewJob(ctx context.Context, arg CreateReviewJobParams) (ReviewJob, error) {
	row := q.db.QueryRow(ctx, createReviewJob,
		arg.ReviewKitID,
		arg.WorkspaceID,
		arg.Platform,
		arg.Status,
		arg.AgentVersion,
		arg.ReviewSessionTokenID,
	)
	var i ReviewJob
	err := row.Scan(
		&i.ID,
		&i.ReviewKitID,
		&i.WorkspaceID,
		&i.Platform,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.FailureReason,
		&i.AgentVersion,
		&i.ReviewSessionTokenID,
		&i.VideoFileID,
		&i.ArtifactsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReviewJobEvent = `-- name: CreateReviewJobEvent :one
INSERT INTO review_job_events (
  review_job_id, event_type, message, metadata, elapsed_ms
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, review_job_id, event_type, message, metadata, elapsed_ms, created_at
`

type CreateReviewJobEventParams struct {
	ReviewJobID string      `json:"review_job_id"`
	EventType   string      `json:"event_type"`
	Message     string      `json:"message"`
	Metadata    []byte      `json:"metadata"`
	ElapsedMs   pgtype.Int8 `json:"elapsed_ms"`
}

func (q *Queries) CreateReviewJobEvent(ctx context.Context, arg CreateReviewJobEventParams) (ReviewJobEvent, error) {
	row := q.db.QueryRow(ctx, createReviewJobEvent,
		arg.ReviewJobID,
		arg.EventType,
		arg.Message,
		arg.Metadata,
		arg.ElapsedMs,
	)
	var i ReviewJobEvent
	err := row.Scan(
		&i.ID,
		&i.ReviewJobID,
		&i.EventType,
		&i.Message,
		&i.Metadata,
		&i.ElapsedMs,
		&i.CreatedAt,
	)
	return i, err
}

const createReviewKit = `-- name: CreateReviewKit :one
INSERT INTO review_kits (
  workspace_id, platform, use_case, review_domain_id, brand_snapshot, required_scopes, status
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, workspace_id, platform, use_case, review_domain_id, brand_snapshot, required_scopes, status, created_at, updated_at
`

type CreateReviewKitParams struct {
	WorkspaceID    string   `json:"workspace_id"`
	Platform       string   `json:"platform"`
	UseCase        string   `json:"use_case"`
	ReviewDomainID string   `json:"review_domain_id"`
	BrandSnapshot  []byte   `json:"brand_snapshot"`
	RequiredScopes []string `json:"required_scopes"`
	Status         string   `json:"status"`
}

func (q *Queries) CreateReviewKit(ctx context.Context, arg CreateReviewKitParams) (ReviewKit, error) {
	row := q.db.QueryRow(ctx, createReviewKit,
		arg.WorkspaceID,
		arg.Platform,
		arg.UseCase,
		arg.ReviewDomainID,
		arg.BrandSnapshot,
		arg.RequiredScopes,
		arg.Status,
	)
	var i ReviewKit
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Platform,
		&i.UseCase,
		&i.ReviewDomainID,
		&i.BrandSnapshot,
		&i.RequiredScopes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReviewSession = `-- name: CreateReviewSession :one
INSERT INTO review_sessions (
  review_job_id, review_kit_id, workspace_id, platform, review_domain, token_hash, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, review_job_id, review_kit_id, workspace_id, platform, review_domain, token_hash, expires_at, claimed_at, revoked_at, created_at
`

type CreateReviewSessionParams struct {
	ReviewJobID  string             `json:"review_job_id"`
	ReviewKitID  string             `json:"review_kit_id"`
	WorkspaceID  string             `json:"workspace_id"`
	Platform     string             `json:"platform"`
	ReviewDomain string             `json:"review_domain"`
	TokenHash    string             `json:"token_hash"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateReviewSession(ctx context.Context, arg CreateReviewSessionParams) (ReviewSession, error) {
	row := q.db.QueryRow(ctx, createReviewSession,
		arg.ReviewJobID,
		arg.ReviewKitID,
		arg.WorkspaceID,
		arg.Platform,
		arg.ReviewDomain,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i ReviewSession
	err := row.Scan(
		&i.ID,
		&i.ReviewJobID,
		&i.ReviewKitID,
		&i.WorkspaceID,
		&i.Platform,
		&i.ReviewDomain,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ClaimedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const failReviewJob = `-- name: FailReviewJob :one
UPDATE review_jobs
SET status = 'failed',
    failed_at = NOW(),
    failure_reason = $3,
    artifacts_json = $4,
    updated_at = NOW()
WHERE id = $1 AND workspace_id = $2
RETURNING id, review_kit_id, workspace_id, platform, status, started_at, completed_at, failed_at, failure_reason, agent_version, review_session_token_id, video_file_id, artifacts_json, created_at, updated_at
`

type FailReviewJobParams struct {
	ID            string      `json:"id"`
	WorkspaceID   string      `json:"workspace_id"`
	FailureReason pgtype.Text `json:"failure_reason"`
	ArtifactsJson []byte      `json:"artifacts_json"`
}

func (q *Queries) FailReviewJob(ctx context.Context, arg FailReviewJobParams) (ReviewJob, error) {
	row := q.db.QueryRow(ctx, failReviewJob,
		arg.ID,
		arg.WorkspaceID,
		arg.FailureReason,
		arg.ArtifactsJson,
	)
	var i ReviewJob
	err := row.Scan(
		&i.ID,
		&i.ReviewKitID,
		&i.WorkspaceID,
		&i.Platform,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.FailureReason,
		&i.AgentVersion,
		&i.ReviewSessionTokenID,
		&i.VideoFileID,
		&i.ArtifactsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveReviewSessionForJob = `-- name: GetActiveReviewSessionForJob :one
SELECT id, review_job_id, review_kit_id, workspace_id, platform, review_domain, token_hash, expires_at, claimed_at, revoked_at, created_at FROM review_sessions
WHERE review_job_id = $1
  AND workspace_id = $2
  AND revoked_at IS NULL
  AND expires_at > NOW()
ORDER BY created_at DESC
LIMIT 1
`

type GetActiveReviewSessionForJobParams struct {
	ReviewJobID string `json:"review_job_id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetActiveReviewSessionForJob(ctx context.Context, arg GetActiveReviewSessionForJobParams) (ReviewSession, error) {
	row := q.db.QueryRow(ctx, getActiveReviewSessionForJob, arg.ReviewJobID, arg.WorkspaceID)
	var i ReviewSession
	err := row.Scan(
		&i.ID,
		&i.ReviewJobID,
		&i.ReviewKitID,
		&i.WorkspaceID,
		&i.Platform,
		&i.ReviewDomain,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ClaimedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getReviewDomain = `-- name: GetReviewDomain :one
SELECT id, workspace_id, domain, provider, status, verification_token, cname_target, dns_verified_at, tls_status, tls_issued_at, created_at, updated_at FROM review_domains
WHERE id = $1 AND workspace_id = $2
`

type GetReviewDomainParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetReviewDomain(ctx context.Context, arg GetReviewDomainParams) (ReviewDomain, error) {
	row := q.db.QueryRow(ctx, getReviewDomain, arg.ID, arg.WorkspaceID)
	var i ReviewDomain
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Domain,
		&i.Provider,
		&i.Status,
		&i.VerificationToken,
		&i.CnameTarget,
		&i.DnsVerifiedAt,
		&i.TlsStatus,
		&i.TlsIssuedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReviewDomainByDomain = `-- name: GetReviewDomainByDomain :one
SELECT id, workspace_id, domain, provider, status, verification_token, cname_target, dns_verified_at, tls_status, tls_issued_at, created_at, updated_at FROM review_domains
WHERE lower(domain) = lower($1)
`

func (q *Queries) GetReviewDomainByDomain(ctx context.Context, lower string) (ReviewDomain, error) {
	row := q.db.QueryRow(ctx, getReviewDomainByDomain, lower)
	var i ReviewDomain
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Domain,
		&i.Provider,
		&i.Status,
		&i.VerificationToken,
		&i.CnameTarget,
		&i.DnsVerifiedAt,
		&i.TlsStatus,
		&i.TlsIssuedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReviewJob = `-- name: GetReviewJob :one
SELECT id, review_kit_id, workspace_id, platform, status, started_at, completed_at, failed_at, failure_reason, agent_version, review_session_token_id, video_file_id, artifacts_json, created_at, updated_at FROM review_jobs
WHERE id = $1 AND workspace_id = $2
`

type GetReviewJobParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetReviewJob(ctx context.Context, arg GetReviewJobParams) (ReviewJob, error) {
	row := q.db.QueryRow(ctx, getReviewJob, arg.ID, arg.WorkspaceID)
	var i ReviewJob
	err := row.Scan(
		&i.ID,
		&i.ReviewKitID,
		&i.WorkspaceID,
		&i.Platform,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.FailureReason,
		&i.AgentVersion,
		&i.ReviewSessionTokenID,
		&i.VideoFileID,
		&i.ArtifactsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReviewKit = `-- name: GetReviewKit :one
SELECT id, workspace_id, platform, use_case, review_domain_id, brand_snapshot, required_scopes, status, created_at, updated_at FROM review_kits
WHERE id = $1 AND workspace_id = $2
`

type GetReviewKitParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetReviewKit(ctx context.Context, arg GetReviewKitParams) (ReviewKit, error) {
	row := q.db.QueryRow(ctx, getReviewKit, arg.ID, arg.WorkspaceID)
	var i ReviewKit
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Platform,
		&i.UseCase,
		&i.ReviewDomainID,
		&i.BrandSnapshot,
		&i.RequiredScopes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReviewSessionByTokenHash = `-- name: GetReviewSessionByTokenHash :one
SELECT id, review_job_id, review_kit_id, workspace_id, platform, review_domain, token_hash, expires_at, claimed_at, revoked_at, created_at FROM review_sessions
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
`

func (q *Queries) GetReviewSessionByTokenHash(ctx context.Context, tokenHash string) (ReviewSession, error) {
	row := q.db.QueryRow(ctx, getReviewSessionByTokenHash, tokenHash)
	var i ReviewSession
	err := row.Scan(
		&i.ID,
		&i.ReviewJobID,
		&i.ReviewKitID,
		&i.WorkspaceID,
		&i.Platform,
		&i.ReviewDomain,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ClaimedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listReviewDomainsByWorkspace = `-- name: ListReviewDomainsByWorkspace :many
SELECT id, workspace_id, domain, provider, status, verification_token, cname_target, dns_verified_at, tls_status, tls_issued_at, created_at, updated_at FROM review_domains
WHERE workspace_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListReviewDomainsByWorkspace(ctx context.Context, workspaceID string) ([]ReviewDomain, error) {
	rows, err := q.db.Query(ctx, listReviewDomainsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewDomain{}
	for rows.Next() {
		var i ReviewDomain
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Domain,
			&i.Provider,
			&i.Status,
			&i.VerificationToken,
			&i.CnameTarget,
			&i.DnsVerifiedAt,
			&i.TlsStatus,
			&i.TlsIssuedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewJobEvents = `-- name: ListReviewJobEvents :many
SELECT e.id, e.review_job_id, e.event_type, e.message, e.metadata, e.elapsed_ms, e.created_at FROM review_job_events e
JOIN review_jobs j ON j.id = e.review_job_id
WHERE e.review_job_id = $1 AND j.workspace_id = $2
ORDER BY e.created_at ASC
`

type ListReviewJobEventsParams struct {
	ReviewJobID string `json:"review_job_id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) ListReviewJobEvents(ctx context.Context, arg ListReviewJobEventsParams) ([]ReviewJobEvent, error) {
	rows, err := q.db.Query(ctx, listReviewJobEvents, arg.ReviewJobID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewJobEvent{}
	for rows.Next() {
		var i ReviewJobEvent
		if err := rows.Scan(
			&i.ID,
			&i.ReviewJobID,
			&i.EventType,
			&i.Message,
			&i.Metadata,
			&i.ElapsedMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewJobsByKit = `-- name: ListReviewJobsByKit :many
SELECT id, review_kit_id, workspace_id, platform, status, started_at, completed_at, failed_at, failure_reason, agent_version, review_session_token_id, video_file_id, artifacts_json, created_at, updated_at FROM review_jobs
WHERE review_kit_id = $1 AND workspace_id = $2
ORDER BY created_at DESC
`

type ListReviewJobsByKitParams struct {
	ReviewKitID string `json:"review_kit_id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) ListReviewJobsByKit(ctx context.Context, arg ListReviewJobsByKitParams) ([]ReviewJob, error) {
	rows, err := q.db.Query(ctx, listReviewJobsByKit, arg.ReviewKitID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewJob{}
	for rows.Next() {
		var i ReviewJob
		if err := rows.Scan(
			&i.ID,
			&i.ReviewKitID,
			&i.WorkspaceID,
			&i.Platform,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FailedAt,
			&i.FailureReason,
			&i.AgentVersion,
			&i.ReviewSessionTokenID,
			&i.VideoFileID,
			&i.ArtifactsJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewKitsByWorkspace = `-- name: ListReviewKitsByWorkspace :many
SELECT id, workspace_id, platform, use_case, review_domain_id, brand_snapshot, required_scopes, status, created_at, updated_at FROM review_kits
WHERE workspace_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListReviewKitsByWorkspace(ctx context.Context, workspaceID string) ([]ReviewKit, error) {
	rows, err := q.db.Query(ctx, listReviewKitsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewKit{}
	for rows.Next() {
		var i ReviewKit
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Platform,
			&i.UseCase,
			&i.ReviewDomainID,
			&i.BrandSnapshot,
			&i.RequiredScopes,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReviewJobRunning = `-- name: MarkReviewJobRunning :one
UPDATE review_jobs
SET status = 'running',
    started_at = COALESCE(started_at, NOW()),
    updated_at = NOW()
WHERE id = $1 AND workspace_id = $2
RETURNING id, review_kit_id, workspace_id, platform, status, started_at, completed_at, failed_at, failure_reason, agent_version, review_session_token_id, video_file_id, artifacts_json, created_at, updated_at
`

type MarkReviewJobRunningParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) MarkReviewJobRunning(ctx context.Context, arg MarkReviewJobRunningParams) (ReviewJob, error) {
	row := q.db.QueryRow(ctx, markReviewJobRunning, arg.ID, arg.WorkspaceID)
	var i ReviewJob
	err := row.Scan(
		&i.ID,
		&i.ReviewKitID,
		&i.WorkspaceID,
		&i.Platform,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.FailureReason,
		&i.AgentVersion,
		&i.ReviewSessionTokenID,
		&i.VideoFileID,
		&i.ArtifactsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markReviewJobWaitingForUser = `-- name: MarkReviewJobWaitingForUser :one
UPDATE review_jobs
SET status = 'waiting_for_user',
    updated_at = NOW()
WHERE id = $1 AND workspace_id = $2
RETURNING id, review_kit_id, workspace_id, platform, status, started_at, completed_at, failed_at, failure_reason, agent_version, review_session_token_id, video_file_id, artifacts_json, created_at, updated_at
`

type MarkReviewJobWaitingForUserParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) MarkReviewJobWaitingForUser(ctx context.Context, arg MarkReviewJobWaitingForUserParams) (ReviewJob, error) {
	row := q.db.QueryRow(ctx, markReviewJobWaitingForUser, arg.ID, arg.WorkspaceID)
	var i ReviewJob
	err := row.Scan(
		&i.ID,
		&i.ReviewKitID,
		&i.WorkspaceID,
		&i.Platform,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.FailureReason,
		&i.AgentVersion,
		&i.ReviewSessionTokenID,
		&i.VideoFileID,
		&i.ArtifactsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeReviewSession = `-- name: RevokeReviewSession :one
UPDATE review_sessions
SET revoked_at = NOW()
WHERE id = $1 AND workspace_id = $2
RETURNING id, review_job_id, review_kit_id, workspace_id, platform, review_domain, token_hash, expires_at, claimed_at, revoked_at, created_at
`

type RevokeReviewSessionParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) RevokeReviewSession(ctx context.Context, arg RevokeReviewSessionParams) (ReviewSession, error) {
	row := q.db.QueryRow(ctx, revokeReviewSession, arg.ID, arg.WorkspaceID)
	var i ReviewSession
	err := row.Scan(
		&i.ID,
		&i.ReviewJobID,
		&i.ReviewKitID,
		&i.WorkspaceID,
		&i.Platform,
		&i.ReviewDomain,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ClaimedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateReviewDomainVerification = `-- name: UpdateReviewDomainVerification :one
UPDATE review_domains
SET status = $3,
    dns_verified_at = $4,
    tls_status = $5,
    tls_issued_at = $6,
    updated_at = NOW()
WHERE id = $1 AND workspace_id = $2
RETURNING id, workspace_id, domain, provider, status, verification_token, cname_target, dns_verified_at, tls_status, tls_issued_at, created_at, updated_at
`

type UpdateReviewDomainVerificationParams struct {
	ID            string             `json:"id"`
	WorkspaceID   string             `json:"workspace_id"`
	Status        string             `json:"status"`
	DnsVerifiedAt pgtype.Timestamptz `json:"dns_verified_at"`
	TlsStatus     string             `json:"tls_status"`
	TlsIssuedAt   pgtype.Timestamptz `json:"tls_issued_at"`
}

func (q *Queries) UpdateReviewDomainVerification(ctx context.Context, arg UpdateReviewDomainVerificationParams) (ReviewDomain, error) {
	row := q.db.QueryRow(ctx, updateReviewDomainVerification,
		arg.ID,
		arg.WorkspaceID,
		arg.Status,
		arg.DnsVerifiedAt,
		arg.TlsStatus,
		arg.TlsIssuedAt,
	)
	var i ReviewDomain
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Domain,
		&i.Provider,
		&i.Status,
		&i.VerificationToken,
		&i.CnameTarget,
		&i.DnsVerifiedAt,
		&i.TlsStatus,
		&i.TlsIssuedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReviewKitStatus = `-- name: UpdateReviewKitStatus :one
UPDATE review_kits
SET status = $3,
    updated_at = NOW()
WHERE id = $1 AND workspace_id = $2
RETURNING id, workspace_id, platform, use_case, review_domain_id, brand_snapshot, required_scopes, status, created_at, updated_at
`

type UpdateReviewKitStatusParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Status      string `json:"status"`
}

func (q *Queries) UpdateReviewKitStatus(ctx context.Context, arg UpdateReviewKitStatusParams) (ReviewKit, error) {
	row := q.db.QueryRow(ctx, updateReviewKitStatus, arg.ID, arg.WorkspaceID, arg.Status)
	var i ReviewKit
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Platform,
		&i.UseCase,
		&i.ReviewDomainID,
		&i.BrandSnapshot,
		&i.RequiredScopes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
