// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: social_connections.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrReactivateSocialAccountBinding = `-- name: CreateOrReactivateSocialAccountBinding :one
INSERT INTO social_accounts (
  profile_id, platform, access_token, refresh_token, token_expires_at,
  external_account_id, account_name, account_avatar_url, metadata, scope,
  status, connection_type, connect_session_id, external_user_id,
  external_user_email, last_refreshed_at, x_app_mode, connection_id,
  binding_version, binding_status
)
VALUES (
  $1, $2, $3, $4,
  $5, $6, $7,
  $8, COALESCE($9::jsonb, '{}'::jsonb), $10,
  'active', $11, $12, $13,
  $14, NOW(), $15, $16, 1, 'active'
)
ON CONFLICT (profile_id, connection_id) WHERE connection_id IS NOT NULL
DO UPDATE SET
  access_token = EXCLUDED.access_token,
  refresh_token = EXCLUDED.refresh_token,
  token_expires_at = EXCLUDED.token_expires_at,
  external_account_id = EXCLUDED.external_account_id,
  account_name = EXCLUDED.account_name,
  account_avatar_url = EXCLUDED.account_avatar_url,
  metadata = EXCLUDED.metadata,
  scope = EXCLUDED.scope,
  connection_type = EXCLUDED.connection_type,
  connect_session_id = EXCLUDED.connect_session_id,
  external_user_id = EXCLUDED.external_user_id,
  external_user_email = EXCLUDED.external_user_email,
  last_refreshed_at = NOW(),
  x_app_mode = EXCLUDED.x_app_mode,
  binding_status = 'active',
  binding_version = social_accounts.binding_version + 1,
  disconnected_at = NULL,
  status = 'active'
RETURNING id, profile_id, platform, access_token, refresh_token,
  token_expires_at, external_account_id, account_name, account_avatar_url,
  connected_at, disconnected_at, metadata, scope, status, connection_type,
  connect_session_id, external_user_id, external_user_email, last_refreshed_at,
  x_app_mode, connection_id, binding_version, binding_status
`

type CreateOrReactivateSocialAccountBindingParams struct {
	ProfileID          string             `json:"profile_id"`
	Platform           string             `json:"platform"`
	LegacyAccessToken  string             `json:"legacy_access_token"`
	LegacyRefreshToken pgtype.Text        `json:"legacy_refresh_token"`
	TokenExpiresAt     pgtype.Timestamptz `json:"token_expires_at"`
	ExternalAccountID  string             `json:"external_account_id"`
	AccountName        pgtype.Text        `json:"account_name"`
	AccountAvatarUrl   pgtype.Text        `json:"account_avatar_url"`
	Metadata           []byte             `json:"metadata"`
	Scope              []string           `json:"scope"`
	ConnectionType     string             `json:"connection_type"`
	ConnectSessionID   pgtype.Text        `json:"connect_session_id"`
	ExternalUserID     pgtype.Text        `json:"external_user_id"`
	ExternalUserEmail  pgtype.Text        `json:"external_user_email"`
	XAppMode           pgtype.Text        `json:"x_app_mode"`
	ConnectionID       pgtype.Text        `json:"connection_id"`
}

func (q *Queries) CreateOrReactivateSocialAccountBinding(ctx context.Context, arg CreateOrReactivateSocialAccountBindingParams) (SocialAccount, error) {
	row := q.db.QueryRow(ctx, createOrReactivateSocialAccountBinding,
		arg.ProfileID,
		arg.Platform,
		arg.LegacyAccessToken,
		arg.LegacyRefreshToken,
		arg.TokenExpiresAt,
		arg.ExternalAccountID,
		arg.AccountName,
		arg.AccountAvatarUrl,
		arg.Metadata,
		arg.Scope,
		arg.ConnectionType,
		arg.ConnectSessionID,
		arg.ExternalUserID,
		arg.ExternalUserEmail,
		arg.XAppMode,
		arg.ConnectionID,
	)
	var i SocialAccount
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Platform,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.ExternalAccountID,
		&i.AccountName,
		&i.AccountAvatarUrl,
		&i.ConnectedAt,
		&i.DisconnectedAt,
		&i.Metadata,
		&i.Scope,
		&i.Status,
		&i.ConnectionType,
		&i.ConnectSessionID,
		&i.ExternalUserID,
		&i.ExternalUserEmail,
		&i.LastRefreshedAt,
		&i.XAppMode,
		&i.ConnectionID,
		&i.BindingVersion,
		&i.BindingStatus,
	)
	return i, err
}

const createSocialConnection = `-- name: CreateSocialConnection :one
INSERT INTO social_connections (
  workspace_id, platform, provider_identity, access_token, refresh_token,
  token_expires_at, account_name, account_avatar_url, metadata, scope, status,
  connection_type, external_user_id, external_user_email, last_refreshed_at,
  x_app_mode, connected_at, disconnected_at
)
VALUES (
  $1, $2, $3, $4, $5,
  $6, $7, $8,
  COALESCE($9::jsonb, '{}'::jsonb), $10, 'active', $11,
  $12, $13, NOW(), $14, NOW(), NULL
)
RETURNING id, workspace_id, platform, provider_identity, access_token,
  refresh_token, token_expires_at, account_name, account_avatar_url, metadata,
  scope, status, connection_type, external_user_id, external_user_email,
  last_refreshed_at, x_app_mode, connected_at, disconnected_at, created_at,
  updated_at
`

type CreateSocialConnectionParams struct {
	WorkspaceID       string             `json:"workspace_id"`
	Platform          string             `json:"platform"`
	ProviderIdentity  pgtype.Text        `json:"provider_identity"`
	AccessToken       string             `json:"access_token"`
	RefreshToken      pgtype.Text        `json:"refresh_token"`
	TokenExpiresAt    pgtype.Timestamptz `json:"token_expires_at"`
	AccountName       pgtype.Text        `json:"account_name"`
	AccountAvatarUrl  pgtype.Text        `json:"account_avatar_url"`
	Metadata          []byte             `json:"metadata"`
	Scope             []string           `json:"scope"`
	ConnectionType    string             `json:"connection_type"`
	ExternalUserID    pgtype.Text        `json:"external_user_id"`
	ExternalUserEmail pgtype.Text        `json:"external_user_email"`
	XAppMode          pgtype.Text        `json:"x_app_mode"`
}

func (q *Queries) CreateSocialConnection(ctx context.Context, arg CreateSocialConnectionParams) (SocialConnection, error) {
	row := q.db.QueryRow(ctx, createSocialConnection,
		arg.WorkspaceID,
		arg.Platform,
		arg.ProviderIdentity,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiresAt,
		arg.AccountName,
		arg.AccountAvatarUrl,
		arg.Metadata,
		arg.Scope,
		arg.ConnectionType,
		arg.ExternalUserID,
		arg.ExternalUserEmail,
		arg.XAppMode,
	)
	var i SocialConnection
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Platform,
		&i.ProviderIdentity,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.AccountName,
		&i.AccountAvatarUrl,
		&i.Metadata,
		&i.Scope,
		&i.Status,
		&i.ConnectionType,
		&i.ExternalUserID,
		&i.ExternalUserEmail,
		&i.LastRefreshedAt,
		&i.XAppMode,
		&i.ConnectedAt,
		&i.DisconnectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const disconnectAllSocialAccountBindings = `-- name: DisconnectAllSocialAccountBindings :many
UPDATE social_accounts
SET status = 'disconnected',
    disconnected_at = NOW(),
    binding_version = binding_version + 1
WHERE connection_id = $1
  AND (status <> 'disconnected' OR disconnected_at IS NULL)
RETURNING id, profile_id, platform, access_token, refresh_token,
  token_expires_at, external_account_id, account_name, account_avatar_url,
  connected_at, disconnected_at, metadata, scope, status, connection_type,
  connect_session_id, external_user_id, external_user_email, last_refreshed_at,
  x_app_mode, connection_id, binding_version, binding_status
`

func (q *Queries) DisconnectAllSocialAccountBindings(ctx context.Context, connectionID pgtype.Text) ([]SocialAccount, error) {
	rows, err := q.db.Query(ctx, disconnectAllSocialAccountBindings, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SocialAccount{}
	for rows.Next() {
		var i SocialAccount
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.Platform,
			&i.AccessToken,
			&i.RefreshToken,
			&i.TokenExpiresAt,
			&i.ExternalAccountID,
			&i.AccountName,
			&i.AccountAvatarUrl,
			&i.ConnectedAt,
			&i.DisconnectedAt,
			&i.Metadata,
			&i.Scope,
			&i.Status,
			&i.ConnectionType,
			&i.ConnectSessionID,
			&i.ExternalUserID,
			&i.ExternalUserEmail,
			&i.LastRefreshedAt,
			&i.XAppMode,
			&i.ConnectionID,
			&i.BindingVersion,
			&i.BindingStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const disconnectSocialConnection = `-- name: DisconnectSocialConnection :one
UPDATE social_connections
SET status = 'disconnected',
    disconnected_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND workspace_id = $2
RETURNING id, workspace_id, platform, provider_identity, access_token,
  refresh_token, token_expires_at, account_name, account_avatar_url, metadata,
  scope, status, connection_type, external_user_id, external_user_email,
  last_refreshed_at, x_app_mode, connected_at, disconnected_at, created_at,
  updated_at
`

type DisconnectSocialConnectionParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) DisconnectSocialConnection(ctx context.Context, arg DisconnectSocialConnectionParams) (SocialConnection, error) {
	row := q.db.QueryRow(ctx, disconnectSocialConnection, arg.ID, arg.WorkspaceID)
	var i SocialConnection
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Platform,
		&i.ProviderIdentity,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.AccountName,
		&i.AccountAvatarUrl,
		&i.Metadata,
		&i.Scope,
		&i.Status,
		&i.ConnectionType,
		&i.ExternalUserID,
		&i.ExternalUserEmail,
		&i.LastRefreshedAt,
		&i.XAppMode,
		&i.ConnectedAt,
		&i.DisconnectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findCanonicalSocialConnectionForUpdate = `-- name: FindCanonicalSocialConnectionForUpdate :one
SELECT sc.id, sc.workspace_id, sc.platform, sc.provider_identity,
  sc.access_token, sc.refresh_token, sc.token_expires_at, sc.account_name,
  sc.account_avatar_url, sc.metadata, sc.scope, sc.status,
  sc.connection_type, sc.external_user_id, sc.external_user_email,
  sc.last_refreshed_at, sc.x_app_mode, sc.connected_at, sc.disconnected_at,
  sc.created_at, sc.updated_at
FROM social_connections sc
WHERE sc.workspace_id = $1
  AND sc.platform = $2
  AND sc.provider_identity = $3
  AND sc.status <> 'migration_conflict'
FOR UPDATE OF sc
`

type FindCanonicalSocialConnectionForUpdateParams struct {
	WorkspaceID      string      `json:"workspace_id"`
	Platform         string      `json:"platform"`
	ProviderIdentity pgtype.Text `json:"provider_identity"`
}

func (q *Queries) FindCanonicalSocialConnectionForUpdate(ctx context.Context, arg FindCanonicalSocialConnectionForUpdateParams) (SocialConnection, error) {
	row := q.db.QueryRow(ctx, findCanonicalSocialConnectionForUpdate, arg.WorkspaceID, arg.Platform, arg.ProviderIdentity)
	var i SocialConnection
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Platform,
		&i.ProviderIdentity,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.AccountName,
		&i.AccountAvatarUrl,
		&i.Metadata,
		&i.Scope,
		&i.Status,
		&i.ConnectionType,
		&i.ExternalUserID,
		&i.ExternalUserEmail,
		&i.LastRefreshedAt,
		&i.XAppMode,
		&i.ConnectedAt,
		&i.DisconnectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReconnectRequiredSocialAccountForUpdate = `-- name: GetReconnectRequiredSocialAccountForUpdate :one
SELECT sa.id, sa.profile_id, sa.platform, sa.access_token, sa.refresh_token,
  sa.token_expires_at, sa.external_account_id, sa.account_name,
  sa.account_avatar_url, sa.connected_at, sa.disconnected_at, sa.metadata,
  sa.scope, sa.status, sa.connection_type, sa.connect_session_id,
  sa.external_user_id, sa.external_user_email, sa.last_refreshed_at,
  sa.x_app_mode, sa.connection_id, sa.binding_version, sa.binding_status
FROM social_accounts sa
JOIN profiles p ON p.id = sa.profile_id
WHERE sa.id = $1
  AND p.workspace_id = $2
  AND sa.profile_id = $3
  AND sa.platform = $4
  AND sa.connection_id IS NULL
  AND sa.status = 'reconnect_required'
  AND sa.binding_status = 'active'
  AND EXISTS (
    SELECT 1
    FROM social_connection_migration_conflicts conflict
    WHERE conflict.workspace_id = $2
      AND conflict.platform = $4
      AND conflict.resolved_at IS NULL
      AND sa.id = ANY(conflict.source_account_ids)
  )
FOR UPDATE OF sa
`

type GetReconnectRequiredSocialAccountForUpdateParams struct {
	ReconnectAccountID string `json:"reconnect_account_id"`
	WorkspaceID        string `json:"workspace_id"`
	ProfileID          string `json:"profile_id"`
	Platform           string `json:"platform"`
}

// A caller may recover only the exact quarantined public binding selected
// before provider authentication. Workspace/Profile/platform scope and open
// migration evidence are all required by the locking read.
func (q *Queries) GetReconnectRequiredSocialAccountForUpdate(ctx context.Context, arg GetReconnectRequiredSocialAccountForUpdateParams) (SocialAccount, error) {
	row := q.db.QueryRow(ctx, getReconnectRequiredSocialAccountForUpdate,
		arg.ReconnectAccountID,
		arg.WorkspaceID,
		arg.ProfileID,
		arg.Platform,
	)
	var i SocialAccount
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Platform,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.ExternalAccountID,
		&i.AccountName,
		&i.AccountAvatarUrl,
		&i.ConnectedAt,
		&i.DisconnectedAt,
		&i.Metadata,
		&i.Scope,
		&i.Status,
		&i.ConnectionType,
		&i.ConnectSessionID,
		&i.ExternalUserID,
		&i.ExternalUserEmail,
		&i.LastRefreshedAt,
		&i.XAppMode,
		&i.ConnectionID,
		&i.BindingVersion,
		&i.BindingStatus,
	)
	return i, err
}

const getSocialConnectionForUpdate = `-- name: GetSocialConnectionForUpdate :one
SELECT sc.id, sc.workspace_id, sc.platform, sc.provider_identity,
  sc.access_token, sc.refresh_token, sc.token_expires_at, sc.account_name,
  sc.account_avatar_url, sc.metadata, sc.scope, sc.status,
  sc.connection_type, sc.external_user_id, sc.external_user_email,
  sc.last_refreshed_at, sc.x_app_mode, sc.connected_at, sc.disconnected_at,
  sc.created_at, sc.updated_at
FROM social_connections sc
WHERE sc.id = $1
  AND sc.workspace_id = $2
FOR UPDATE OF sc
`

type GetSocialConnectionForUpdateParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetSocialConnectionForUpdate(ctx context.Context, arg GetSocialConnectionForUpdateParams) (SocialConnection, error) {
	row := q.db.QueryRow(ctx, getSocialConnectionForUpdate, arg.ID, arg.WorkspaceID)
	var i SocialConnection
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Platform,
		&i.ProviderIdentity,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.AccountName,
		&i.AccountAvatarUrl,
		&i.Metadata,
		&i.Scope,
		&i.Status,
		&i.ConnectionType,
		&i.ExternalUserID,
		&i.ExternalUserEmail,
		&i.LastRefreshedAt,
		&i.XAppMode,
		&i.ConnectedAt,
		&i.DisconnectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBoundAccountIDsForAccount = `-- name: ListBoundAccountIDsForAccount :many
SELECT DISTINCT target.id
FROM social_accounts source
JOIN profiles source_profile ON source_profile.id = source.profile_id
JOIN social_accounts target
  ON target.connection_id = source.connection_id
 AND target.binding_status = 'active'
 -- Disconnected rows are not selectable targets and must not be listed as
 -- siblings. A historical row can share a connection with a live one, and
 -- surfacing it would expose an account the caller can neither use nor see in
 -- their own account list.
 AND target.disconnected_at IS NULL
JOIN profiles target_profile ON target_profile.id = target.profile_id
LEFT JOIN social_connections sc ON sc.id = source.connection_id
WHERE source.id = $1
  AND source_profile.workspace_id = $2
  AND target_profile.workspace_id = $2
  AND (
    $3::TEXT IS NULL
    OR COALESCE(sc.external_user_id, target.external_user_id) = $3::TEXT
  )
ORDER BY target.id
`

type ListBoundAccountIDsForAccountParams struct {
	AccountID      string      `json:"account_id"`
	WorkspaceID    string      `json:"workspace_id"`
	ExternalUserID pgtype.Text `json:"external_user_id"`
}

// Exact caller-safe sibling grouping for Dashboard selection. Public binding
// IDs are returned; the physical connection ID remains server-internal.
func (q *Queries) ListBoundAccountIDsForAccount(ctx context.Context, arg ListBoundAccountIDsForAccountParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listBoundAccountIDsForAccount, arg.AccountID, arg.WorkspaceID, arg.ExternalUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoundProfileIDsForAccount = `-- name: ListBoundProfileIDsForAccount :many
SELECT DISTINCT target.profile_id
FROM social_accounts source
JOIN profiles source_profile ON source_profile.id = source.profile_id
JOIN social_accounts target
  ON target.connection_id = source.connection_id
 AND target.binding_status = 'active'
 -- Disconnected rows are not selectable targets and must not be listed as
 -- siblings. A historical row can share a connection with a live one, and
 -- surfacing it would expose an account the caller can neither use nor see in
 -- their own account list.
 AND target.disconnected_at IS NULL
JOIN profiles target_profile ON target_profile.id = target.profile_id
LEFT JOIN social_connections sc ON sc.id = source.connection_id
WHERE source.id = $1
  AND source_profile.workspace_id = $2
  AND target_profile.workspace_id = $2
  AND (
    $3::TEXT IS NULL
    OR COALESCE(sc.external_user_id, target.external_user_id) = $3::TEXT
  )
ORDER BY target.profile_id
`

type ListBoundProfileIDsForAccountParams struct {
	AccountID      string      `json:"account_id"`
	WorkspaceID    string      `json:"workspace_id"`
	ExternalUserID pgtype.Text `json:"external_user_id"`
}

func (q *Queries) ListBoundProfileIDsForAccount(ctx context.Context, arg ListBoundProfileIDsForAccountParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listBoundProfileIDsForAccount, arg.AccountID, arg.WorkspaceID, arg.ExternalUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var profile_id string
		if err := rows.Scan(&profile_id); err != nil {
			return nil, err
		}
		items = append(items, profile_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recoverReconnectRequiredSocialAccountBinding = `-- name: RecoverReconnectRequiredSocialAccountBinding :one
UPDATE social_accounts sa
SET connection_id = $1,
    access_token = $2,
    refresh_token = $3,
    token_expires_at = $4,
    external_account_id = $5,
    account_name = $6,
    account_avatar_url = $7,
    metadata = COALESCE($8::jsonb, '{}'::jsonb),
    scope = $9,
    connection_type = $10,
    connect_session_id = $11,
    external_user_id = $12,
    external_user_email = $13,
    last_refreshed_at = NOW(),
    x_app_mode = $14,
    binding_status = 'active',
    binding_version = binding_version + 1,
    disconnected_at = NULL,
    status = 'active'
FROM profiles p
WHERE sa.id = $15
  AND sa.profile_id = p.id
  AND p.workspace_id = $16
  AND sa.profile_id = $17
  AND sa.platform = $18
  AND sa.connection_id IS NULL
  AND sa.status = 'reconnect_required'
  AND EXISTS (
    SELECT 1
    FROM social_connection_migration_conflicts conflict
    WHERE conflict.workspace_id = $16
      AND conflict.platform = $18
      AND conflict.resolved_at IS NULL
      AND sa.id = ANY(conflict.source_account_ids)
  )
RETURNING sa.id, sa.profile_id, sa.platform, sa.access_token, sa.refresh_token,
  sa.token_expires_at, sa.external_account_id, sa.account_name,
  sa.account_avatar_url, sa.connected_at, sa.disconnected_at, sa.metadata,
  sa.scope, sa.status, sa.connection_type, sa.connect_session_id,
  sa.external_user_id, sa.external_user_email, sa.last_refreshed_at,
  sa.x_app_mode, sa.connection_id, sa.binding_version, sa.binding_status
`

type RecoverReconnectRequiredSocialAccountBindingParams struct {
	ConnectionID       pgtype.Text        `json:"connection_id"`
	LegacyAccessToken  string             `json:"legacy_access_token"`
	LegacyRefreshToken pgtype.Text        `json:"legacy_refresh_token"`
	TokenExpiresAt     pgtype.Timestamptz `json:"token_expires_at"`
	ExternalAccountID  string             `json:"external_account_id"`
	AccountName        pgtype.Text        `json:"account_name"`
	AccountAvatarUrl   pgtype.Text        `json:"account_avatar_url"`
	Metadata           []byte             `json:"metadata"`
	Scope              []string           `json:"scope"`
	ConnectionType     string             `json:"connection_type"`
	ConnectSessionID   pgtype.Text        `json:"connect_session_id"`
	ExternalUserID     pgtype.Text        `json:"external_user_id"`
	ExternalUserEmail  pgtype.Text        `json:"external_user_email"`
	XAppMode           pgtype.Text        `json:"x_app_mode"`
	ReconnectAccountID string             `json:"reconnect_account_id"`
	WorkspaceID        string             `json:"workspace_id"`
	ProfileID          string             `json:"profile_id"`
	Platform           string             `json:"platform"`
}

func (q *Queries) RecoverReconnectRequiredSocialAccountBinding(ctx context.Context, arg RecoverReconnectRequiredSocialAccountBindingParams) (SocialAccount, error) {
	row := q.db.QueryRow(ctx, recoverReconnectRequiredSocialAccountBinding,
		arg.ConnectionID,
		arg.LegacyAccessToken,
		arg.LegacyRefreshToken,
		arg.TokenExpiresAt,
		arg.ExternalAccountID,
		arg.AccountName,
		arg.AccountAvatarUrl,
		arg.Metadata,
		arg.Scope,
		arg.ConnectionType,
		arg.ConnectSessionID,
		arg.ExternalUserID,
		arg.ExternalUserEmail,
		arg.XAppMode,
		arg.ReconnectAccountID,
		arg.WorkspaceID,
		arg.ProfileID,
		arg.Platform,
	)
	var i SocialAccount
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Platform,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.ExternalAccountID,
		&i.AccountName,
		&i.AccountAvatarUrl,
		&i.ConnectedAt,
		&i.DisconnectedAt,
		&i.Metadata,
		&i.Scope,
		&i.Status,
		&i.ConnectionType,
		&i.ConnectSessionID,
		&i.ExternalUserID,
		&i.ExternalUserEmail,
		&i.LastRefreshedAt,
		&i.XAppMode,
		&i.ConnectionID,
		&i.BindingVersion,
		&i.BindingStatus,
	)
	return i, err
}

const refreshSocialConnection = `-- name: RefreshSocialConnection :one
UPDATE social_connections
SET access_token = $1,
    refresh_token = $2,
    token_expires_at = $3,
    account_name = $4,
    account_avatar_url = $5,
    metadata = COALESCE($6::jsonb, '{}'::jsonb),
    scope = $7,
    external_user_email = $8,
    last_refreshed_at = NOW(),
    x_app_mode = $9,
    status = 'active',
    disconnected_at = NULL,
    updated_at = NOW()
WHERE id = $10
  AND workspace_id = $11
RETURNING id, workspace_id, platform, provider_identity, access_token,
  refresh_token, token_expires_at, account_name, account_avatar_url, metadata,
  scope, status, connection_type, external_user_id, external_user_email,
  last_refreshed_at, x_app_mode, connected_at, disconnected_at, created_at,
  updated_at
`

type RefreshSocialConnectionParams struct {
	AccessToken       string             `json:"access_token"`
	RefreshToken      pgtype.Text        `json:"refresh_token"`
	TokenExpiresAt    pgtype.Timestamptz `json:"token_expires_at"`
	AccountName       pgtype.Text        `json:"account_name"`
	AccountAvatarUrl  pgtype.Text        `json:"account_avatar_url"`
	Metadata          []byte             `json:"metadata"`
	Scope             []string           `json:"scope"`
	ExternalUserEmail pgtype.Text        `json:"external_user_email"`
	XAppMode          pgtype.Text        `json:"x_app_mode"`
	ID                string             `json:"id"`
	WorkspaceID       string             `json:"workspace_id"`
}

func (q *Queries) RefreshSocialConnection(ctx context.Context, arg RefreshSocialConnectionParams) (SocialConnection, error) {
	row := q.db.QueryRow(ctx, refreshSocialConnection,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiresAt,
		arg.AccountName,
		arg.AccountAvatarUrl,
		arg.Metadata,
		arg.Scope,
		arg.ExternalUserEmail,
		arg.XAppMode,
		arg.ID,
		arg.WorkspaceID,
	)
	var i SocialConnection
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Platform,
		&i.ProviderIdentity,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.AccountName,
		&i.AccountAvatarUrl,
		&i.Metadata,
		&i.Scope,
		&i.Status,
		&i.ConnectionType,
		&i.ExternalUserID,
		&i.ExternalUserEmail,
		&i.LastRefreshedAt,
		&i.XAppMode,
		&i.ConnectedAt,
		&i.DisconnectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resolveMigrationConflictsForRecoveredAccount = `-- name: ResolveMigrationConflictsForRecoveredAccount :exec
UPDATE social_connection_migration_conflicts conflict
SET resolved_at = NOW(),
    resolution = JSONB_BUILD_OBJECT(
      'method', 'verified_targeted_reconnect',
      'recovered_account_id', $1::TEXT,
      'connection_id', $2::TEXT
    )
WHERE conflict.workspace_id = $3
  AND conflict.platform = $4
  AND conflict.resolved_at IS NULL
  AND $1::TEXT = ANY(conflict.source_account_ids)
  AND NOT EXISTS (
    SELECT 1
    FROM UNNEST(conflict.source_account_ids) AS source(account_id)
    JOIN social_accounts remaining ON remaining.id = source.account_id
    WHERE remaining.connection_id IS NULL
      AND remaining.status = 'reconnect_required'
  )
`

type ResolveMigrationConflictsForRecoveredAccountParams struct {
	ReconnectAccountID string `json:"reconnect_account_id"`
	ConnectionID       string `json:"connection_id"`
	WorkspaceID        string `json:"workspace_id"`
	Platform           string `json:"platform"`
}

func (q *Queries) ResolveMigrationConflictsForRecoveredAccount(ctx context.Context, arg ResolveMigrationConflictsForRecoveredAccountParams) error {
	_, err := q.db.Exec(ctx, resolveMigrationConflictsForRecoveredAccount,
		arg.ReconnectAccountID,
		arg.ConnectionID,
		arg.WorkspaceID,
		arg.Platform,
	)
	return err
}

const unbindSocialAccountBinding = `-- name: UnbindSocialAccountBinding :one
UPDATE social_accounts sa
SET binding_status = 'unbound',
    binding_version = binding_version + 1,
    status = 'disconnected',
    disconnected_at = NOW()
FROM profiles p
WHERE sa.id = $1
  AND sa.profile_id = p.id
  AND p.workspace_id = $2
  AND sa.connection_id = $3
  AND sa.binding_status = 'active'
RETURNING sa.id, sa.profile_id, sa.platform, sa.access_token, sa.refresh_token,
  sa.token_expires_at, sa.external_account_id, sa.account_name,
  sa.account_avatar_url, sa.connected_at, sa.disconnected_at, sa.metadata,
  sa.scope, sa.status, sa.connection_type, sa.connect_session_id,
  sa.external_user_id, sa.external_user_email, sa.last_refreshed_at,
  sa.x_app_mode, sa.connection_id, sa.binding_version, sa.binding_status
`

type UnbindSocialAccountBindingParams struct {
	ID           string      `json:"id"`
	WorkspaceID  string      `json:"workspace_id"`
	ConnectionID pgtype.Text `json:"connection_id"`
}

func (q *Queries) UnbindSocialAccountBinding(ctx context.Context, arg UnbindSocialAccountBindingParams) (SocialAccount, error) {
	row := q.db.QueryRow(ctx, unbindSocialAccountBinding, arg.ID, arg.WorkspaceID, arg.ConnectionID)
	var i SocialAccount
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Platform,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.ExternalAccountID,
		&i.AccountName,
		&i.AccountAvatarUrl,
		&i.ConnectedAt,
		&i.DisconnectedAt,
		&i.Metadata,
		&i.Scope,
		&i.Status,
		&i.ConnectionType,
		&i.ConnectSessionID,
		&i.ExternalUserID,
		&i.ExternalUserEmail,
		&i.LastRefreshedAt,
		&i.XAppMode,
		&i.ConnectionID,
		&i.BindingVersion,
		&i.BindingStatus,
	)
	return i, err
}

const updateSocialConnectionTokens = `-- name: UpdateSocialConnectionTokens :exec
UPDATE social_connections
SET access_token = $1,
    refresh_token = $2,
    token_expires_at = $3,
    last_refreshed_at = NOW(),
    updated_at = NOW()
WHERE id = $4
`

type UpdateSocialConnectionTokensParams struct {
	AccessToken    string             `json:"access_token"`
	RefreshToken   pgtype.Text        `json:"refresh_token"`
	TokenExpiresAt pgtype.Timestamptz `json:"token_expires_at"`
	ID             string             `json:"id"`
}

func (q *Queries) UpdateSocialConnectionTokens(ctx context.Context, arg UpdateSocialConnectionTokensParams) error {
	_, err := q.db.Exec(ctx, updateSocialConnectionTokens,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiresAt,
		arg.ID,
	)
	return err
}
