// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: social_accounts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSocialAccount = `-- name: CreateSocialAccount :one
INSERT INTO social_accounts (project_id, platform, access_token, refresh_token, token_expires_at, external_account_id, account_name, account_avatar_url, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, project_id, platform, access_token, refresh_token, token_expires_at, external_account_id, account_name, account_avatar_url, connected_at, disconnected_at, metadata, scope
`

type CreateSocialAccountParams struct {
	ProjectID         string             `json:"project_id"`
	Platform          string             `json:"platform"`
	AccessToken       string             `json:"access_token"`
	RefreshToken      pgtype.Text        `json:"refresh_token"`
	TokenExpiresAt    pgtype.Timestamptz `json:"token_expires_at"`
	ExternalAccountID string             `json:"external_account_id"`
	AccountName       pgtype.Text        `json:"account_name"`
	AccountAvatarUrl  pgtype.Text        `json:"account_avatar_url"`
	Metadata          []byte             `json:"metadata"`
}

func (q *Queries) CreateSocialAccount(ctx context.Context, arg CreateSocialAccountParams) (SocialAccount, error) {
	row := q.db.QueryRow(ctx, createSocialAccount,
		arg.ProjectID,
		arg.Platform,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiresAt,
		arg.ExternalAccountID,
		arg.AccountName,
		arg.AccountAvatarUrl,
		arg.Metadata,
	)
	var i SocialAccount
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Platform,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.ExternalAccountID,
		&i.AccountName,
		&i.AccountAvatarUrl,
		&i.ConnectedAt,
		&i.DisconnectedAt,
		&i.Metadata,
		&i.Scope,
	)
	return i, err
}

const disconnectSocialAccount = `-- name: DisconnectSocialAccount :one
UPDATE social_accounts SET disconnected_at = NOW()
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, platform, access_token, refresh_token, token_expires_at, external_account_id, account_name, account_avatar_url, connected_at, disconnected_at, metadata, scope
`

type DisconnectSocialAccountParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) DisconnectSocialAccount(ctx context.Context, arg DisconnectSocialAccountParams) (SocialAccount, error) {
	row := q.db.QueryRow(ctx, disconnectSocialAccount, arg.ID, arg.ProjectID)
	var i SocialAccount
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Platform,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.ExternalAccountID,
		&i.AccountName,
		&i.AccountAvatarUrl,
		&i.ConnectedAt,
		&i.DisconnectedAt,
		&i.Metadata,
		&i.Scope,
	)
	return i, err
}

const getExpiringTokens = `-- name: GetExpiringTokens :many
SELECT id, project_id, platform, access_token, refresh_token, token_expires_at, external_account_id, account_name, account_avatar_url, connected_at, disconnected_at, metadata, scope FROM social_accounts
WHERE disconnected_at IS NULL
  AND token_expires_at IS NOT NULL
  AND token_expires_at < NOW() + INTERVAL '24 hours'
`

func (q *Queries) GetExpiringTokens(ctx context.Context) ([]SocialAccount, error) {
	rows, err := q.db.Query(ctx, getExpiringTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SocialAccount{}
	for rows.Next() {
		var i SocialAccount
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Platform,
			&i.AccessToken,
			&i.RefreshToken,
			&i.TokenExpiresAt,
			&i.ExternalAccountID,
			&i.AccountName,
			&i.AccountAvatarUrl,
			&i.ConnectedAt,
			&i.DisconnectedAt,
			&i.Metadata,
			&i.Scope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSocialAccount = `-- name: GetSocialAccount :one
SELECT id, project_id, platform, access_token, refresh_token, token_expires_at, external_account_id, account_name, account_avatar_url, connected_at, disconnected_at, metadata, scope FROM social_accounts WHERE id = $1
`

func (q *Queries) GetSocialAccount(ctx context.Context, id string) (SocialAccount, error) {
	row := q.db.QueryRow(ctx, getSocialAccount, id)
	var i SocialAccount
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Platform,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.ExternalAccountID,
		&i.AccountName,
		&i.AccountAvatarUrl,
		&i.ConnectedAt,
		&i.DisconnectedAt,
		&i.Metadata,
		&i.Scope,
	)
	return i, err
}

const getSocialAccountByIDAndProject = `-- name: GetSocialAccountByIDAndProject :one
SELECT id, project_id, platform, access_token, refresh_token, token_expires_at, external_account_id, account_name, account_avatar_url, connected_at, disconnected_at, metadata, scope FROM social_accounts WHERE id = $1 AND project_id = $2
`

type GetSocialAccountByIDAndProjectParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) GetSocialAccountByIDAndProject(ctx context.Context, arg GetSocialAccountByIDAndProjectParams) (SocialAccount, error) {
	row := q.db.QueryRow(ctx, getSocialAccountByIDAndProject, arg.ID, arg.ProjectID)
	var i SocialAccount
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Platform,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.ExternalAccountID,
		&i.AccountName,
		&i.AccountAvatarUrl,
		&i.ConnectedAt,
		&i.DisconnectedAt,
		&i.Metadata,
		&i.Scope,
	)
	return i, err
}

const listSocialAccountsByProject = `-- name: ListSocialAccountsByProject :many
SELECT id, project_id, platform, access_token, refresh_token, token_expires_at, external_account_id, account_name, account_avatar_url, connected_at, disconnected_at, metadata, scope FROM social_accounts
WHERE project_id = $1 AND disconnected_at IS NULL
ORDER BY connected_at DESC
`

func (q *Queries) ListSocialAccountsByProject(ctx context.Context, projectID string) ([]SocialAccount, error) {
	rows, err := q.db.Query(ctx, listSocialAccountsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SocialAccount{}
	for rows.Next() {
		var i SocialAccount
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Platform,
			&i.AccessToken,
			&i.RefreshToken,
			&i.TokenExpiresAt,
			&i.ExternalAccountID,
			&i.AccountName,
			&i.AccountAvatarUrl,
			&i.ConnectedAt,
			&i.DisconnectedAt,
			&i.Metadata,
			&i.Scope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllSocialAccountsByProject = `-- name: ListAllSocialAccountsByProject :many
SELECT id, project_id, platform, access_token, refresh_token, token_expires_at, external_account_id, account_name, account_avatar_url, connected_at, disconnected_at, metadata, scope FROM social_accounts
WHERE project_id = $1
ORDER BY connected_at DESC
`

// ListAllSocialAccountsByProject returns every account for a project, including
// disconnected ones. Used when resolving the platform for historical post
// results whose originating account may have been disconnected after publish.
func (q *Queries) ListAllSocialAccountsByProject(ctx context.Context, projectID string) ([]SocialAccount, error) {
	rows, err := q.db.Query(ctx, listAllSocialAccountsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SocialAccount{}
	for rows.Next() {
		var i SocialAccount
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Platform,
			&i.AccessToken,
			&i.RefreshToken,
			&i.TokenExpiresAt,
			&i.ExternalAccountID,
			&i.AccountName,
			&i.AccountAvatarUrl,
			&i.ConnectedAt,
			&i.DisconnectedAt,
			&i.Metadata,
			&i.Scope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSocialAccountTokens = `-- name: UpdateSocialAccountTokens :exec
UPDATE social_accounts
SET access_token = $2, refresh_token = $3, token_expires_at = $4
WHERE id = $1
`

type UpdateSocialAccountTokensParams struct {
	ID             string             `json:"id"`
	AccessToken    string             `json:"access_token"`
	RefreshToken   pgtype.Text        `json:"refresh_token"`
	TokenExpiresAt pgtype.Timestamptz `json:"token_expires_at"`
}

func (q *Queries) UpdateSocialAccountTokens(ctx context.Context, arg UpdateSocialAccountTokensParams) error {
	_, err := q.db.Exec(ctx, updateSocialAccountTokens,
		arg.ID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiresAt,
	)
	return err
}
