// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: social_connections.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrReactivateSocialAccountBinding = `-- name: CreateOrReactivateSocialAccountBinding :one
INSERT INTO social_accounts (
  profile_id, platform, access_token, refresh_token, token_expires_at,
  external_account_id, account_name, account_avatar_url, metadata, scope,
  status, connection_type, connect_session_id, external_user_id,
  external_user_email, last_refreshed_at, x_app_mode, connection_id,
  binding_version, binding_status
)
VALUES (
  $1, $2, $3, $4,
  $5, $6, $7,
  $8, COALESCE($9::jsonb, '{}'::jsonb), $10,
  'active', $11, $12, $13,
  $14, NOW(), $15, $16, 1, 'active'
)
ON CONFLICT (profile_id, connection_id) WHERE connection_id IS NOT NULL
DO UPDATE SET
  access_token = EXCLUDED.access_token,
  refresh_token = EXCLUDED.refresh_token,
  token_expires_at = EXCLUDED.token_expires_at,
  external_account_id = EXCLUDED.external_account_id,
  account_name = EXCLUDED.account_name,
  account_avatar_url = EXCLUDED.account_avatar_url,
  metadata = EXCLUDED.metadata,
  scope = EXCLUDED.scope,
  connection_type = EXCLUDED.connection_type,
  connect_session_id = EXCLUDED.connect_session_id,
  external_user_id = EXCLUDED.external_user_id,
  external_user_email = EXCLUDED.external_user_email,
  last_refreshed_at = NOW(),
  x_app_mode = EXCLUDED.x_app_mode,
  binding_status = 'active',
  binding_version = social_accounts.binding_version + 1,
  disconnected_at = NULL,
  status = 'active'
RETURNING id, profile_id, platform, access_token, refresh_token,
  token_expires_at, external_account_id, account_name, account_avatar_url,
  connected_at, disconnected_at, metadata, scope, status, connection_type,
  connect_session_id, external_user_id, external_user_email, last_refreshed_at,
  x_app_mode, connection_id, binding_version, binding_status
`

type CreateOrReactivateSocialAccountBindingParams struct {
	ProfileID          string             `json:"profile_id"`
	Platform           string             `json:"platform"`
	LegacyAccessToken  string             `json:"legacy_access_token"`
	LegacyRefreshToken pgtype.Text        `json:"legacy_refresh_token"`
	TokenExpiresAt     pgtype.Timestamptz `json:"token_expires_at"`
	ExternalAccountID  string             `json:"external_account_id"`
	AccountName        pgtype.Text        `json:"account_name"`
	AccountAvatarUrl   pgtype.Text        `json:"account_avatar_url"`
	Metadata           []byte             `json:"metadata"`
	Scope              []string           `json:"scope"`
	ConnectionType     string             `json:"connection_type"`
	ConnectSessionID   pgtype.Text        `json:"connect_session_id"`
	ExternalUserID     pgtype.Text        `json:"external_user_id"`
	ExternalUserEmail  pgtype.Text        `json:"external_user_email"`
	XAppMode           pgtype.Text        `json:"x_app_mode"`
	ConnectionID       pgtype.Text        `json:"connection_id"`
}

func (q *Queries) CreateOrReactivateSocialAccountBinding(ctx context.Context, arg CreateOrReactivateSocialAccountBindingParams) (SocialAccount, error) {
	row := q.db.QueryRow(ctx, createOrReactivateSocialAccountBinding,
		arg.ProfileID,
		arg.Platform,
		arg.LegacyAccessToken,
		arg.LegacyRefreshToken,
		arg.TokenExpiresAt,
		arg.ExternalAccountID,
		arg.AccountName,
		arg.AccountAvatarUrl,
		arg.Metadata,
		arg.Scope,
		arg.ConnectionType,
		arg.ConnectSessionID,
		arg.ExternalUserID,
		arg.ExternalUserEmail,
		arg.XAppMode,
		arg.ConnectionID,
	)
	var i SocialAccount
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Platform,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.ExternalAccountID,
		&i.AccountName,
		&i.AccountAvatarUrl,
		&i.ConnectedAt,
		&i.DisconnectedAt,
		&i.Metadata,
		&i.Scope,
		&i.Status,
		&i.ConnectionType,
		&i.ConnectSessionID,
		&i.ExternalUserID,
		&i.ExternalUserEmail,
		&i.LastRefreshedAt,
		&i.XAppMode,
		&i.ConnectionID,
		&i.BindingVersion,
		&i.BindingStatus,
	)
	return i, err
}

const createSocialConnection = `-- name: CreateSocialConnection :one
INSERT INTO social_connections (
  workspace_id, platform, provider_identity, access_token, refresh_token,
  token_expires_at, account_name, account_avatar_url, metadata, scope, status,
  connection_type, external_user_id, external_user_email, last_refreshed_at,
  x_app_mode, connected_at, disconnected_at
)
VALUES (
  $1, $2, $3, $4, $5,
  $6, $7, $8,
  COALESCE($9::jsonb, '{}'::jsonb), $10, 'active', $11,
  $12, $13, NOW(), $14, NOW(), NULL
)
RETURNING id, workspace_id, platform, provider_identity, access_token,
  refresh_token, token_expires_at, account_name, account_avatar_url, metadata,
  scope, status, connection_type, external_user_id, external_user_email,
  last_refreshed_at, x_app_mode, connected_at, disconnected_at, created_at,
  updated_at
`

type CreateSocialConnectionParams struct {
	WorkspaceID       string             `json:"workspace_id"`
	Platform          string             `json:"platform"`
	ProviderIdentity  pgtype.Text        `json:"provider_identity"`
	AccessToken       string             `json:"access_token"`
	RefreshToken      pgtype.Text        `json:"refresh_token"`
	TokenExpiresAt    pgtype.Timestamptz `json:"token_expires_at"`
	AccountName       pgtype.Text        `json:"account_name"`
	AccountAvatarUrl  pgtype.Text        `json:"account_avatar_url"`
	Metadata          []byte             `json:"metadata"`
	Scope             []string           `json:"scope"`
	ConnectionType    string             `json:"connection_type"`
	ExternalUserID    pgtype.Text        `json:"external_user_id"`
	ExternalUserEmail pgtype.Text        `json:"external_user_email"`
	XAppMode          pgtype.Text        `json:"x_app_mode"`
}

func (q *Queries) CreateSocialConnection(ctx context.Context, arg CreateSocialConnectionParams) (SocialConnection, error) {
	row := q.db.QueryRow(ctx, createSocialConnection,
		arg.WorkspaceID,
		arg.Platform,
		arg.ProviderIdentity,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiresAt,
		arg.AccountName,
		arg.AccountAvatarUrl,
		arg.Metadata,
		arg.Scope,
		arg.ConnectionType,
		arg.ExternalUserID,
		arg.ExternalUserEmail,
		arg.XAppMode,
	)
	var i SocialConnection
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Platform,
		&i.ProviderIdentity,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.AccountName,
		&i.AccountAvatarUrl,
		&i.Metadata,
		&i.Scope,
		&i.Status,
		&i.ConnectionType,
		&i.ExternalUserID,
		&i.ExternalUserEmail,
		&i.LastRefreshedAt,
		&i.XAppMode,
		&i.ConnectedAt,
		&i.DisconnectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const disconnectSocialConnection = `-- name: DisconnectSocialConnection :one
UPDATE social_connections
SET status = 'disconnected',
    disconnected_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND workspace_id = $2
RETURNING id, workspace_id, platform, provider_identity, access_token,
  refresh_token, token_expires_at, account_name, account_avatar_url, metadata,
  scope, status, connection_type, external_user_id, external_user_email,
  last_refreshed_at, x_app_mode, connected_at, disconnected_at, created_at,
  updated_at
`

type DisconnectSocialConnectionParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) DisconnectSocialConnection(ctx context.Context, arg DisconnectSocialConnectionParams) (SocialConnection, error) {
	row := q.db.QueryRow(ctx, disconnectSocialConnection, arg.ID, arg.WorkspaceID)
	var i SocialConnection
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Platform,
		&i.ProviderIdentity,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.AccountName,
		&i.AccountAvatarUrl,
		&i.Metadata,
		&i.Scope,
		&i.Status,
		&i.ConnectionType,
		&i.ExternalUserID,
		&i.ExternalUserEmail,
		&i.LastRefreshedAt,
		&i.XAppMode,
		&i.ConnectedAt,
		&i.DisconnectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findCanonicalSocialConnectionForUpdate = `-- name: FindCanonicalSocialConnectionForUpdate :one
SELECT sc.id, sc.workspace_id, sc.platform, sc.provider_identity,
  sc.access_token, sc.refresh_token, sc.token_expires_at, sc.account_name,
  sc.account_avatar_url, sc.metadata, sc.scope, sc.status,
  sc.connection_type, sc.external_user_id, sc.external_user_email,
  sc.last_refreshed_at, sc.x_app_mode, sc.connected_at, sc.disconnected_at,
  sc.created_at, sc.updated_at
FROM social_connections sc
WHERE sc.workspace_id = $1
  AND sc.platform = $2
  AND sc.provider_identity = $3
  AND sc.status <> 'migration_conflict'
FOR UPDATE OF sc
`

type FindCanonicalSocialConnectionForUpdateParams struct {
	WorkspaceID      string      `json:"workspace_id"`
	Platform         string      `json:"platform"`
	ProviderIdentity pgtype.Text `json:"provider_identity"`
}

func (q *Queries) FindCanonicalSocialConnectionForUpdate(ctx context.Context, arg FindCanonicalSocialConnectionForUpdateParams) (SocialConnection, error) {
	row := q.db.QueryRow(ctx, findCanonicalSocialConnectionForUpdate, arg.WorkspaceID, arg.Platform, arg.ProviderIdentity)
	var i SocialConnection
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Platform,
		&i.ProviderIdentity,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.AccountName,
		&i.AccountAvatarUrl,
		&i.Metadata,
		&i.Scope,
		&i.Status,
		&i.ConnectionType,
		&i.ExternalUserID,
		&i.ExternalUserEmail,
		&i.LastRefreshedAt,
		&i.XAppMode,
		&i.ConnectedAt,
		&i.DisconnectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSocialConnectionForUpdate = `-- name: GetSocialConnectionForUpdate :one
SELECT sc.id, sc.workspace_id, sc.platform, sc.provider_identity,
  sc.access_token, sc.refresh_token, sc.token_expires_at, sc.account_name,
  sc.account_avatar_url, sc.metadata, sc.scope, sc.status,
  sc.connection_type, sc.external_user_id, sc.external_user_email,
  sc.last_refreshed_at, sc.x_app_mode, sc.connected_at, sc.disconnected_at,
  sc.created_at, sc.updated_at
FROM social_connections sc
WHERE sc.id = $1
  AND sc.workspace_id = $2
FOR UPDATE OF sc
`

type GetSocialConnectionForUpdateParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetSocialConnectionForUpdate(ctx context.Context, arg GetSocialConnectionForUpdateParams) (SocialConnection, error) {
	row := q.db.QueryRow(ctx, getSocialConnectionForUpdate, arg.ID, arg.WorkspaceID)
	var i SocialConnection
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Platform,
		&i.ProviderIdentity,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.AccountName,
		&i.AccountAvatarUrl,
		&i.Metadata,
		&i.Scope,
		&i.Status,
		&i.ConnectionType,
		&i.ExternalUserID,
		&i.ExternalUserEmail,
		&i.LastRefreshedAt,
		&i.XAppMode,
		&i.ConnectedAt,
		&i.DisconnectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const refreshSocialConnection = `-- name: RefreshSocialConnection :one
UPDATE social_connections
SET access_token = $1,
    refresh_token = $2,
    token_expires_at = $3,
    account_name = $4,
    account_avatar_url = $5,
    metadata = COALESCE($6::jsonb, '{}'::jsonb),
    scope = $7,
    external_user_email = $8,
    last_refreshed_at = NOW(),
    x_app_mode = $9,
    status = 'active',
    disconnected_at = NULL,
    updated_at = NOW()
WHERE id = $10
  AND workspace_id = $11
RETURNING id, workspace_id, platform, provider_identity, access_token,
  refresh_token, token_expires_at, account_name, account_avatar_url, metadata,
  scope, status, connection_type, external_user_id, external_user_email,
  last_refreshed_at, x_app_mode, connected_at, disconnected_at, created_at,
  updated_at
`

type RefreshSocialConnectionParams struct {
	AccessToken       string             `json:"access_token"`
	RefreshToken      pgtype.Text        `json:"refresh_token"`
	TokenExpiresAt    pgtype.Timestamptz `json:"token_expires_at"`
	AccountName       pgtype.Text        `json:"account_name"`
	AccountAvatarUrl  pgtype.Text        `json:"account_avatar_url"`
	Metadata          []byte             `json:"metadata"`
	Scope             []string           `json:"scope"`
	ExternalUserEmail pgtype.Text        `json:"external_user_email"`
	XAppMode          pgtype.Text        `json:"x_app_mode"`
	ID                string             `json:"id"`
	WorkspaceID       string             `json:"workspace_id"`
}

func (q *Queries) RefreshSocialConnection(ctx context.Context, arg RefreshSocialConnectionParams) (SocialConnection, error) {
	row := q.db.QueryRow(ctx, refreshSocialConnection,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiresAt,
		arg.AccountName,
		arg.AccountAvatarUrl,
		arg.Metadata,
		arg.Scope,
		arg.ExternalUserEmail,
		arg.XAppMode,
		arg.ID,
		arg.WorkspaceID,
	)
	var i SocialConnection
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Platform,
		&i.ProviderIdentity,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.AccountName,
		&i.AccountAvatarUrl,
		&i.Metadata,
		&i.Scope,
		&i.Status,
		&i.ConnectionType,
		&i.ExternalUserID,
		&i.ExternalUserEmail,
		&i.LastRefreshedAt,
		&i.XAppMode,
		&i.ConnectedAt,
		&i.DisconnectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
