// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: social_posts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSocialPost = `-- name: CreateSocialPost :one
INSERT INTO social_posts (project_id, caption, media_urls, status, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, caption, media_urls, status, scheduled_at, published_at, created_at, metadata
`

type CreateSocialPostParams struct {
	ProjectID string      `json:"project_id"`
	Caption   pgtype.Text `json:"caption"`
	MediaUrls []string    `json:"media_urls"`
	Status    string      `json:"status"`
	Metadata  []byte      `json:"metadata"`
}

func (q *Queries) CreateSocialPost(ctx context.Context, arg CreateSocialPostParams) (SocialPost, error) {
	row := q.db.QueryRow(ctx, createSocialPost,
		arg.ProjectID,
		arg.Caption,
		arg.MediaUrls,
		arg.Status,
		arg.Metadata,
	)
	var i SocialPost
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Caption,
		&i.MediaUrls,
		&i.Status,
		&i.ScheduledAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.Metadata,
	)
	return i, err
}

const deleteSocialPost = `-- name: DeleteSocialPost :exec
DELETE FROM social_posts WHERE id = $1
`

func (q *Queries) DeleteSocialPost(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSocialPost, id)
	return err
}

const getSocialPostByIDAndProject = `-- name: GetSocialPostByIDAndProject :one
SELECT id, project_id, caption, media_urls, status, scheduled_at, published_at, created_at, metadata FROM social_posts WHERE id = $1 AND project_id = $2
`

type GetSocialPostByIDAndProjectParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) GetSocialPostByIDAndProject(ctx context.Context, arg GetSocialPostByIDAndProjectParams) (SocialPost, error) {
	row := q.db.QueryRow(ctx, getSocialPostByIDAndProject, arg.ID, arg.ProjectID)
	var i SocialPost
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Caption,
		&i.MediaUrls,
		&i.Status,
		&i.ScheduledAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.Metadata,
	)
	return i, err
}

const listSocialPostsByProject = `-- name: ListSocialPostsByProject :many
SELECT id, project_id, caption, media_urls, status, scheduled_at, published_at, created_at, metadata FROM social_posts
WHERE project_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSocialPostsByProjectParams struct {
	ProjectID string `json:"project_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListSocialPostsByProject(ctx context.Context, arg ListSocialPostsByProjectParams) ([]SocialPost, error) {
	rows, err := q.db.Query(ctx, listSocialPostsByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SocialPost{}
	for rows.Next() {
		var i SocialPost
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Caption,
			&i.MediaUrls,
			&i.Status,
			&i.ScheduledAt,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSocialPostStatus = `-- name: UpdateSocialPostStatus :exec
UPDATE social_posts SET status = $2, published_at = $3
WHERE id = $1
`

type UpdateSocialPostStatusParams struct {
	ID          string             `json:"id"`
	Status      string             `json:"status"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) UpdateSocialPostStatus(ctx context.Context, arg UpdateSocialPostStatusParams) error {
	_, err := q.db.Exec(ctx, updateSocialPostStatus, arg.ID, arg.Status, arg.PublishedAt)
	return err
}
