// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelSubscription = `-- name: CancelSubscription :exec
UPDATE subscriptions
SET plan_id = 'free', status = 'active', stripe_subscription_id = NULL,
    cancel_at_period_end = FALSE, updated_at = NOW()
WHERE stripe_subscription_id = $1
`

func (q *Queries) CancelSubscription(ctx context.Context, stripeSubscriptionID pgtype.Text) error {
	_, err := q.db.Exec(ctx, cancelSubscription, stripeSubscriptionID)
	return err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (project_id, plan_id, stripe_customer_id, stripe_subscription_id, status)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (project_id) DO UPDATE
SET plan_id = EXCLUDED.plan_id,
    stripe_customer_id = EXCLUDED.stripe_customer_id,
    stripe_subscription_id = EXCLUDED.stripe_subscription_id,
    status = EXCLUDED.status,
    updated_at = NOW()
RETURNING id, project_id, plan_id, stripe_customer_id, stripe_subscription_id, status, current_period_start, current_period_end, cancel_at_period_end, created_at, updated_at
`

type CreateSubscriptionParams struct {
	ProjectID            string      `json:"project_id"`
	PlanID               string      `json:"plan_id"`
	StripeCustomerID     pgtype.Text `json:"stripe_customer_id"`
	StripeSubscriptionID pgtype.Text `json:"stripe_subscription_id"`
	Status               string      `json:"status"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.ProjectID,
		arg.PlanID,
		arg.StripeCustomerID,
		arg.StripeSubscriptionID,
		arg.Status,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.PlanID,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByProject = `-- name: GetSubscriptionByProject :one
SELECT id, project_id, plan_id, stripe_customer_id, stripe_subscription_id, status, current_period_start, current_period_end, cancel_at_period_end, created_at, updated_at FROM subscriptions WHERE project_id = $1
`

func (q *Queries) GetSubscriptionByProject(ctx context.Context, projectID string) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByProject, projectID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.PlanID,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByStripeCustomer = `-- name: GetSubscriptionByStripeCustomer :one
SELECT id, project_id, plan_id, stripe_customer_id, stripe_subscription_id, status, current_period_start, current_period_end, cancel_at_period_end, created_at, updated_at FROM subscriptions WHERE stripe_customer_id = $1
`

func (q *Queries) GetSubscriptionByStripeCustomer(ctx context.Context, stripeCustomerID pgtype.Text) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByStripeCustomer, stripeCustomerID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.PlanID,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByStripeSubscription = `-- name: GetSubscriptionByStripeSubscription :one
SELECT id, project_id, plan_id, stripe_customer_id, stripe_subscription_id, status, current_period_start, current_period_end, cancel_at_period_end, created_at, updated_at FROM subscriptions WHERE stripe_subscription_id = $1
`

func (q *Queries) GetSubscriptionByStripeSubscription(ctx context.Context, stripeSubscriptionID pgtype.Text) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByStripeSubscription, stripeSubscriptionID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.PlanID,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubscriptionPlan = `-- name: UpdateSubscriptionPlan :exec
UPDATE subscriptions
SET plan_id = $2, status = $3, updated_at = NOW()
WHERE project_id = $1
`

type UpdateSubscriptionPlanParams struct {
	ProjectID string `json:"project_id"`
	PlanID    string `json:"plan_id"`
	Status    string `json:"status"`
}

func (q *Queries) UpdateSubscriptionPlan(ctx context.Context, arg UpdateSubscriptionPlanParams) error {
	_, err := q.db.Exec(ctx, updateSubscriptionPlan, arg.ProjectID, arg.PlanID, arg.Status)
	return err
}

const updateSubscriptionStatus = `-- name: UpdateSubscriptionStatus :exec
UPDATE subscriptions SET status = $2, updated_at = NOW() WHERE stripe_subscription_id = $1
`

type UpdateSubscriptionStatusParams struct {
	StripeSubscriptionID pgtype.Text `json:"stripe_subscription_id"`
	Status               string      `json:"status"`
}

func (q *Queries) UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) error {
	_, err := q.db.Exec(ctx, updateSubscriptionStatus, arg.StripeSubscriptionID, arg.Status)
	return err
}

const updateSubscriptionStripe = `-- name: UpdateSubscriptionStripe :exec
UPDATE subscriptions
SET stripe_customer_id = $2, stripe_subscription_id = $3, plan_id = $4, status = $5,
    current_period_start = $6, current_period_end = $7, updated_at = NOW()
WHERE project_id = $1
`

type UpdateSubscriptionStripeParams struct {
	ProjectID            string             `json:"project_id"`
	StripeCustomerID     pgtype.Text        `json:"stripe_customer_id"`
	StripeSubscriptionID pgtype.Text        `json:"stripe_subscription_id"`
	PlanID               string             `json:"plan_id"`
	Status               string             `json:"status"`
	CurrentPeriodStart   pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd     pgtype.Timestamptz `json:"current_period_end"`
}

func (q *Queries) UpdateSubscriptionStripe(ctx context.Context, arg UpdateSubscriptionStripeParams) error {
	_, err := q.db.Exec(ctx, updateSubscriptionStripe,
		arg.ProjectID,
		arg.StripeCustomerID,
		arg.StripeSubscriptionID,
		arg.PlanID,
		arg.Status,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
	)
	return err
}
