// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: terminal_post_event_outbox.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPendingTerminalPostEventDeliveries = `-- name: ClaimPendingTerminalPostEventDeliveries :many
WITH candidates AS (
  SELECT delivery.event_id, delivery.sink
  FROM terminal_post_event_deliveries delivery
  JOIN terminal_post_event_outbox event ON event.id = delivery.event_id
  WHERE (
      delivery.status = 'pending'
      OR (delivery.status = 'processing' AND delivery.lease_expires_at <= NOW())
    )
    AND delivery.next_attempt_at <= NOW()
    AND NOT EXISTS (
      SELECT 1
      FROM terminal_post_event_outbox earlier_event
      JOIN terminal_post_event_deliveries earlier_delivery
        ON earlier_delivery.event_id = earlier_event.id
      WHERE earlier_event.post_id = event.post_id
        AND earlier_event.sequence_number < event.sequence_number
        AND earlier_delivery.status <> 'enqueued'
    )
  ORDER BY event.sequence_number, delivery.sink
  FOR UPDATE OF delivery SKIP LOCKED
  LIMIT $1
), claimed AS (
  UPDATE terminal_post_event_deliveries delivery
  SET status = 'processing',
      attempts = delivery.attempts + 1,
      lease_expires_at = NOW() + INTERVAL '5 minutes',
      last_error = NULL,
      updated_at = NOW()
  FROM candidates
  WHERE delivery.event_id = candidates.event_id
    AND delivery.sink = candidates.sink
  RETURNING delivery.event_id, delivery.sink, delivery.status, delivery.attempts, delivery.next_attempt_at, delivery.lease_expires_at, delivery.last_error, delivery.enqueued_at, delivery.created_at, delivery.updated_at
)
SELECT
  claimed.event_id,
  claimed.sink,
  claimed.attempts,
  event.workspace_id,
  event.post_id,
  event.parent_status,
  event.parent_version,
  event.event_type,
  event.payload,
  event.sequence_number
FROM claimed
JOIN terminal_post_event_outbox event ON event.id = claimed.event_id
ORDER BY event.sequence_number, claimed.sink
`

type ClaimPendingTerminalPostEventDeliveriesRow struct {
	EventID        string `json:"event_id"`
	Sink           string `json:"sink"`
	Attempts       int32  `json:"attempts"`
	WorkspaceID    string `json:"workspace_id"`
	PostID         string `json:"post_id"`
	ParentStatus   string `json:"parent_status"`
	ParentVersion  string `json:"parent_version"`
	EventType      string `json:"event_type"`
	Payload        []byte `json:"payload"`
	SequenceNumber int64  `json:"sequence_number"`
}

func (q *Queries) ClaimPendingTerminalPostEventDeliveries(ctx context.Context, limit int32) ([]ClaimPendingTerminalPostEventDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, claimPendingTerminalPostEventDeliveries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimPendingTerminalPostEventDeliveriesRow{}
	for rows.Next() {
		var i ClaimPendingTerminalPostEventDeliveriesRow
		if err := rows.Scan(
			&i.EventID,
			&i.Sink,
			&i.Attempts,
			&i.WorkspaceID,
			&i.PostID,
			&i.ParentStatus,
			&i.ParentVersion,
			&i.EventType,
			&i.Payload,
			&i.SequenceNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createPostStatusTransitionEvent = `-- name: CreatePostStatusTransitionEvent :one
INSERT INTO terminal_post_event_outbox (
  post_id,
  workspace_id,
  parent_status,
  parent_version,
  event_type,
  payload
) VALUES (
  $1,
  $2,
  $3,
  $4,
  CAST($5 AS TEXT),
  $6
)
ON CONFLICT (post_id, parent_version) DO NOTHING
RETURNING id, sequence_number, post_id, workspace_id, parent_status, parent_version, event_type, payload, created_at
`

type CreatePostStatusTransitionEventParams struct {
	PostID        string `json:"post_id"`
	WorkspaceID   string `json:"workspace_id"`
	ParentStatus  string `json:"parent_status"`
	ParentVersion string `json:"parent_version"`
	EventType     string `json:"event_type"`
	Payload       []byte `json:"payload"`
}

func (q *Queries) CreatePostStatusTransitionEvent(ctx context.Context, arg CreatePostStatusTransitionEventParams) (TerminalPostEventOutbox, error) {
	row := q.db.QueryRow(ctx, createPostStatusTransitionEvent,
		arg.PostID,
		arg.WorkspaceID,
		arg.ParentStatus,
		arg.ParentVersion,
		arg.EventType,
		arg.Payload,
	)
	var i TerminalPostEventOutbox
	err := row.Scan(
		&i.ID,
		&i.SequenceNumber,
		&i.PostID,
		&i.WorkspaceID,
		&i.ParentStatus,
		&i.ParentVersion,
		&i.EventType,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const createTerminalPostEventDelivery = `-- name: CreateTerminalPostEventDelivery :exec
INSERT INTO terminal_post_event_deliveries (event_id, sink)
VALUES ($1, $2)
ON CONFLICT (event_id, sink) DO NOTHING
`

type CreateTerminalPostEventDeliveryParams struct {
	EventID string `json:"event_id"`
	Sink    string `json:"sink"`
}

func (q *Queries) CreateTerminalPostEventDelivery(ctx context.Context, arg CreateTerminalPostEventDeliveryParams) error {
	_, err := q.db.Exec(ctx, createTerminalPostEventDelivery, arg.EventID, arg.Sink)
	return err
}

const electWorkspaceFirstPostPublished = `-- name: ElectWorkspaceFirstPostPublished :one
INSERT INTO terminal_post_first_publish_elections (workspace_id, post_id)
SELECT $1, $2
WHERE (
  SELECT COUNT(*)
  FROM social_posts
  WHERE workspace_id = $1
    AND status = 'published'
) = 1
ON CONFLICT (workspace_id) DO NOTHING
RETURNING workspace_id
`

type ElectWorkspaceFirstPostPublishedParams struct {
	WorkspaceID string `json:"workspace_id"`
	PostID      string `json:"post_id"`
}

func (q *Queries) ElectWorkspaceFirstPostPublished(ctx context.Context, arg ElectWorkspaceFirstPostPublishedParams) (string, error) {
	row := q.db.QueryRow(ctx, electWorkspaceFirstPostPublished, arg.WorkspaceID, arg.PostID)
	var workspace_id string
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const markTerminalPostEventDeliveryEnqueued = `-- name: MarkTerminalPostEventDeliveryEnqueued :execrows
UPDATE terminal_post_event_deliveries
SET status = 'enqueued',
    enqueued_at = NOW(),
    lease_expires_at = NULL,
    last_error = NULL,
    updated_at = NOW()
WHERE event_id = $1
  AND sink = $2
  AND status = 'processing'
  AND attempts = $3
`

type MarkTerminalPostEventDeliveryEnqueuedParams struct {
	EventID          string `json:"event_id"`
	Sink             string `json:"sink"`
	ExpectedAttempts int32  `json:"expected_attempts"`
}

func (q *Queries) MarkTerminalPostEventDeliveryEnqueued(ctx context.Context, arg MarkTerminalPostEventDeliveryEnqueuedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markTerminalPostEventDeliveryEnqueued, arg.EventID, arg.Sink, arg.ExpectedAttempts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryTerminalPostEventDelivery = `-- name: RetryTerminalPostEventDelivery :execrows
UPDATE terminal_post_event_deliveries
SET status = 'pending',
    next_attempt_at = $1,
    lease_expires_at = NULL,
    last_error = $2,
    updated_at = NOW()
WHERE event_id = $3
  AND sink = $4
  AND status = 'processing'
  AND attempts = $5
`

type RetryTerminalPostEventDeliveryParams struct {
	NextAttemptAt    pgtype.Timestamptz `json:"next_attempt_at"`
	LastError        pgtype.Text        `json:"last_error"`
	EventID          string             `json:"event_id"`
	Sink             string             `json:"sink"`
	ExpectedAttempts int32              `json:"expected_attempts"`
}

func (q *Queries) RetryTerminalPostEventDelivery(ctx context.Context, arg RetryTerminalPostEventDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryTerminalPostEventDelivery,
		arg.NextAttemptAt,
		arg.LastError,
		arg.EventID,
		arg.Sink,
		arg.ExpectedAttempts,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
