// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: usage.sql

package db

import (
	"context"
)

const getUsage = `-- name: GetUsage :one
SELECT id, period, post_count, created_at, updated_at, workspace_id FROM usage WHERE workspace_id = $1 AND period = $2
`

type GetUsageParams struct {
	WorkspaceID string `json:"workspace_id"`
	Period      string `json:"period"`
}

func (q *Queries) GetUsage(ctx context.Context, arg GetUsageParams) (Usage, error) {
	row := q.db.QueryRow(ctx, getUsage, arg.WorkspaceID, arg.Period)
	var i Usage
	err := row.Scan(
		&i.ID,
		&i.Period,
		&i.PostCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
	)
	return i, err
}

const incrementUsage = `-- name: IncrementUsage :exec
INSERT INTO usage (workspace_id, period, post_count)
VALUES ($1, $2, $3)
ON CONFLICT (workspace_id, period)
DO UPDATE SET post_count = usage.post_count + $3, updated_at = NOW()
`

type IncrementUsageParams struct {
	WorkspaceID string `json:"workspace_id"`
	Period      string `json:"period"`
	PostCount   int32  `json:"post_count"`
}

func (q *Queries) IncrementUsage(ctx context.Context, arg IncrementUsageParams) error {
	_, err := q.db.Exec(ctx, incrementUsage, arg.WorkspaceID, arg.Period, arg.PostCount)
	return err
}

const upsertUsage = `-- name: UpsertUsage :one
INSERT INTO usage (workspace_id, period, post_count)
VALUES ($1, $2, 0)
ON CONFLICT (workspace_id, period) DO UPDATE SET updated_at = NOW()
RETURNING id, period, post_count, created_at, updated_at, workspace_id
`

type UpsertUsageParams struct {
	WorkspaceID string `json:"workspace_id"`
	Period      string `json:"period"`
}

func (q *Queries) UpsertUsage(ctx context.Context, arg UpsertUsageParams) (Usage, error) {
	row := q.db.QueryRow(ctx, upsertUsage, arg.WorkspaceID, arg.Period)
	var i Usage
	err := row.Scan(
		&i.ID,
		&i.Period,
		&i.PostCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
	)
	return i, err
}
