// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeOnboarding = `-- name: CompleteOnboarding :exec
UPDATE users SET onboarding_completed = TRUE, name = $2, updated_at = NOW()
WHERE id = $1
`

type CompleteOnboardingParams struct {
	ID   string      `json:"id"`
	Name pgtype.Text `json:"name"`
}

func (q *Queries) CompleteOnboarding(ctx context.Context, arg CompleteOnboardingParams) error {
	_, err := q.db.Exec(ctx, completeOnboarding, arg.ID, arg.Name)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, email, name, created_at, updated_at, default_profile_id, last_profile_id, onboarding_completed, onboarding_intent, onboarding_shown_at, onboarding_completed_at, activation_completed_at, activation_guide_dismissed_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultProfileID,
		&i.LastProfileID,
		&i.OnboardingCompleted,
		&i.OnboardingIntent,
		&i.OnboardingShownAt,
		&i.OnboardingCompletedAt,
		&i.ActivationCompletedAt,
		&i.ActivationGuideDismissedAt,
	)
	return i, err
}

const markOnboardingShown = `-- name: MarkOnboardingShown :exec
UPDATE users
SET onboarding_shown_at = COALESCE(onboarding_shown_at, NOW())
WHERE id = $1
`

// Stamps the first-seen timestamp when the Welcome modal is rendered.
// Safe to call repeatedly — only sets if currently NULL.
func (q *Queries) MarkOnboardingShown(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markOnboardingShown, id)
	return err
}

const setOnboardingIntent = `-- name: SetOnboardingIntent :one
UPDATE users
SET onboarding_intent = $2,
    onboarding_completed_at = NOW(),
    onboarding_shown_at = COALESCE(onboarding_shown_at, NOW()),
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, name, created_at, updated_at, default_profile_id, last_profile_id, onboarding_completed, onboarding_intent, onboarding_shown_at, onboarding_completed_at, activation_completed_at, activation_guide_dismissed_at
`

type SetOnboardingIntentParams struct {
	ID               string      `json:"id"`
	OnboardingIntent pgtype.Text `json:"onboarding_intent"`
}

// Records the user's intent (or "skipped") and stamps the completion time.
// Always updates (no COALESCE) so users can change their intent via Settings.
func (q *Queries) SetOnboardingIntent(ctx context.Context, arg SetOnboardingIntentParams) (User, error) {
	row := q.db.QueryRow(ctx, setOnboardingIntent, arg.ID, arg.OnboardingIntent)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultProfileID,
		&i.LastProfileID,
		&i.OnboardingCompleted,
		&i.OnboardingIntent,
		&i.OnboardingShownAt,
		&i.OnboardingCompletedAt,
		&i.ActivationCompletedAt,
		&i.ActivationGuideDismissedAt,
	)
	return i, err
}

const setUserDefaultProfile = `-- name: SetUserDefaultProfile :exec
UPDATE users SET default_profile_id = $2, updated_at = NOW()
WHERE id = $1
`

type SetUserDefaultProfileParams struct {
	ID               string      `json:"id"`
	DefaultProfileID pgtype.Text `json:"default_profile_id"`
}

func (q *Queries) SetUserDefaultProfile(ctx context.Context, arg SetUserDefaultProfileParams) error {
	_, err := q.db.Exec(ctx, setUserDefaultProfile, arg.ID, arg.DefaultProfileID)
	return err
}

const setUserLastProfile = `-- name: SetUserLastProfile :exec
UPDATE users SET last_profile_id = $2 WHERE id = $1
`

type SetUserLastProfileParams struct {
	ID            string      `json:"id"`
	LastProfileID pgtype.Text `json:"last_profile_id"`
}

func (q *Queries) SetUserLastProfile(ctx context.Context, arg SetUserLastProfileParams) error {
	_, err := q.db.Exec(ctx, setUserLastProfile, arg.ID, arg.LastProfileID)
	return err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (id, email, name)
VALUES ($1, $2, $3)
ON CONFLICT (id)
DO UPDATE SET email = $2, name = $3, updated_at = NOW()
RETURNING id, email, name, created_at, updated_at, default_profile_id, last_profile_id, onboarding_completed, onboarding_intent, onboarding_shown_at, onboarding_completed_at, activation_completed_at, activation_guide_dismissed_at
`

type UpsertUserParams struct {
	ID    string      `json:"id"`
	Email string      `json:"email"`
	Name  pgtype.Text `json:"name"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.ID, arg.Email, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultProfileID,
		&i.LastProfileID,
		&i.OnboardingCompleted,
		&i.OnboardingIntent,
		&i.OnboardingShownAt,
		&i.OnboardingCompletedAt,
		&i.ActivationCompletedAt,
		&i.ActivationGuideDismissedAt,
	)
	return i, err
}
