// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_tutorials.sql

package db

import (
	"context"
)

const clearUserTutorialDismissal = `-- name: ClearUserTutorialDismissal :exec
UPDATE user_tutorials
SET dismissed_at = NULL, updated_at = NOW()
WHERE user_id = $1 AND tutorial_id = $2 AND completed_at IS NULL
`

type ClearUserTutorialDismissalParams struct {
	UserID     string `json:"user_id"`
	TutorialID string `json:"tutorial_id"`
}

// Clears dismissed_at so a mandatory tutorial can re-pop. Called when
// the frontend decides to resume a mandatory tutorial on the profile
// page. Does not touch completed_at.
func (q *Queries) ClearUserTutorialDismissal(ctx context.Context, arg ClearUserTutorialDismissalParams) error {
	_, err := q.db.Exec(ctx, clearUserTutorialDismissal, arg.UserID, arg.TutorialID)
	return err
}

const completeUserTutorial = `-- name: CompleteUserTutorial :one
INSERT INTO user_tutorials (user_id, tutorial_id, completed_at, updated_at)
VALUES ($1, $2, NOW(), NOW())
ON CONFLICT (user_id, tutorial_id) DO UPDATE SET
  completed_at = COALESCE(user_tutorials.completed_at, EXCLUDED.completed_at),
  dismissed_at = NULL,  -- completing a tutorial clears any prior dismissal
  updated_at   = NOW()
RETURNING user_id, tutorial_id, completed_at, dismissed_at, created_at, updated_at
`

type CompleteUserTutorialParams struct {
	UserID     string `json:"user_id"`
	TutorialID string `json:"tutorial_id"`
}

// Stamps completed_at. If the row exists, keeps the earliest
// completed_at (idempotent: re-completing doesn't reset the timestamp).
func (q *Queries) CompleteUserTutorial(ctx context.Context, arg CompleteUserTutorialParams) (UserTutorial, error) {
	row := q.db.QueryRow(ctx, completeUserTutorial, arg.UserID, arg.TutorialID)
	var i UserTutorial
	err := row.Scan(
		&i.UserID,
		&i.TutorialID,
		&i.CompletedAt,
		&i.DismissedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const dismissUserTutorial = `-- name: DismissUserTutorial :one
INSERT INTO user_tutorials (user_id, tutorial_id, dismissed_at, updated_at)
VALUES ($1, $2, NOW(), NOW())
ON CONFLICT (user_id, tutorial_id) DO UPDATE SET
  dismissed_at = NOW(),
  updated_at   = NOW()
RETURNING user_id, tutorial_id, completed_at, dismissed_at, created_at, updated_at
`

type DismissUserTutorialParams struct {
	UserID     string `json:"user_id"`
	TutorialID string `json:"tutorial_id"`
}

// Stamps dismissed_at. Tutorial-specific policy (e.g. quickstart being
// re-popped on the profile page) lives in the frontend; the backend
// just records the fact.
func (q *Queries) DismissUserTutorial(ctx context.Context, arg DismissUserTutorialParams) (UserTutorial, error) {
	row := q.db.QueryRow(ctx, dismissUserTutorial, arg.UserID, arg.TutorialID)
	var i UserTutorial
	err := row.Scan(
		&i.UserID,
		&i.TutorialID,
		&i.CompletedAt,
		&i.DismissedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserTutorial = `-- name: GetUserTutorial :one
SELECT user_id, tutorial_id, completed_at, dismissed_at, created_at, updated_at
FROM user_tutorials
WHERE user_id = $1 AND tutorial_id = $2
`

type GetUserTutorialParams struct {
	UserID     string `json:"user_id"`
	TutorialID string `json:"tutorial_id"`
}

func (q *Queries) GetUserTutorial(ctx context.Context, arg GetUserTutorialParams) (UserTutorial, error) {
	row := q.db.QueryRow(ctx, getUserTutorial, arg.UserID, arg.TutorialID)
	var i UserTutorial
	err := row.Scan(
		&i.UserID,
		&i.TutorialID,
		&i.CompletedAt,
		&i.DismissedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserTutorials = `-- name: ListUserTutorials :many
SELECT user_id, tutorial_id, completed_at, dismissed_at, created_at, updated_at
FROM user_tutorials
WHERE user_id = $1
ORDER BY created_at
`

// Returns every tutorial row for a user. The handler merges this with
// activation counts so the frontend gets per-tutorial completion +
// per-step completion in one response.
func (q *Queries) ListUserTutorials(ctx context.Context, userID string) ([]UserTutorial, error) {
	rows, err := q.db.Query(ctx, listUserTutorials, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserTutorial{}
	for rows.Next() {
		var i UserTutorial
		if err := rows.Scan(
			&i.UserID,
			&i.TutorialID,
			&i.CompletedAt,
			&i.DismissedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
