// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhooks (project_id, url, secret, events)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, url, secret, events, active, created_at
`

type CreateWebhookParams struct {
	ProjectID string   `json:"project_id"`
	Url       string   `json:"url"`
	Secret    string   `json:"secret"`
	Events    []string `json:"events"`
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, createWebhook,
		arg.ProjectID,
		arg.Url,
		arg.Secret,
		arg.Events,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const createWebhookDelivery = `-- name: CreateWebhookDelivery :one
INSERT INTO webhook_deliveries (webhook_id, event, payload)
VALUES ($1, $2, $3)
RETURNING id, webhook_id, event, payload, status_code, attempts, delivered_at, next_retry_at, created_at
`

type CreateWebhookDeliveryParams struct {
	WebhookID string `json:"webhook_id"`
	Event     string `json:"event"`
	Payload   []byte `json:"payload"`
}

func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, createWebhookDelivery, arg.WebhookID, arg.Event, arg.Payload)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.Event,
		&i.Payload,
		&i.StatusCode,
		&i.Attempts,
		&i.DeliveredAt,
		&i.NextRetryAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWebhook = `-- name: DeleteWebhook :exec
UPDATE webhooks SET active = false WHERE id = $1 AND project_id = $2
`

type DeleteWebhookParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) DeleteWebhook(ctx context.Context, arg DeleteWebhookParams) error {
	_, err := q.db.Exec(ctx, deleteWebhook, arg.ID, arg.ProjectID)
	return err
}

const getPendingWebhookDeliveries = `-- name: GetPendingWebhookDeliveries :many
SELECT id, webhook_id, event, payload, status_code, attempts, delivered_at, next_retry_at, created_at FROM webhook_deliveries
WHERE delivered_at IS NULL AND (next_retry_at IS NULL OR next_retry_at <= NOW())
ORDER BY created_at ASC
LIMIT 100
`

func (q *Queries) GetPendingWebhookDeliveries(ctx context.Context) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, getPendingWebhookDeliveries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.Event,
			&i.Payload,
			&i.StatusCode,
			&i.Attempts,
			&i.DeliveredAt,
			&i.NextRetryAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWebhook = `-- name: GetWebhook :one
SELECT id, project_id, url, secret, events, active, created_at FROM webhooks WHERE id = $1
`

func (q *Queries) GetWebhook(ctx context.Context, id string) (Webhook, error) {
	row := q.db.QueryRow(ctx, getWebhook, id)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listWebhooksByProject = `-- name: ListWebhooksByProject :many
SELECT id, project_id, url, secret, events, active, created_at FROM webhooks WHERE project_id = $1 AND active = true
`

func (q *Queries) ListWebhooksByProject(ctx context.Context, projectID string) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listWebhooksByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooksByProjectAndEvent = `-- name: ListWebhooksByProjectAndEvent :many
SELECT id, project_id, url, secret, events, active, created_at FROM webhooks
WHERE project_id = $1 AND active = true AND $2::text = ANY(events)
`

type ListWebhooksByProjectAndEventParams struct {
	ProjectID string `json:"project_id"`
	Event     string `json:"event"`
}

func (q *Queries) ListWebhooksByProjectAndEvent(ctx context.Context, arg ListWebhooksByProjectAndEventParams) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listWebhooksByProjectAndEvent, arg.ProjectID, arg.Event)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebhookDelivery = `-- name: UpdateWebhookDelivery :exec
UPDATE webhook_deliveries
SET status_code = $2, attempts = $3, next_retry_at = $4, delivered_at = $5
WHERE id = $1
`

type UpdateWebhookDeliveryParams struct {
	ID          string             `json:"id"`
	StatusCode  pgtype.Int4        `json:"status_code"`
	Attempts    int32              `json:"attempts"`
	NextRetryAt pgtype.Timestamptz `json:"next_retry_at"`
	DeliveredAt pgtype.Timestamptz `json:"delivered_at"`
}

func (q *Queries) UpdateWebhookDelivery(ctx context.Context, arg UpdateWebhookDeliveryParams) error {
	_, err := q.db.Exec(ctx, updateWebhookDelivery,
		arg.ID,
		arg.StatusCode,
		arg.Attempts,
		arg.NextRetryAt,
		arg.DeliveredAt,
	)
	return err
}
