// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspaces.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (user_id, name)
VALUES ($1, $2)
RETURNING id, user_id, name, per_account_monthly_limit, created_at, updated_at, usage_modes
`

type CreateWorkspaceParams struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.UserID, arg.Name)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.PerAccountMonthlyLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UsageModes,
	)
	return i, err
}

const deleteWorkspace = `-- name: DeleteWorkspace :exec
DELETE FROM workspaces WHERE id = $1
`

func (q *Queries) DeleteWorkspace(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteWorkspace, id)
	return err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, user_id, name, per_account_monthly_limit, created_at, updated_at, usage_modes FROM workspaces WHERE id = $1
`

func (q *Queries) GetWorkspace(ctx context.Context, id string) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.PerAccountMonthlyLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UsageModes,
	)
	return i, err
}

const getWorkspaceByIDAndOwner = `-- name: GetWorkspaceByIDAndOwner :one
SELECT id, user_id, name, per_account_monthly_limit, created_at, updated_at, usage_modes FROM workspaces WHERE id = $1 AND user_id = $2
`

type GetWorkspaceByIDAndOwnerParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetWorkspaceByIDAndOwner(ctx context.Context, arg GetWorkspaceByIDAndOwnerParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByIDAndOwner, arg.ID, arg.UserID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.PerAccountMonthlyLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UsageModes,
	)
	return i, err
}

const listWorkspacesByUser = `-- name: ListWorkspacesByUser :many
SELECT id, user_id, name, per_account_monthly_limit, created_at, updated_at, usage_modes FROM workspaces WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListWorkspacesByUser(ctx context.Context, userID string) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listWorkspacesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.PerAccountMonthlyLimit,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UsageModes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkspace = `-- name: UpdateWorkspace :one
UPDATE workspaces SET name = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, per_account_monthly_limit, created_at, updated_at, usage_modes
`

type UpdateWorkspaceParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspace, arg.ID, arg.Name)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.PerAccountMonthlyLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UsageModes,
	)
	return i, err
}

const updateWorkspacePerAccountQuota = `-- name: UpdateWorkspacePerAccountQuota :one
UPDATE workspaces
SET per_account_monthly_limit = $2::INTEGER,
    updated_at                = NOW()
WHERE id = $1
RETURNING id, user_id, name, per_account_monthly_limit, created_at, updated_at, usage_modes
`

type UpdateWorkspacePerAccountQuotaParams struct {
	ID                     string      `json:"id"`
	PerAccountMonthlyLimit pgtype.Int4 `json:"per_account_monthly_limit"`
}

func (q *Queries) UpdateWorkspacePerAccountQuota(ctx context.Context, arg UpdateWorkspacePerAccountQuotaParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspacePerAccountQuota, arg.ID, arg.PerAccountMonthlyLimit)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.PerAccountMonthlyLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UsageModes,
	)
	return i, err
}

const updateWorkspaceUsageModes = `-- name: UpdateWorkspaceUsageModes :one
UPDATE workspaces SET usage_modes = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, per_account_monthly_limit, created_at, updated_at, usage_modes
`

type UpdateWorkspaceUsageModesParams struct {
	ID         string   `json:"id"`
	UsageModes []string `json:"usage_modes"`
}

func (q *Queries) UpdateWorkspaceUsageModes(ctx context.Context, arg UpdateWorkspaceUsageModesParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspaceUsageModes, arg.ID, arg.UsageModes)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.PerAccountMonthlyLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UsageModes,
	)
	return i, err
}
