// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_trial_grants.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimWorkspaceTrialGrantCheckout = `-- name: ClaimWorkspaceTrialGrantCheckout :one
UPDATE workspace_trial_grants
SET status = 'checkout_pending',
    stripe_customer_id = $1,
    checkout_attempt = checkout_attempt + 1,
    updated_at = NOW()
WHERE id = $2
  AND workspace_id = $3
  AND plan_id = $4
  AND $1::TEXT <> ''
  AND status = 'pending_activation'
RETURNING id, workspace_id, kind, plan_id, duration_days, status, granted_by_user_id, stripe_mode, stripe_customer_id, stripe_subscription_id, stripe_schedule_id, stripe_checkout_session_id, checkout_attempt, granted_at, scheduled_start_at, started_at, ends_at, activated_at, canceled_at, revoked_at, superseded_at, completed_at, superseded_by_plan_id, failure_code, failure_message, created_at, updated_at
`

type ClaimWorkspaceTrialGrantCheckoutParams struct {
	StripeCustomerID pgtype.Text `json:"stripe_customer_id"`
	ID               string      `json:"id"`
	WorkspaceID      string      `json:"workspace_id"`
	PlanID           string      `json:"plan_id"`
}

func (q *Queries) ClaimWorkspaceTrialGrantCheckout(ctx context.Context, arg ClaimWorkspaceTrialGrantCheckoutParams) (WorkspaceTrialGrant, error) {
	row := q.db.QueryRow(ctx, claimWorkspaceTrialGrantCheckout,
		arg.StripeCustomerID,
		arg.ID,
		arg.WorkspaceID,
		arg.PlanID,
	)
	var i WorkspaceTrialGrant
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.PlanID,
		&i.DurationDays,
		&i.Status,
		&i.GrantedByUserID,
		&i.StripeMode,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripeScheduleID,
		&i.StripeCheckoutSessionID,
		&i.CheckoutAttempt,
		&i.GrantedAt,
		&i.ScheduledStartAt,
		&i.StartedAt,
		&i.EndsAt,
		&i.ActivatedAt,
		&i.CanceledAt,
		&i.RevokedAt,
		&i.SupersededAt,
		&i.CompletedAt,
		&i.SupersededByPlanID,
		&i.FailureCode,
		&i.FailureMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkspaceTrialGrant = `-- name: CreateWorkspaceTrialGrant :one
INSERT INTO workspace_trial_grants (
  workspace_id,
  kind,
  plan_id,
  duration_days,
  status,
  granted_by_user_id,
  stripe_mode,
  stripe_customer_id,
  stripe_subscription_id,
  granted_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10
)
RETURNING id, workspace_id, kind, plan_id, duration_days, status, granted_by_user_id, stripe_mode, stripe_customer_id, stripe_subscription_id, stripe_schedule_id, stripe_checkout_session_id, checkout_attempt, granted_at, scheduled_start_at, started_at, ends_at, activated_at, canceled_at, revoked_at, superseded_at, completed_at, superseded_by_plan_id, failure_code, failure_message, created_at, updated_at
`

type CreateWorkspaceTrialGrantParams struct {
	WorkspaceID          string             `json:"workspace_id"`
	Kind                 string             `json:"kind"`
	PlanID               string             `json:"plan_id"`
	DurationDays         int32              `json:"duration_days"`
	Status               string             `json:"status"`
	GrantedByUserID      string             `json:"granted_by_user_id"`
	StripeMode           pgtype.Text        `json:"stripe_mode"`
	StripeCustomerID     pgtype.Text        `json:"stripe_customer_id"`
	StripeSubscriptionID pgtype.Text        `json:"stripe_subscription_id"`
	GrantedAt            pgtype.Timestamptz `json:"granted_at"`
}

func (q *Queries) CreateWorkspaceTrialGrant(ctx context.Context, arg CreateWorkspaceTrialGrantParams) (WorkspaceTrialGrant, error) {
	row := q.db.QueryRow(ctx, createWorkspaceTrialGrant,
		arg.WorkspaceID,
		arg.Kind,
		arg.PlanID,
		arg.DurationDays,
		arg.Status,
		arg.GrantedByUserID,
		arg.StripeMode,
		arg.StripeCustomerID,
		arg.StripeSubscriptionID,
		arg.GrantedAt,
	)
	var i WorkspaceTrialGrant
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.PlanID,
		&i.DurationDays,
		&i.Status,
		&i.GrantedByUserID,
		&i.StripeMode,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripeScheduleID,
		&i.StripeCheckoutSessionID,
		&i.CheckoutAttempt,
		&i.GrantedAt,
		&i.ScheduledStartAt,
		&i.StartedAt,
		&i.EndsAt,
		&i.ActivatedAt,
		&i.CanceledAt,
		&i.RevokedAt,
		&i.SupersededAt,
		&i.CompletedAt,
		&i.SupersededByPlanID,
		&i.FailureCode,
		&i.FailureMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOpenWorkspaceTrialGrant = `-- name: GetOpenWorkspaceTrialGrant :one
SELECT id, workspace_id, kind, plan_id, duration_days, status, granted_by_user_id, stripe_mode, stripe_customer_id, stripe_subscription_id, stripe_schedule_id, stripe_checkout_session_id, checkout_attempt, granted_at, scheduled_start_at, started_at, ends_at, activated_at, canceled_at, revoked_at, superseded_at, completed_at, superseded_by_plan_id, failure_code, failure_message, created_at, updated_at
FROM workspace_trial_grants
WHERE workspace_id = $1
  AND status IN ('provisioning', 'pending_activation', 'checkout_pending', 'scheduled', 'active')
`

func (q *Queries) GetOpenWorkspaceTrialGrant(ctx context.Context, workspaceID string) (WorkspaceTrialGrant, error) {
	row := q.db.QueryRow(ctx, getOpenWorkspaceTrialGrant, workspaceID)
	var i WorkspaceTrialGrant
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.PlanID,
		&i.DurationDays,
		&i.Status,
		&i.GrantedByUserID,
		&i.StripeMode,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripeScheduleID,
		&i.StripeCheckoutSessionID,
		&i.CheckoutAttempt,
		&i.GrantedAt,
		&i.ScheduledStartAt,
		&i.StartedAt,
		&i.EndsAt,
		&i.ActivatedAt,
		&i.CanceledAt,
		&i.RevokedAt,
		&i.SupersededAt,
		&i.CompletedAt,
		&i.SupersededByPlanID,
		&i.FailureCode,
		&i.FailureMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceTrialGrant = `-- name: GetWorkspaceTrialGrant :one
SELECT id, workspace_id, kind, plan_id, duration_days, status, granted_by_user_id, stripe_mode, stripe_customer_id, stripe_subscription_id, stripe_schedule_id, stripe_checkout_session_id, checkout_attempt, granted_at, scheduled_start_at, started_at, ends_at, activated_at, canceled_at, revoked_at, superseded_at, completed_at, superseded_by_plan_id, failure_code, failure_message, created_at, updated_at
FROM workspace_trial_grants
WHERE id = $1
`

func (q *Queries) GetWorkspaceTrialGrant(ctx context.Context, id string) (WorkspaceTrialGrant, error) {
	row := q.db.QueryRow(ctx, getWorkspaceTrialGrant, id)
	var i WorkspaceTrialGrant
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.PlanID,
		&i.DurationDays,
		&i.Status,
		&i.GrantedByUserID,
		&i.StripeMode,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripeScheduleID,
		&i.StripeCheckoutSessionID,
		&i.CheckoutAttempt,
		&i.GrantedAt,
		&i.ScheduledStartAt,
		&i.StartedAt,
		&i.EndsAt,
		&i.ActivatedAt,
		&i.CanceledAt,
		&i.RevokedAt,
		&i.SupersededAt,
		&i.CompletedAt,
		&i.SupersededByPlanID,
		&i.FailureCode,
		&i.FailureMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceTrialGrantByCheckoutSession = `-- name: GetWorkspaceTrialGrantByCheckoutSession :one
SELECT id, workspace_id, kind, plan_id, duration_days, status, granted_by_user_id, stripe_mode, stripe_customer_id, stripe_subscription_id, stripe_schedule_id, stripe_checkout_session_id, checkout_attempt, granted_at, scheduled_start_at, started_at, ends_at, activated_at, canceled_at, revoked_at, superseded_at, completed_at, superseded_by_plan_id, failure_code, failure_message, created_at, updated_at
FROM workspace_trial_grants
WHERE stripe_checkout_session_id = $1
`

func (q *Queries) GetWorkspaceTrialGrantByCheckoutSession(ctx context.Context, stripeCheckoutSessionID pgtype.Text) (WorkspaceTrialGrant, error) {
	row := q.db.QueryRow(ctx, getWorkspaceTrialGrantByCheckoutSession, stripeCheckoutSessionID)
	var i WorkspaceTrialGrant
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.PlanID,
		&i.DurationDays,
		&i.Status,
		&i.GrantedByUserID,
		&i.StripeMode,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripeScheduleID,
		&i.StripeCheckoutSessionID,
		&i.CheckoutAttempt,
		&i.GrantedAt,
		&i.ScheduledStartAt,
		&i.StartedAt,
		&i.EndsAt,
		&i.ActivatedAt,
		&i.CanceledAt,
		&i.RevokedAt,
		&i.SupersededAt,
		&i.CompletedAt,
		&i.SupersededByPlanID,
		&i.FailureCode,
		&i.FailureMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceTrialGrantBySchedule = `-- name: GetWorkspaceTrialGrantBySchedule :one
SELECT id, workspace_id, kind, plan_id, duration_days, status, granted_by_user_id, stripe_mode, stripe_customer_id, stripe_subscription_id, stripe_schedule_id, stripe_checkout_session_id, checkout_attempt, granted_at, scheduled_start_at, started_at, ends_at, activated_at, canceled_at, revoked_at, superseded_at, completed_at, superseded_by_plan_id, failure_code, failure_message, created_at, updated_at
FROM workspace_trial_grants
WHERE stripe_schedule_id = $1
ORDER BY granted_at DESC
LIMIT 1
`

func (q *Queries) GetWorkspaceTrialGrantBySchedule(ctx context.Context, stripeScheduleID pgtype.Text) (WorkspaceTrialGrant, error) {
	row := q.db.QueryRow(ctx, getWorkspaceTrialGrantBySchedule, stripeScheduleID)
	var i WorkspaceTrialGrant
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.PlanID,
		&i.DurationDays,
		&i.Status,
		&i.GrantedByUserID,
		&i.StripeMode,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripeScheduleID,
		&i.StripeCheckoutSessionID,
		&i.CheckoutAttempt,
		&i.GrantedAt,
		&i.ScheduledStartAt,
		&i.StartedAt,
		&i.EndsAt,
		&i.ActivatedAt,
		&i.CanceledAt,
		&i.RevokedAt,
		&i.SupersededAt,
		&i.CompletedAt,
		&i.SupersededByPlanID,
		&i.FailureCode,
		&i.FailureMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceTrialGrantBySubscription = `-- name: GetWorkspaceTrialGrantBySubscription :one
SELECT id, workspace_id, kind, plan_id, duration_days, status, granted_by_user_id, stripe_mode, stripe_customer_id, stripe_subscription_id, stripe_schedule_id, stripe_checkout_session_id, checkout_attempt, granted_at, scheduled_start_at, started_at, ends_at, activated_at, canceled_at, revoked_at, superseded_at, completed_at, superseded_by_plan_id, failure_code, failure_message, created_at, updated_at
FROM workspace_trial_grants
WHERE stripe_subscription_id = $1
ORDER BY granted_at DESC
LIMIT 1
`

func (q *Queries) GetWorkspaceTrialGrantBySubscription(ctx context.Context, stripeSubscriptionID pgtype.Text) (WorkspaceTrialGrant, error) {
	row := q.db.QueryRow(ctx, getWorkspaceTrialGrantBySubscription, stripeSubscriptionID)
	var i WorkspaceTrialGrant
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.PlanID,
		&i.DurationDays,
		&i.Status,
		&i.GrantedByUserID,
		&i.StripeMode,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripeScheduleID,
		&i.StripeCheckoutSessionID,
		&i.CheckoutAttempt,
		&i.GrantedAt,
		&i.ScheduledStartAt,
		&i.StartedAt,
		&i.EndsAt,
		&i.ActivatedAt,
		&i.CanceledAt,
		&i.RevokedAt,
		&i.SupersededAt,
		&i.CompletedAt,
		&i.SupersededByPlanID,
		&i.FailureCode,
		&i.FailureMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkspaceTrialGrantHistory = `-- name: ListWorkspaceTrialGrantHistory :many
SELECT id, workspace_id, kind, plan_id, duration_days, status, granted_by_user_id, stripe_mode, stripe_customer_id, stripe_subscription_id, stripe_schedule_id, stripe_checkout_session_id, checkout_attempt, granted_at, scheduled_start_at, started_at, ends_at, activated_at, canceled_at, revoked_at, superseded_at, completed_at, superseded_by_plan_id, failure_code, failure_message, created_at, updated_at
FROM workspace_trial_grants
WHERE workspace_id = $1
ORDER BY granted_at DESC, id DESC
`

func (q *Queries) ListWorkspaceTrialGrantHistory(ctx context.Context, workspaceID string) ([]WorkspaceTrialGrant, error) {
	rows, err := q.db.Query(ctx, listWorkspaceTrialGrantHistory, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceTrialGrant{}
	for rows.Next() {
		var i WorkspaceTrialGrant
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Kind,
			&i.PlanID,
			&i.DurationDays,
			&i.Status,
			&i.GrantedByUserID,
			&i.StripeMode,
			&i.StripeCustomerID,
			&i.StripeSubscriptionID,
			&i.StripeScheduleID,
			&i.StripeCheckoutSessionID,
			&i.CheckoutAttempt,
			&i.GrantedAt,
			&i.ScheduledStartAt,
			&i.StartedAt,
			&i.EndsAt,
			&i.ActivatedAt,
			&i.CanceledAt,
			&i.RevokedAt,
			&i.SupersededAt,
			&i.CompletedAt,
			&i.SupersededByPlanID,
			&i.FailureCode,
			&i.FailureMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWorkspaceTrialGrantActive = `-- name: MarkWorkspaceTrialGrantActive :one
UPDATE workspace_trial_grants
SET status = 'active',
    stripe_customer_id = $1,
    stripe_subscription_id = $2,
    started_at = $3,
    ends_at = $4,
    activated_at = $5,
    failure_code = NULL,
    failure_message = NULL,
    updated_at = NOW()
WHERE id = $6
  AND status = $7
RETURNING id, workspace_id, kind, plan_id, duration_days, status, granted_by_user_id, stripe_mode, stripe_customer_id, stripe_subscription_id, stripe_schedule_id, stripe_checkout_session_id, checkout_attempt, granted_at, scheduled_start_at, started_at, ends_at, activated_at, canceled_at, revoked_at, superseded_at, completed_at, superseded_by_plan_id, failure_code, failure_message, created_at, updated_at
`

type MarkWorkspaceTrialGrantActiveParams struct {
	StripeCustomerID     pgtype.Text        `json:"stripe_customer_id"`
	StripeSubscriptionID pgtype.Text        `json:"stripe_subscription_id"`
	StartedAt            pgtype.Timestamptz `json:"started_at"`
	EndsAt               pgtype.Timestamptz `json:"ends_at"`
	ActivatedAt          pgtype.Timestamptz `json:"activated_at"`
	ID                   string             `json:"id"`
	ExpectedStatus       string             `json:"expected_status"`
}

func (q *Queries) MarkWorkspaceTrialGrantActive(ctx context.Context, arg MarkWorkspaceTrialGrantActiveParams) (WorkspaceTrialGrant, error) {
	row := q.db.QueryRow(ctx, markWorkspaceTrialGrantActive,
		arg.StripeCustomerID,
		arg.StripeSubscriptionID,
		arg.StartedAt,
		arg.EndsAt,
		arg.ActivatedAt,
		arg.ID,
		arg.ExpectedStatus,
	)
	var i WorkspaceTrialGrant
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.PlanID,
		&i.DurationDays,
		&i.Status,
		&i.GrantedByUserID,
		&i.StripeMode,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripeScheduleID,
		&i.StripeCheckoutSessionID,
		&i.CheckoutAttempt,
		&i.GrantedAt,
		&i.ScheduledStartAt,
		&i.StartedAt,
		&i.EndsAt,
		&i.ActivatedAt,
		&i.CanceledAt,
		&i.RevokedAt,
		&i.SupersededAt,
		&i.CompletedAt,
		&i.SupersededByPlanID,
		&i.FailureCode,
		&i.FailureMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markWorkspaceTrialGrantCanceled = `-- name: MarkWorkspaceTrialGrantCanceled :one
UPDATE workspace_trial_grants
SET status = 'canceled',
    canceled_at = $1,
    updated_at = NOW()
WHERE id = $2
  AND status = $3
RETURNING id, workspace_id, kind, plan_id, duration_days, status, granted_by_user_id, stripe_mode, stripe_customer_id, stripe_subscription_id, stripe_schedule_id, stripe_checkout_session_id, checkout_attempt, granted_at, scheduled_start_at, started_at, ends_at, activated_at, canceled_at, revoked_at, superseded_at, completed_at, superseded_by_plan_id, failure_code, failure_message, created_at, updated_at
`

type MarkWorkspaceTrialGrantCanceledParams struct {
	CanceledAt     pgtype.Timestamptz `json:"canceled_at"`
	ID             string             `json:"id"`
	ExpectedStatus string             `json:"expected_status"`
}

func (q *Queries) MarkWorkspaceTrialGrantCanceled(ctx context.Context, arg MarkWorkspaceTrialGrantCanceledParams) (WorkspaceTrialGrant, error) {
	row := q.db.QueryRow(ctx, markWorkspaceTrialGrantCanceled, arg.CanceledAt, arg.ID, arg.ExpectedStatus)
	var i WorkspaceTrialGrant
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.PlanID,
		&i.DurationDays,
		&i.Status,
		&i.GrantedByUserID,
		&i.StripeMode,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripeScheduleID,
		&i.StripeCheckoutSessionID,
		&i.CheckoutAttempt,
		&i.GrantedAt,
		&i.ScheduledStartAt,
		&i.StartedAt,
		&i.EndsAt,
		&i.ActivatedAt,
		&i.CanceledAt,
		&i.RevokedAt,
		&i.SupersededAt,
		&i.CompletedAt,
		&i.SupersededByPlanID,
		&i.FailureCode,
		&i.FailureMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markWorkspaceTrialGrantCompleted = `-- name: MarkWorkspaceTrialGrantCompleted :one
UPDATE workspace_trial_grants
SET status = 'completed',
    completed_at = $1,
    updated_at = NOW()
WHERE id = $2
  AND status = $3
RETURNING id, workspace_id, kind, plan_id, duration_days, status, granted_by_user_id, stripe_mode, stripe_customer_id, stripe_subscription_id, stripe_schedule_id, stripe_checkout_session_id, checkout_attempt, granted_at, scheduled_start_at, started_at, ends_at, activated_at, canceled_at, revoked_at, superseded_at, completed_at, superseded_by_plan_id, failure_code, failure_message, created_at, updated_at
`

type MarkWorkspaceTrialGrantCompletedParams struct {
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	ID             string             `json:"id"`
	ExpectedStatus string             `json:"expected_status"`
}

func (q *Queries) MarkWorkspaceTrialGrantCompleted(ctx context.Context, arg MarkWorkspaceTrialGrantCompletedParams) (WorkspaceTrialGrant, error) {
	row := q.db.QueryRow(ctx, markWorkspaceTrialGrantCompleted, arg.CompletedAt, arg.ID, arg.ExpectedStatus)
	var i WorkspaceTrialGrant
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.PlanID,
		&i.DurationDays,
		&i.Status,
		&i.GrantedByUserID,
		&i.StripeMode,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripeScheduleID,
		&i.StripeCheckoutSessionID,
		&i.CheckoutAttempt,
		&i.GrantedAt,
		&i.ScheduledStartAt,
		&i.StartedAt,
		&i.EndsAt,
		&i.ActivatedAt,
		&i.CanceledAt,
		&i.RevokedAt,
		&i.SupersededAt,
		&i.CompletedAt,
		&i.SupersededByPlanID,
		&i.FailureCode,
		&i.FailureMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markWorkspaceTrialGrantFailed = `-- name: MarkWorkspaceTrialGrantFailed :one
UPDATE workspace_trial_grants
SET status = 'failed',
    failure_code = $1,
    failure_message = $2,
    updated_at = NOW()
WHERE id = $3
  AND status = $4
RETURNING id, workspace_id, kind, plan_id, duration_days, status, granted_by_user_id, stripe_mode, stripe_customer_id, stripe_subscription_id, stripe_schedule_id, stripe_checkout_session_id, checkout_attempt, granted_at, scheduled_start_at, started_at, ends_at, activated_at, canceled_at, revoked_at, superseded_at, completed_at, superseded_by_plan_id, failure_code, failure_message, created_at, updated_at
`

type MarkWorkspaceTrialGrantFailedParams struct {
	FailureCode    pgtype.Text `json:"failure_code"`
	FailureMessage pgtype.Text `json:"failure_message"`
	ID             string      `json:"id"`
	ExpectedStatus string      `json:"expected_status"`
}

func (q *Queries) MarkWorkspaceTrialGrantFailed(ctx context.Context, arg MarkWorkspaceTrialGrantFailedParams) (WorkspaceTrialGrant, error) {
	row := q.db.QueryRow(ctx, markWorkspaceTrialGrantFailed,
		arg.FailureCode,
		arg.FailureMessage,
		arg.ID,
		arg.ExpectedStatus,
	)
	var i WorkspaceTrialGrant
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.PlanID,
		&i.DurationDays,
		&i.Status,
		&i.GrantedByUserID,
		&i.StripeMode,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripeScheduleID,
		&i.StripeCheckoutSessionID,
		&i.CheckoutAttempt,
		&i.GrantedAt,
		&i.ScheduledStartAt,
		&i.StartedAt,
		&i.EndsAt,
		&i.ActivatedAt,
		&i.CanceledAt,
		&i.RevokedAt,
		&i.SupersededAt,
		&i.CompletedAt,
		&i.SupersededByPlanID,
		&i.FailureCode,
		&i.FailureMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markWorkspaceTrialGrantRevoked = `-- name: MarkWorkspaceTrialGrantRevoked :one
UPDATE workspace_trial_grants
SET status = 'revoked',
    revoked_at = $1,
    updated_at = NOW()
WHERE id = $2
  AND status = $3
RETURNING id, workspace_id, kind, plan_id, duration_days, status, granted_by_user_id, stripe_mode, stripe_customer_id, stripe_subscription_id, stripe_schedule_id, stripe_checkout_session_id, checkout_attempt, granted_at, scheduled_start_at, started_at, ends_at, activated_at, canceled_at, revoked_at, superseded_at, completed_at, superseded_by_plan_id, failure_code, failure_message, created_at, updated_at
`

type MarkWorkspaceTrialGrantRevokedParams struct {
	RevokedAt      pgtype.Timestamptz `json:"revoked_at"`
	ID             string             `json:"id"`
	ExpectedStatus string             `json:"expected_status"`
}

func (q *Queries) MarkWorkspaceTrialGrantRevoked(ctx context.Context, arg MarkWorkspaceTrialGrantRevokedParams) (WorkspaceTrialGrant, error) {
	row := q.db.QueryRow(ctx, markWorkspaceTrialGrantRevoked, arg.RevokedAt, arg.ID, arg.ExpectedStatus)
	var i WorkspaceTrialGrant
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.PlanID,
		&i.DurationDays,
		&i.Status,
		&i.GrantedByUserID,
		&i.StripeMode,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripeScheduleID,
		&i.StripeCheckoutSessionID,
		&i.CheckoutAttempt,
		&i.GrantedAt,
		&i.ScheduledStartAt,
		&i.StartedAt,
		&i.EndsAt,
		&i.ActivatedAt,
		&i.CanceledAt,
		&i.RevokedAt,
		&i.SupersededAt,
		&i.CompletedAt,
		&i.SupersededByPlanID,
		&i.FailureCode,
		&i.FailureMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markWorkspaceTrialGrantScheduled = `-- name: MarkWorkspaceTrialGrantScheduled :one
UPDATE workspace_trial_grants
SET status = 'scheduled',
    stripe_customer_id = $1,
    stripe_subscription_id = $2,
    stripe_schedule_id = $3,
    scheduled_start_at = $4,
    ends_at = $5,
    failure_code = NULL,
    failure_message = NULL,
    updated_at = NOW()
WHERE id = $6
  AND status = $7
RETURNING id, workspace_id, kind, plan_id, duration_days, status, granted_by_user_id, stripe_mode, stripe_customer_id, stripe_subscription_id, stripe_schedule_id, stripe_checkout_session_id, checkout_attempt, granted_at, scheduled_start_at, started_at, ends_at, activated_at, canceled_at, revoked_at, superseded_at, completed_at, superseded_by_plan_id, failure_code, failure_message, created_at, updated_at
`

type MarkWorkspaceTrialGrantScheduledParams struct {
	StripeCustomerID     pgtype.Text        `json:"stripe_customer_id"`
	StripeSubscriptionID pgtype.Text        `json:"stripe_subscription_id"`
	StripeScheduleID     pgtype.Text        `json:"stripe_schedule_id"`
	ScheduledStartAt     pgtype.Timestamptz `json:"scheduled_start_at"`
	EndsAt               pgtype.Timestamptz `json:"ends_at"`
	ID                   string             `json:"id"`
	ExpectedStatus       string             `json:"expected_status"`
}

func (q *Queries) MarkWorkspaceTrialGrantScheduled(ctx context.Context, arg MarkWorkspaceTrialGrantScheduledParams) (WorkspaceTrialGrant, error) {
	row := q.db.QueryRow(ctx, markWorkspaceTrialGrantScheduled,
		arg.StripeCustomerID,
		arg.StripeSubscriptionID,
		arg.StripeScheduleID,
		arg.ScheduledStartAt,
		arg.EndsAt,
		arg.ID,
		arg.ExpectedStatus,
	)
	var i WorkspaceTrialGrant
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.PlanID,
		&i.DurationDays,
		&i.Status,
		&i.GrantedByUserID,
		&i.StripeMode,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripeScheduleID,
		&i.StripeCheckoutSessionID,
		&i.CheckoutAttempt,
		&i.GrantedAt,
		&i.ScheduledStartAt,
		&i.StartedAt,
		&i.EndsAt,
		&i.ActivatedAt,
		&i.CanceledAt,
		&i.RevokedAt,
		&i.SupersededAt,
		&i.CompletedAt,
		&i.SupersededByPlanID,
		&i.FailureCode,
		&i.FailureMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markWorkspaceTrialGrantSuperseded = `-- name: MarkWorkspaceTrialGrantSuperseded :one
UPDATE workspace_trial_grants
SET status = 'superseded',
    superseded_at = $1,
    superseded_by_plan_id = $2,
    updated_at = NOW()
WHERE id = $3
  AND status = $4
RETURNING id, workspace_id, kind, plan_id, duration_days, status, granted_by_user_id, stripe_mode, stripe_customer_id, stripe_subscription_id, stripe_schedule_id, stripe_checkout_session_id, checkout_attempt, granted_at, scheduled_start_at, started_at, ends_at, activated_at, canceled_at, revoked_at, superseded_at, completed_at, superseded_by_plan_id, failure_code, failure_message, created_at, updated_at
`

type MarkWorkspaceTrialGrantSupersededParams struct {
	SupersededAt       pgtype.Timestamptz `json:"superseded_at"`
	SupersededByPlanID pgtype.Text        `json:"superseded_by_plan_id"`
	ID                 string             `json:"id"`
	ExpectedStatus     string             `json:"expected_status"`
}

func (q *Queries) MarkWorkspaceTrialGrantSuperseded(ctx context.Context, arg MarkWorkspaceTrialGrantSupersededParams) (WorkspaceTrialGrant, error) {
	row := q.db.QueryRow(ctx, markWorkspaceTrialGrantSuperseded,
		arg.SupersededAt,
		arg.SupersededByPlanID,
		arg.ID,
		arg.ExpectedStatus,
	)
	var i WorkspaceTrialGrant
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.PlanID,
		&i.DurationDays,
		&i.Status,
		&i.GrantedByUserID,
		&i.StripeMode,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripeScheduleID,
		&i.StripeCheckoutSessionID,
		&i.CheckoutAttempt,
		&i.GrantedAt,
		&i.ScheduledStartAt,
		&i.StartedAt,
		&i.EndsAt,
		&i.ActivatedAt,
		&i.CanceledAt,
		&i.RevokedAt,
		&i.SupersededAt,
		&i.CompletedAt,
		&i.SupersededByPlanID,
		&i.FailureCode,
		&i.FailureMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordWorkspaceTrialGrantCheckoutSession = `-- name: RecordWorkspaceTrialGrantCheckoutSession :one
UPDATE workspace_trial_grants
SET stripe_checkout_session_id = $1,
    updated_at = NOW()
WHERE id = $2
  AND status = 'checkout_pending'
  AND stripe_checkout_session_id IS NULL
  AND checkout_attempt = $3
RETURNING id, workspace_id, kind, plan_id, duration_days, status, granted_by_user_id, stripe_mode, stripe_customer_id, stripe_subscription_id, stripe_schedule_id, stripe_checkout_session_id, checkout_attempt, granted_at, scheduled_start_at, started_at, ends_at, activated_at, canceled_at, revoked_at, superseded_at, completed_at, superseded_by_plan_id, failure_code, failure_message, created_at, updated_at
`

type RecordWorkspaceTrialGrantCheckoutSessionParams struct {
	StripeCheckoutSessionID pgtype.Text `json:"stripe_checkout_session_id"`
	ID                      string      `json:"id"`
	ExpectedCheckoutAttempt int32       `json:"expected_checkout_attempt"`
}

func (q *Queries) RecordWorkspaceTrialGrantCheckoutSession(ctx context.Context, arg RecordWorkspaceTrialGrantCheckoutSessionParams) (WorkspaceTrialGrant, error) {
	row := q.db.QueryRow(ctx, recordWorkspaceTrialGrantCheckoutSession, arg.StripeCheckoutSessionID, arg.ID, arg.ExpectedCheckoutAttempt)
	var i WorkspaceTrialGrant
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.PlanID,
		&i.DurationDays,
		&i.Status,
		&i.GrantedByUserID,
		&i.StripeMode,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripeScheduleID,
		&i.StripeCheckoutSessionID,
		&i.CheckoutAttempt,
		&i.GrantedAt,
		&i.ScheduledStartAt,
		&i.StartedAt,
		&i.EndsAt,
		&i.ActivatedAt,
		&i.CanceledAt,
		&i.RevokedAt,
		&i.SupersededAt,
		&i.CompletedAt,
		&i.SupersededByPlanID,
		&i.FailureCode,
		&i.FailureMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordWorkspaceTrialGrantProvisioningSchedule = `-- name: RecordWorkspaceTrialGrantProvisioningSchedule :one
UPDATE workspace_trial_grants
SET stripe_schedule_id = COALESCE($1, stripe_schedule_id),
    failure_code = $2,
    failure_message = $3,
    updated_at = NOW()
WHERE id = $4
  AND status = 'provisioning'
  AND ($1 IS NULL OR stripe_schedule_id IS NULL OR stripe_schedule_id = $1)
RETURNING id, workspace_id, kind, plan_id, duration_days, status, granted_by_user_id, stripe_mode, stripe_customer_id, stripe_subscription_id, stripe_schedule_id, stripe_checkout_session_id, checkout_attempt, granted_at, scheduled_start_at, started_at, ends_at, activated_at, canceled_at, revoked_at, superseded_at, completed_at, superseded_by_plan_id, failure_code, failure_message, created_at, updated_at
`

type RecordWorkspaceTrialGrantProvisioningScheduleParams struct {
	StripeScheduleID pgtype.Text `json:"stripe_schedule_id"`
	FailureCode      pgtype.Text `json:"failure_code"`
	FailureMessage   pgtype.Text `json:"failure_message"`
	ID               string      `json:"id"`
}

func (q *Queries) RecordWorkspaceTrialGrantProvisioningSchedule(ctx context.Context, arg RecordWorkspaceTrialGrantProvisioningScheduleParams) (WorkspaceTrialGrant, error) {
	row := q.db.QueryRow(ctx, recordWorkspaceTrialGrantProvisioningSchedule,
		arg.StripeScheduleID,
		arg.FailureCode,
		arg.FailureMessage,
		arg.ID,
	)
	var i WorkspaceTrialGrant
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.PlanID,
		&i.DurationDays,
		&i.Status,
		&i.GrantedByUserID,
		&i.StripeMode,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripeScheduleID,
		&i.StripeCheckoutSessionID,
		&i.CheckoutAttempt,
		&i.GrantedAt,
		&i.ScheduledStartAt,
		&i.StartedAt,
		&i.EndsAt,
		&i.ActivatedAt,
		&i.CanceledAt,
		&i.RevokedAt,
		&i.SupersededAt,
		&i.CompletedAt,
		&i.SupersededByPlanID,
		&i.FailureCode,
		&i.FailureMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordWorkspaceTrialGrantRenewalCancellation = `-- name: RecordWorkspaceTrialGrantRenewalCancellation :one
UPDATE workspace_trial_grants
SET canceled_at = $1,
    updated_at = NOW()
WHERE id = $2
  AND status = 'active'
RETURNING id, workspace_id, kind, plan_id, duration_days, status, granted_by_user_id, stripe_mode, stripe_customer_id, stripe_subscription_id, stripe_schedule_id, stripe_checkout_session_id, checkout_attempt, granted_at, scheduled_start_at, started_at, ends_at, activated_at, canceled_at, revoked_at, superseded_at, completed_at, superseded_by_plan_id, failure_code, failure_message, created_at, updated_at
`

type RecordWorkspaceTrialGrantRenewalCancellationParams struct {
	CanceledAt pgtype.Timestamptz `json:"canceled_at"`
	ID         string             `json:"id"`
}

func (q *Queries) RecordWorkspaceTrialGrantRenewalCancellation(ctx context.Context, arg RecordWorkspaceTrialGrantRenewalCancellationParams) (WorkspaceTrialGrant, error) {
	row := q.db.QueryRow(ctx, recordWorkspaceTrialGrantRenewalCancellation, arg.CanceledAt, arg.ID)
	var i WorkspaceTrialGrant
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.PlanID,
		&i.DurationDays,
		&i.Status,
		&i.GrantedByUserID,
		&i.StripeMode,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripeScheduleID,
		&i.StripeCheckoutSessionID,
		&i.CheckoutAttempt,
		&i.GrantedAt,
		&i.ScheduledStartAt,
		&i.StartedAt,
		&i.EndsAt,
		&i.ActivatedAt,
		&i.CanceledAt,
		&i.RevokedAt,
		&i.SupersededAt,
		&i.CompletedAt,
		&i.SupersededByPlanID,
		&i.FailureCode,
		&i.FailureMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const releaseExpiredWorkspaceTrialGrantCheckout = `-- name: ReleaseExpiredWorkspaceTrialGrantCheckout :one
UPDATE workspace_trial_grants
SET status = 'pending_activation',
    stripe_checkout_session_id = NULL,
    updated_at = NOW()
WHERE id = $1
  AND status = 'checkout_pending'
  AND stripe_checkout_session_id = $2
  AND updated_at < $3
RETURNING id, workspace_id, kind, plan_id, duration_days, status, granted_by_user_id, stripe_mode, stripe_customer_id, stripe_subscription_id, stripe_schedule_id, stripe_checkout_session_id, checkout_attempt, granted_at, scheduled_start_at, started_at, ends_at, activated_at, canceled_at, revoked_at, superseded_at, completed_at, superseded_by_plan_id, failure_code, failure_message, created_at, updated_at
`

type ReleaseExpiredWorkspaceTrialGrantCheckoutParams struct {
	ID                      string             `json:"id"`
	StripeCheckoutSessionID pgtype.Text        `json:"stripe_checkout_session_id"`
	ExpiredBefore           pgtype.Timestamptz `json:"expired_before"`
}

func (q *Queries) ReleaseExpiredWorkspaceTrialGrantCheckout(ctx context.Context, arg ReleaseExpiredWorkspaceTrialGrantCheckoutParams) (WorkspaceTrialGrant, error) {
	row := q.db.QueryRow(ctx, releaseExpiredWorkspaceTrialGrantCheckout, arg.ID, arg.StripeCheckoutSessionID, arg.ExpiredBefore)
	var i WorkspaceTrialGrant
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.PlanID,
		&i.DurationDays,
		&i.Status,
		&i.GrantedByUserID,
		&i.StripeMode,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripeScheduleID,
		&i.StripeCheckoutSessionID,
		&i.CheckoutAttempt,
		&i.GrantedAt,
		&i.ScheduledStartAt,
		&i.StartedAt,
		&i.EndsAt,
		&i.ActivatedAt,
		&i.CanceledAt,
		&i.RevokedAt,
		&i.SupersededAt,
		&i.CompletedAt,
		&i.SupersededByPlanID,
		&i.FailureCode,
		&i.FailureMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reopenUnrecordedWorkspaceTrialGrantCheckout = `-- name: ReopenUnrecordedWorkspaceTrialGrantCheckout :one
UPDATE workspace_trial_grants
SET status = 'pending_activation',
    updated_at = NOW()
WHERE id = $1
  AND status = 'checkout_pending'
  AND stripe_checkout_session_id IS NULL
  AND checkout_attempt = $2
RETURNING id, workspace_id, kind, plan_id, duration_days, status, granted_by_user_id, stripe_mode, stripe_customer_id, stripe_subscription_id, stripe_schedule_id, stripe_checkout_session_id, checkout_attempt, granted_at, scheduled_start_at, started_at, ends_at, activated_at, canceled_at, revoked_at, superseded_at, completed_at, superseded_by_plan_id, failure_code, failure_message, created_at, updated_at
`

type ReopenUnrecordedWorkspaceTrialGrantCheckoutParams struct {
	ID                      string `json:"id"`
	ExpectedCheckoutAttempt int32  `json:"expected_checkout_attempt"`
}

func (q *Queries) ReopenUnrecordedWorkspaceTrialGrantCheckout(ctx context.Context, arg ReopenUnrecordedWorkspaceTrialGrantCheckoutParams) (WorkspaceTrialGrant, error) {
	row := q.db.QueryRow(ctx, reopenUnrecordedWorkspaceTrialGrantCheckout, arg.ID, arg.ExpectedCheckoutAttempt)
	var i WorkspaceTrialGrant
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.PlanID,
		&i.DurationDays,
		&i.Status,
		&i.GrantedByUserID,
		&i.StripeMode,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripeScheduleID,
		&i.StripeCheckoutSessionID,
		&i.CheckoutAttempt,
		&i.GrantedAt,
		&i.ScheduledStartAt,
		&i.StartedAt,
		&i.EndsAt,
		&i.ActivatedAt,
		&i.CanceledAt,
		&i.RevokedAt,
		&i.SupersededAt,
		&i.CompletedAt,
		&i.SupersededByPlanID,
		&i.FailureCode,
		&i.FailureMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const transitionWorkspaceTrialGrantStatus = `-- name: TransitionWorkspaceTrialGrantStatus :one
UPDATE workspace_trial_grants
SET status = $1,
    updated_at = NOW()
WHERE id = $2
  AND status = $3
RETURNING id, workspace_id, kind, plan_id, duration_days, status, granted_by_user_id, stripe_mode, stripe_customer_id, stripe_subscription_id, stripe_schedule_id, stripe_checkout_session_id, checkout_attempt, granted_at, scheduled_start_at, started_at, ends_at, activated_at, canceled_at, revoked_at, superseded_at, completed_at, superseded_by_plan_id, failure_code, failure_message, created_at, updated_at
`

type TransitionWorkspaceTrialGrantStatusParams struct {
	NewStatus      string `json:"new_status"`
	ID             string `json:"id"`
	ExpectedStatus string `json:"expected_status"`
}

func (q *Queries) TransitionWorkspaceTrialGrantStatus(ctx context.Context, arg TransitionWorkspaceTrialGrantStatusParams) (WorkspaceTrialGrant, error) {
	row := q.db.QueryRow(ctx, transitionWorkspaceTrialGrantStatus, arg.NewStatus, arg.ID, arg.ExpectedStatus)
	var i WorkspaceTrialGrant
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.PlanID,
		&i.DurationDays,
		&i.Status,
		&i.GrantedByUserID,
		&i.StripeMode,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripeScheduleID,
		&i.StripeCheckoutSessionID,
		&i.CheckoutAttempt,
		&i.GrantedAt,
		&i.ScheduledStartAt,
		&i.StartedAt,
		&i.EndsAt,
		&i.ActivatedAt,
		&i.CanceledAt,
		&i.RevokedAt,
		&i.SupersededAt,
		&i.CompletedAt,
		&i.SupersededByPlanID,
		&i.FailureCode,
		&i.FailureMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
