// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: x_inbox.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteXInboxDeliveryResource = `-- name: DeleteXInboxDeliveryResource :exec
DELETE FROM x_inbox_delivery_resources
WHERE social_account_id = $1
`

func (q *Queries) DeleteXInboxDeliveryResource(ctx context.Context, socialAccountID string) error {
	_, err := q.db.Exec(ctx, deleteXInboxDeliveryResource, socialAccountID)
	return err
}

const getXInboxDeliveryResource = `-- name: GetXInboxDeliveryResource :one
SELECT social_account_id, filtered_stream_rule_id, activity_dm_subscription_id, delivery_status, last_error, last_synced_at, created_at, updated_at FROM x_inbox_delivery_resources
WHERE social_account_id = $1
`

func (q *Queries) GetXInboxDeliveryResource(ctx context.Context, socialAccountID string) (XInboxDeliveryResource, error) {
	row := q.db.QueryRow(ctx, getXInboxDeliveryResource, socialAccountID)
	var i XInboxDeliveryResource
	err := row.Scan(
		&i.SocialAccountID,
		&i.FilteredStreamRuleID,
		&i.ActivityDmSubscriptionID,
		&i.DeliveryStatus,
		&i.LastError,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateXInboxDeliveryResource = `-- name: UpdateXInboxDeliveryResource :one
UPDATE x_inbox_delivery_resources
SET filtered_stream_rule_id = $2,
    activity_dm_subscription_id = $3,
    delivery_status = $4,
    last_error = $5,
    last_synced_at = $6,
    updated_at = NOW()
WHERE social_account_id = $1
RETURNING social_account_id, filtered_stream_rule_id, activity_dm_subscription_id, delivery_status, last_error, last_synced_at, created_at, updated_at
`

type UpdateXInboxDeliveryResourceParams struct {
	SocialAccountID          string             `json:"social_account_id"`
	FilteredStreamRuleID     pgtype.Text        `json:"filtered_stream_rule_id"`
	ActivityDmSubscriptionID pgtype.Text        `json:"activity_dm_subscription_id"`
	DeliveryStatus           string             `json:"delivery_status"`
	LastError                pgtype.Text        `json:"last_error"`
	LastSyncedAt             pgtype.Timestamptz `json:"last_synced_at"`
}

func (q *Queries) UpdateXInboxDeliveryResource(ctx context.Context, arg UpdateXInboxDeliveryResourceParams) (XInboxDeliveryResource, error) {
	row := q.db.QueryRow(ctx, updateXInboxDeliveryResource,
		arg.SocialAccountID,
		arg.FilteredStreamRuleID,
		arg.ActivityDmSubscriptionID,
		arg.DeliveryStatus,
		arg.LastError,
		arg.LastSyncedAt,
	)
	var i XInboxDeliveryResource
	err := row.Scan(
		&i.SocialAccountID,
		&i.FilteredStreamRuleID,
		&i.ActivityDmSubscriptionID,
		&i.DeliveryStatus,
		&i.LastError,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertXInboxDeliveryResource = `-- name: UpsertXInboxDeliveryResource :one
INSERT INTO x_inbox_delivery_resources (
  social_account_id,
  filtered_stream_rule_id,
  activity_dm_subscription_id,
  delivery_status,
  last_error,
  last_synced_at
)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (social_account_id) DO UPDATE
SET filtered_stream_rule_id = EXCLUDED.filtered_stream_rule_id,
    activity_dm_subscription_id = EXCLUDED.activity_dm_subscription_id,
    delivery_status = EXCLUDED.delivery_status,
    last_error = EXCLUDED.last_error,
    last_synced_at = EXCLUDED.last_synced_at,
    updated_at = NOW()
RETURNING social_account_id, filtered_stream_rule_id, activity_dm_subscription_id, delivery_status, last_error, last_synced_at, created_at, updated_at
`

type UpsertXInboxDeliveryResourceParams struct {
	SocialAccountID          string             `json:"social_account_id"`
	FilteredStreamRuleID     pgtype.Text        `json:"filtered_stream_rule_id"`
	ActivityDmSubscriptionID pgtype.Text        `json:"activity_dm_subscription_id"`
	DeliveryStatus           string             `json:"delivery_status"`
	LastError                pgtype.Text        `json:"last_error"`
	LastSyncedAt             pgtype.Timestamptz `json:"last_synced_at"`
}

func (q *Queries) UpsertXInboxDeliveryResource(ctx context.Context, arg UpsertXInboxDeliveryResourceParams) (XInboxDeliveryResource, error) {
	row := q.db.QueryRow(ctx, upsertXInboxDeliveryResource,
		arg.SocialAccountID,
		arg.FilteredStreamRuleID,
		arg.ActivityDmSubscriptionID,
		arg.DeliveryStatus,
		arg.LastError,
		arg.LastSyncedAt,
	)
	var i XInboxDeliveryResource
	err := row.Scan(
		&i.SocialAccountID,
		&i.FilteredStreamRuleID,
		&i.ActivityDmSubscriptionID,
		&i.DeliveryStatus,
		&i.LastError,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
