// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: x_usage.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getXInboundDailyUsage = `-- name: GetXInboundDailyUsage :one
SELECT workspace_id, utc_date, weighted_units_used, weighted_units_limit, events_accepted, events_suppressed, created_at, updated_at
FROM x_inbound_daily_usage
WHERE workspace_id = $1
  AND utc_date = $2
`

type GetXInboundDailyUsageParams struct {
	WorkspaceID string      `json:"workspace_id"`
	UtcDate     pgtype.Date `json:"utc_date"`
}

func (q *Queries) GetXInboundDailyUsage(ctx context.Context, arg GetXInboundDailyUsageParams) (XInboundDailyUsage, error) {
	row := q.db.QueryRow(ctx, getXInboundDailyUsage, arg.WorkspaceID, arg.UtcDate)
	var i XInboundDailyUsage
	err := row.Scan(
		&i.WorkspaceID,
		&i.UtcDate,
		&i.WeightedUnitsUsed,
		&i.WeightedUnitsLimit,
		&i.EventsAccepted,
		&i.EventsSuppressed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getXUsagePeriod = `-- name: GetXUsagePeriod :one
SELECT workspace_id, period_start, period_end, weighted_units_used, weighted_units_limit, created_at, updated_at
FROM x_usage_periods
WHERE workspace_id = $1
  AND period_start = $2
  AND period_end = $3
`

type GetXUsagePeriodParams struct {
	WorkspaceID string             `json:"workspace_id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
}

func (q *Queries) GetXUsagePeriod(ctx context.Context, arg GetXUsagePeriodParams) (XUsagePeriod, error) {
	row := q.db.QueryRow(ctx, getXUsagePeriod, arg.WorkspaceID, arg.PeriodStart, arg.PeriodEnd)
	var i XUsagePeriod
	err := row.Scan(
		&i.WorkspaceID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.WeightedUnitsUsed,
		&i.WeightedUnitsLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProvisionalXUsageEvents = `-- name: ListProvisionalXUsageEvents :many
SELECT id, workspace_id, social_account_id, period_start, period_end, operation_key, catalog_version, source, idempotency_key, weighted_units, status, created_at, updated_at, connection_mode
FROM x_usage_events
WHERE status = 'provisional'
  AND created_at <= $1
ORDER BY created_at ASC
LIMIT $2
`

type ListProvisionalXUsageEventsParams struct {
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Limit     int32              `json:"limit"`
}

func (q *Queries) ListProvisionalXUsageEvents(ctx context.Context, arg ListProvisionalXUsageEventsParams) ([]XUsageEvent, error) {
	rows, err := q.db.Query(ctx, listProvisionalXUsageEvents, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []XUsageEvent{}
	for rows.Next() {
		var i XUsageEvent
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SocialAccountID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.OperationKey,
			&i.CatalogVersion,
			&i.Source,
			&i.IdempotencyKey,
			&i.WeightedUnits,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ConnectionMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
