import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const calendarViewPath = path.join(root, "src/components/posts/calendar/posts-calendar-view.tsx");

test("Posts calendar view keeps the requested calendar controls and drawer integration", async () => {
  const source = await readFile(calendarViewPath, "utf8");

  assert.match(source, /export function PostsCalendarView/);
  assert.match(source, /CreatePostDrawer/);
  assert.match(source, /List View/);
  assert.match(source, /Create \+/);
  assert.match(source, /Day/);
  assert.match(source, /Week/);
  assert.match(source, /Month/);
  assert.match(source, /usePathname,\s*useParams,\s*useRouter,\s*useSearchParams/);
  assert.match(source, /parseCalendarViewMode\(searchParams\.get\("view"\)\)/);
  assert.match(source, /replaceCalendarMode\("day"\)/);
  assert.match(source, /replaceCalendarMode\("week"\)/);
  assert.match(source, /replaceCalendarMode\("month"\)/);
  assert.match(source, /nextParams\.set\("view",\s*mode\)/);
  assert.match(source, /router\.replace\(`\$\{pathname\}\$\{query \? `\?\$\{query\}` : ""\}`,\s*\{\s*scroll:\s*false\s*\}\)/);
  assert.match(source, /renderWeekView/);
  assert.match(source, /renderDayView/);
  assert.match(source, /handleCalendarWheel/);
  assert.match(source, /handleCalendarTouchStart/);
  assert.match(source, /handleCalendarTouchEnd/);
  assert.match(source, /shiftCalendarBySwipe/);
  assert.match(source, /SwipeTransitionState/);
  assert.match(source, /startCalendarSwipeTransition/);
  assert.match(source, /SWIPE_TRANSITION_MS/);
  assert.match(source, /posts-calendar-swipe-viewport/);
  assert.match(source, /posts-calendar-swipe-layer/);
  assert.match(source, /posts-calendar-swipe-from/);
  assert.match(source, /posts-calendar-swipe-to/);
  assert.match(source, /will-change:transform/);
  assert.match(source, /contain:layout paint/);
  assert.match(source, /getAccumulatedWheelNavigationIntent/);
  assert.match(source, /wheelDeltaRef/);
  assert.match(source, /wheelResetTimerRef/);
  assert.match(source, /clearTimeout\(wheelResetTimerRef\.current\)/);
  assert.match(source, /setTimeout\(\(\) => \{/);
  assert.match(source, /shiftCalendarDateBySwipe/);
  assert.match(source, /getSwipeNavigationIntent/);
  assert.match(source, /onTouchStart=\{handleCalendarTouchStart\}/);
  assert.match(source, /onTouchEnd=\{handleCalendarTouchEnd\}/);
  assert.match(source, /formatWeekdayShort\(day\.date\)/);
  assert.match(source, /posts-calendar-week-grid/);
  assert.match(source, /posts-calendar-day-grid/);
  assert.match(source, /posts-calendar-time-scroll/);
  assert.match(source, /timelineStyle/);
  assert.match(source, /getTimedEventTop\(minute,\s*HOUR_HEIGHT\)/);
  assert.match(source, /--calendar-timeline-height/);
  assert.match(source, /--calendar-timed-event-min-height/);
  assert.match(source, /ref=\{attachScrollbarRef \? weekTimeScrollRef : null\}/);
  assert.match(source, /<div className="posts-calendar-time-scroll" style=\{timelineStyle\}>/);
  assert.match(source, /--calendar-time-gutter:76px/);
  assert.match(source, /--calendar-week-day-min:132px/);
  assert.match(source, /--calendar-week-template:var\(--calendar-time-gutter\) repeat\(7,minmax\(var\(--calendar-week-day-min\),1fr\)\)/);
  assert.match(source, /weekScrollbarWidth/);
  assert.match(source, /offsetWidth - node\.clientWidth/);
  assert.match(source, /posts-calendar-week-header-inner/);
  assert.match(source, /posts-calendar-week-scrollbar-spacer/);
  assert.match(source, /\.posts-calendar-week-header\{[^}]*grid-template-columns:minmax\(0,1fr\) var\(--calendar-scrollbar-gutter\)/);
  assert.match(source, /\.posts-calendar-week-header-inner\{[^}]*grid-template-columns:var\(--calendar-week-template\)/);
  assert.match(source, /\.posts-calendar-week-grid \.posts-calendar-time-scroll\{[^}]*grid-template-columns:var\(--calendar-week-template\)/);
  assert.match(source, /\.posts-calendar-week-columns\{[^}]*grid-column:2\/-1/);
  assert.match(source, /\.posts-calendar-all-day-label,[^}]*white-space:nowrap/);
  assert.match(source, /All Status/);
  assert.match(source, /In Progress/);
  assert.match(source, /Cancelled/);
  assert.match(source, /Archived/);
  assert.match(source, /bucketPostByLocalDay/);
  assert.match(source, /buildWeekDays/);
  assert.match(source, /getCalendarPostMinuteOfDay/);
  assert.match(source, /getProfileCalendarColor/);
  assert.match(source, /shouldShowPostForStatusFilter/);
  assert.match(source, /posts-calendar-fullheight/);
  assert.match(source, /resolvedOptions\(\)\.timeZone/);
});

test("Posts calendar details popover anchors to the selected event button", async () => {
  const source = await readFile(calendarViewPath, "utf8");

  assert.match(source, /getAnchoredPopoverPlacement/);
  assert.match(source, /selectedPostTarget/);
  assert.match(source, /handleSelectPost/);
  assert.match(source, /getElementRect/);
  assert.match(source, /getBoundingClientRect\(\)/);
  assert.match(source, /anchorRect=\{selectedPostTarget\.anchorRect\}/);
  assert.match(source, /data-side=\{placement\.side\}/);
  assert.match(source, /--popover-left/);
  assert.match(source, /--popover-arrow-y/);
  assert.match(source, /posts-calendar-popover-open/);
  assert.match(source, /\.posts-calendar-popover\[data-side="right"\]::before/);
  assert.doesNotMatch(source, /background:color-mix\(in srgb,var\(--overlay\) 48%,transparent\)/);
});
