import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const calendarViewPath = path.join(root, "src/components/posts/calendar/posts-calendar-view.tsx");

test("Posts calendar view keeps the requested calendar controls and drawer integration", async () => {
  const source = await readFile(calendarViewPath, "utf8");

  assert.match(source, /export function PostsCalendarView/);
  assert.match(source, /CreatePostDrawer/);
  assert.match(source, /List View/);
  assert.match(source, /Create \+/);
  assert.match(source, /Day/);
  assert.match(source, /Week/);
  assert.match(source, /Month/);
  assert.match(source, /usePathname,\s*useParams,\s*useRouter,\s*useSearchParams/);
  assert.match(source, /parseCalendarViewMode\(searchParams\.get\("view"\)\)/);
  assert.match(source, /replaceCalendarMode\("day"\)/);
  assert.match(source, /replaceCalendarMode\("week"\)/);
  assert.match(source, /replaceCalendarMode\("month"\)/);
  assert.match(source, /nextParams\.set\("view",\s*mode\)/);
  assert.match(source, /router\.replace\(`\$\{pathname\}\$\{query \? `\?\$\{query\}` : ""\}`,\s*\{\s*scroll:\s*false\s*\}\)/);
  assert.match(source, /renderWeekView/);
  assert.match(source, /renderDayView/);
  assert.match(source, /handleCalendarWheel/);
  assert.match(source, /handleCalendarTouchStart/);
  assert.match(source, /handleCalendarTouchEnd/);
  assert.match(source, /shiftCalendarBySwipe/);
  assert.match(source, /shiftCalendarDateBySwipe/);
  assert.match(source, /getSwipeNavigationIntent/);
  assert.match(source, /onTouchStart=\{handleCalendarTouchStart\}/);
  assert.match(source, /onTouchEnd=\{handleCalendarTouchEnd\}/);
  assert.match(source, /formatWeekdayShort\(day\.date\)/);
  assert.match(source, /posts-calendar-week-grid/);
  assert.match(source, /posts-calendar-day-grid/);
  assert.match(source, /posts-calendar-time-scroll/);
  assert.match(source, /--calendar-time-gutter:76px/);
  assert.match(source, /--calendar-week-day-min:132px/);
  assert.match(source, /--calendar-week-template:var\(--calendar-time-gutter\) repeat\(7,minmax\(var\(--calendar-week-day-min\),1fr\)\)/);
  assert.match(source, /weekScrollbarWidth/);
  assert.match(source, /offsetWidth - node\.clientWidth/);
  assert.match(source, /posts-calendar-week-header-inner/);
  assert.match(source, /posts-calendar-week-scrollbar-spacer/);
  assert.match(source, /\.posts-calendar-week-header\{[^}]*grid-template-columns:minmax\(0,1fr\) var\(--calendar-scrollbar-gutter\)/);
  assert.match(source, /\.posts-calendar-week-header-inner\{[^}]*grid-template-columns:var\(--calendar-week-template\)/);
  assert.match(source, /\.posts-calendar-week-grid \.posts-calendar-time-scroll\{[^}]*grid-template-columns:var\(--calendar-week-template\)/);
  assert.match(source, /\.posts-calendar-week-columns\{[^}]*grid-column:2\/-1/);
  assert.match(source, /\.posts-calendar-all-day-label,[^}]*white-space:nowrap/);
  assert.match(source, /All Status/);
  assert.match(source, /In Progress/);
  assert.match(source, /Cancelled/);
  assert.match(source, /Archived/);
  assert.match(source, /bucketPostByLocalDay/);
  assert.match(source, /buildWeekDays/);
  assert.match(source, /getCalendarPostMinuteOfDay/);
  assert.match(source, /getWheelNavigationIntent/);
  assert.match(source, /getProfileCalendarColor/);
  assert.match(source, /shouldShowPostForStatusFilter/);
  assert.match(source, /posts-calendar-fullheight/);
  assert.match(source, /resolvedOptions\(\)\.timeZone/);
});
