-- +goose Up
-- RBAC Phase 4 (May 2026): pending invite tracking.
--
-- Why a separate table instead of pending memberships:
--   - Invites target an email that may NOT have a UniPost user yet —
--     the signup-after-invite flow needs to identify the invite by a
--     URL token, not a (workspace_id, user_id) tuple that doesn't
--     exist until the user signs up.
--   - One-time-use tokens are a separate concept from membership
--     state; conflating them makes "invite revoked vs membership
--     suspended" ambiguous.
--   - Audit-log writes for "MEMBER.INVITED" point at the invite row;
--     "MEMBER.JOINED" writes a separate row referencing the resulting
--     workspace_members row.
--
-- Tokens are 256-bit URL-safe base64 (43 chars) generated by the
-- existing apikey.RandomBase64URL helper. No HMAC — the token IS the
-- secret; possession alone authorizes acceptance. Expiry defaults to
-- 7 days at creation time.

CREATE TABLE workspace_invites (
    id           TEXT PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id TEXT        NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    email        TEXT        NOT NULL,
    role         TEXT        NOT NULL CHECK (role IN ('admin','editor')), -- can't invite owner
    token        TEXT        NOT NULL UNIQUE,
    invited_by   TEXT        NOT NULL,
    expires_at   TIMESTAMPTZ NOT NULL,
    accepted_at  TIMESTAMPTZ,                                 -- NULL = still pending
    revoked_at   TIMESTAMPTZ,                                 -- NULL = not revoked
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Look up by token (the hot path during accept).
CREATE INDEX workspace_invites_token_idx ON workspace_invites (token);

-- Pending invites by email (used by the dashboard members page +
-- duplicate-invite guards).
CREATE INDEX workspace_invites_email_pending_idx
    ON workspace_invites (email)
    WHERE accepted_at IS NULL AND revoked_at IS NULL;

-- All pending invites for a workspace, sorted newest-first for the UI.
CREATE INDEX workspace_invites_workspace_idx
    ON workspace_invites (workspace_id, created_at DESC);

-- +goose Down
DROP TABLE IF EXISTS workspace_invites;
