-- +goose Up
--
-- Redacted reports generated by `unipost doctor support-bundle --upload`.
-- The report is customer-opt-in, workspace-scoped, and super-admin readable.

CREATE TABLE support_bundles (
  id                 TEXT PRIMARY KEY,
  workspace_id       TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  actor_user_id      TEXT,
  actor_api_key_id   TEXT,
  run_id             TEXT NOT NULL,
  schema_version     TEXT NOT NULL,
  cli_version        TEXT NOT NULL DEFAULT '',
  summary            TEXT NOT NULL DEFAULT '',
  report_markdown    TEXT NOT NULL,
  payload            JSONB NOT NULL DEFAULT '{}'::jsonb,
  finding_count      INTEGER NOT NULL DEFAULT 0,
  recent_error_count INTEGER NOT NULL DEFAULT 0,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX support_bundles_workspace_run_idx
  ON support_bundles (workspace_id, run_id);

CREATE INDEX support_bundles_workspace_created_idx
  ON support_bundles (workspace_id, created_at DESC);

CREATE INDEX support_bundles_created_idx
  ON support_bundles (created_at DESC);

-- +goose Down

DROP TABLE IF EXISTS support_bundles;
